export type Institution = {
  slug: string;
  name: string;
  city: string;
  ttoName: string;
  website: string;
  specialties: string[];
  continent?: string;
  noPublicPortal?: boolean;
};

export const INSTITUTIONS: Institution[] = [
  // ── Tier-1 US Research Universities ──────────────────────────────────────
  { slug: "stanford", name: "Stanford University", city: "Palo Alto, CA", ttoName: "Stanford OTT", website: "https://ottech.stanford.edu", specialties: ["Oncology", "Neuroscience", "Gene Therapy"] },
  { slug: "mit", name: "MIT", city: "Cambridge, MA", ttoName: "MIT Technology Licensing Office", website: "https://tlo.mit.edu", specialties: ["Bioelectronics", "Drug Delivery", "Immunology"] },
  { slug: "harvard", name: "Harvard University", city: "Boston, MA", ttoName: "Harvard OTD", website: "https://otd.harvard.edu", specialties: ["Oncology", "Gene Editing", "Immunotherapy"] },
  { slug: "jhu", name: "Johns Hopkins University", city: "Baltimore, MD", ttoName: "Johns Hopkins TTO", website: "https://ventures.jhu.edu", specialties: ["Infectious Disease", "Oncology", "Neuroscience"] },
  { slug: "ucsf", name: "UC San Francisco", city: "San Francisco, CA", ttoName: "UCSF Innovation Ventures", website: "https://inno.ucsf.edu", specialties: ["Oncology", "Rare Disease", "Immunology"] },
  { slug: "duke", name: "Duke University", city: "Durham, NC", ttoName: "Duke OLV", website: "https://olv.duke.edu", specialties: ["Cardiovascular", "Immunotherapy", "mRNA"] },
  { slug: "columbia", name: "Columbia University", city: "New York, NY", ttoName: "Columbia Technology Ventures", website: "https://techventures.columbia.edu", specialties: ["Neuroscience", "Oncology", "Gene Therapy"] },
  { slug: "upenn", name: "University of Pennsylvania", city: "Philadelphia, PA", ttoName: "Penn Center for Innovation", website: "https://pci.upenn.edu", specialties: ["Gene Therapy", "CAR-T", "mRNA"] },
  { slug: "northwestern", name: "Northwestern University", city: "Evanston, IL", ttoName: "Northwestern TTO", website: "https://tto.northwestern.edu", specialties: ["Drug Delivery", "Oncology", "Bioelectronics"] },
  { slug: "cornell", name: "Cornell University", city: "Ithaca, NY", ttoName: "Cornell Center for TT", website: "https://ctt.cornell.edu", specialties: ["Metabolic Disease", "Antimicrobials", "Oncology"] },
  { slug: "ucberkeley", name: "UC Berkeley", city: "Berkeley, CA", ttoName: "UC Berkeley Intellectual Property Office", website: "https://ipira.berkeley.edu", specialties: ["CRISPR", "Synthetic Biology", "Drug Discovery"] },
  { slug: "uwashington", name: "University of Washington", city: "Seattle, WA", ttoName: "UW CoMotion", website: "https://comotion.uw.edu", specialties: ["Neuroscience", "Oncology", "Structural Biology"]  },
  { slug: "wustl", name: "Washington University in St. Louis", city: "St. Louis, MO", ttoName: "WashU OTM", website: "https://otm.wustl.edu", specialties: ["Neuroscience", "Metabolic Disease", "Immunology"] },
  { slug: "umich", name: "University of Michigan", city: "Ann Arbor, MI", ttoName: "U-M Tech Transfer", website: "https://umich.flintbox.com", specialties: ["Cardiovascular", "Gene Therapy", "Oncology"] },
  { slug: "gatech", name: "Georgia Institute of Technology", city: "Atlanta, GA", ttoName: "Georgia Tech VentureLab", website: "https://gatech.flintbox.com", specialties: ["Robotics", "Advanced Materials", "Biomedical Engineering"] },
  { slug: "mayo", name: "Mayo Clinic", city: "Rochester, MN", ttoName: "Mayo Clinic Ventures", website: "https://ventures.mayoclinic.org", specialties: ["Diagnostics", "Oncology", "Rare Disease"] },
  { slug: "scripps", name: "Scripps Research", city: "La Jolla, CA", ttoName: "Scripps Research TTVD", website: "https://www.scripps.edu/science-and-medicine/ttvd", specialties: ["Drug Discovery", "Antibody Engineering", "Oncology"] , noPublicPortal: true },
  { slug: "salk", name: "Salk Institute", city: "La Jolla, CA", ttoName: "Salk TTO", website: "https://www.salk.edu/partnerships-commercialization", specialties: ["Gene Regulation", "Oncology", "Aging"] , noPublicPortal: true },
  { slug: "mdanderson", name: "MD Anderson Cancer Center", city: "Houston, TX", ttoName: "MD Anderson TTO", website: "https://www.mdanderson.org/research/departments-labs-institutes/programs-centers/technology-commercialization.html", specialties: ["Oncology", "Immunotherapy", "CAR-T"] , noPublicPortal: true },
  { slug: "upitt", name: "University of Pittsburgh", city: "Pittsburgh, PA", ttoName: "Pitt Innovation Institute", website: "https://www.innovation.pitt.edu", specialties: ["Regenerative Medicine", "Oncology", "Organ Transplant"] },
  { slug: "uchicago", name: "University of Chicago", city: "Chicago, IL", ttoName: "UChicago Polsky Center", website: "https://polsky.uchicago.edu/programs-and-services/george-shultz-innovation-fund", specialties: ["Immunology", "Drug Delivery", "Oncology"] },
  { slug: "vanderbilt", name: "Vanderbilt University", city: "Nashville, TN", ttoName: "Vanderbilt Center for Technology Transfer", website: "https://ctt.vanderbilt.edu", specialties: ["Small Molecules", "Metabolic Disease", "Infectious Disease"] },
  { slug: "emory", name: "Emory University", city: "Atlanta, GA", ttoName: "Emory OTT", website: "https://ott.emory.edu", specialties: ["Infectious Disease", "Neuroscience", "Vaccines"] },
  { slug: "bu", name: "Boston University", city: "Boston, MA", ttoName: "BU Technology Development", website: "https://www.bu.edu/otd", specialties: ["Oncology", "Drug Delivery", "Rare Disease"] },
  { slug: "georgetown", name: "Georgetown University", city: "Washington, DC", ttoName: "Georgetown OTL", website: "https://otl.georgetown.edu", specialties: ["Oncology", "Immunology", "Small Molecules"] },
  { slug: "utexas", name: "University of Texas", city: "Austin, TX", ttoName: "UT Office of Technology Commercialization", website: "https://research.utexas.edu/otc", specialties: ["Oncology", "Gene Therapy", "Bioelectronics"] },
  { slug: "cwru", name: "Case Western Reserve University", city: "Cleveland, OH", ttoName: "CWRU TTO", website: "https://research.case.edu/tto", specialties: ["Orthopedics", "Neuroscience", "Biomaterials"] , noPublicPortal: true },
  { slug: "ucolorado", name: "University of Colorado", city: "Aurora, CO", ttoName: "CU Innovations", website: "https://innovations.cu.edu", specialties: ["Oncology", "Respiratory", "Rare Disease"] },
  { slug: "princeton", name: "Princeton University", city: "Princeton, NJ", ttoName: "Princeton OTL", website: "https://puotl.technologypublisher.com", specialties: ["Drug Discovery", "Materials Science", "Neuroscience"] },
  { slug: "ucla", name: "UCLA", city: "Los Angeles, CA", ttoName: "UCLA Technology Development Group", website: "https://ucla.technologypublisher.com", specialties: ["Oncology", "Stem Cells", "Immunotherapy"] },
  { slug: "brown", name: "Brown University", city: "Providence, RI", ttoName: "Brown Technology Innovations", website: "https://brown.technologypublisher.com", specialties: ["Neuroscience", "Drug Delivery", "Biomaterials"] },
  { slug: "rochester", name: "University of Rochester", city: "Rochester, NY", ttoName: "UR Ventures", website: "https://rochester.technologypublisher.com", specialties: ["Oncology", "Optics", "Drug Delivery"] },
  { slug: "tufts", name: "Tufts University", city: "Medford, MA", ttoName: "Tufts Technology Services", website: "https://tufts.technologypublisher.com", specialties: ["Drug Delivery", "Biomaterials", "Infectious Disease"] },
  { slug: "uthealth", name: "UT Health", city: "Houston, TX", ttoName: "UT Health Office of Technology Management", website: "https://uthealth.technologypublisher.com", specialties: ["Oncology", "Cardiovascular", "Diagnostics"] },
  { slug: "coloradostate", name: "Colorado State University", city: "Fort Collins, CO", ttoName: "CSU Ventures", website: "https://csuventures.technologypublisher.com", specialties: ["Infectious Disease", "Drug Delivery", "Agricultural Biotech"] },
  { slug: "virginiatech", name: "Virginia Tech", city: "Blacksburg, VA", ttoName: "Virginia Tech Intellectual Properties", website: "https://vtip.technologypublisher.com", specialties: ["Biosensors", "Drug Delivery", "Oncology"] },
  { slug: "usf", name: "University of South Florida", city: "Tampa, FL", ttoName: "USF Technology Transfer", website: "https://usf.technologypublisher.com", specialties: ["Oncology", "Neuroscience", "Infectious Disease"] },
  { slug: "waynestate", name: "Wayne State University", city: "Detroit, MI", ttoName: "Wayne State Tech Transfer", website: "https://wayne.technologypublisher.com", specialties: ["Oncology", "Drug Discovery", "Rare Disease"] },
  { slug: "utdallas", name: "UT Dallas", city: "Richardson, TX", ttoName: "UT Dallas Technology Commercialization", website: "https://utdallas.technologypublisher.com", specialties: ["Bioelectronics", "Neuroscience", "Drug Delivery"] },
  { slug: "msstate", name: "Mississippi State University", city: "Starkville, MS", ttoName: "MSU Technology Management", website: "https://msstate-innovations.technologypublisher.com", specialties: ["Agricultural Biotech", "Diagnostics", "Biosensors"] },
  { slug: "utoledo", name: "University of Toledo", city: "Toledo, OH", ttoName: "UT Technology Transfer", website: "https://utoledo.technologypublisher.com", specialties: ["Drug Discovery", "Oncology", "Metabolic Disease"] },
  { slug: "njit", name: "New Jersey Institute of Technology", city: "Newark, NJ", ttoName: "NJIT Technology Transfer", website: "https://njit.technologypublisher.com", specialties: ["Biomaterials", "Drug Delivery", "Biosensors"] },
  { slug: "calpoly", name: "Cal Poly San Luis Obispo", city: "San Luis Obispo, CA", ttoName: "Cal Poly Technology Transfer", website: "https://calpoly.technologypublisher.com", specialties: ["Agricultural Biotech", "Biosensors", "Drug Delivery"] },
  { slug: "slu", name: "Saint Louis University", city: "St. Louis, MO", ttoName: "SLU Technology Management", website: "https://slu.technologypublisher.com", specialties: ["Oncology", "Infectious Disease", "Drug Discovery"] },
  { slug: "ucdavis", name: "UC Davis", city: "Davis, CA", ttoName: "UC Davis InnovationAccess", website: "https://ucdavis.technologypublisher.com", specialties: ["Agricultural Biotech", "Oncology", "Regenerative Medicine"] },
  { slug: "utah", name: "University of Utah", city: "Salt Lake City, UT", ttoName: "University of Utah Technology Licensing Office", website: "https://utah.technologypublisher.com", specialties: ["Drug Delivery", "Bioelectronics", "Oncology"] },
  { slug: "uva", name: "University of Virginia", city: "Charlottesville, VA", ttoName: "UVA Licensing & Ventures Group", website: "https://uva.technologypublisher.com", specialties: ["Oncology", "Neuroscience", "Drug Discovery"] },
  { slug: "uoregon", name: "University of Oregon", city: "Eugene, OR", ttoName: "UO Office for Research", website: "https://uoregon.technologypublisher.com", specialties: ["Neuroscience", "Drug Discovery", "Biomaterials"] },
  { slug: "gwu", name: "George Washington University", city: "Washington, DC", ttoName: "GWU Office of Technology Transfer", website: "https://gwu.technologypublisher.com", specialties: ["Oncology", "Infectious Disease", "Diagnostics"] },
  { slug: "czbiohub", name: "CZ Biohub", city: "San Francisco, CA", ttoName: "CZ Biohub Technology Transfer", website: "https://czbiohub.technologypublisher.com", specialties: ["CRISPR", "Diagnostics", "Infectious Disease"] },
  { slug: "musc", name: "Medical University of South Carolina", city: "Charleston, SC", ttoName: "MUSC Foundation for Research Development", website: "https://musc.technologypublisher.com", specialties: ["Oncology", "Cardiovascular", "Rare Disease"] },
  { slug: "southcarolina", name: "University of South Carolina", city: "Columbia, SC", ttoName: "USC Technology Commercialization Office", website: "https://sc.technologypublisher.com", specialties: ["Drug Delivery", "Biomaterials", "Oncology"] },
  { slug: "lehigh", name: "Lehigh University", city: "Bethlehem, PA", ttoName: "Lehigh Office of Technology Transfer", website: "https://lehighott.technologypublisher.com", specialties: ["Biosensors", "Drug Delivery", "Materials Science"] },
  { slug: "clemson", name: "Clemson University", city: "Clemson, SC", ttoName: "Clemson University Research Foundation", website: "https://curf.technologypublisher.com", specialties: ["Biomaterials", "Agricultural Biotech", "Drug Delivery"] },
  { slug: "iowastate", name: "Iowa State University", city: "Ames, IA", ttoName: "Iowa State University Research Foundation", website: "https://isurftech.technologypublisher.com", specialties: ["Agricultural Biotech", "Drug Delivery", "Biosensors"] },
  { slug: "tgen", name: "Translational Genomics Research Institute", city: "Phoenix, AZ", ttoName: "TGen Technology Transfer", website: "https://tgen.technologypublisher.com", specialties: ["Genomics", "Oncology", "Rare Disease"] },
  { slug: "wsu", name: "Washington State University", city: "Pullman, WA", ttoName: "WSU Office of Commercialization", website: "https://wsu.technologypublisher.com", specialties: ["Agricultural Biotech", "Drug Delivery", "Biosensors"] },
  { slug: "arizona", name: "University of Arizona", city: "Tucson, AZ", ttoName: "Tech Launch Arizona", website: "https://arizona.technologypublisher.com", specialties: ["Oncology", "Drug Discovery", "Optics"] },
  { slug: "pennstate", name: "Penn State University", city: "University Park, PA", ttoName: "Penn State Office of TT", website: "https://pennstate.technologypublisher.com", specialties: ["Biomaterials", "Drug Delivery", "Biosensors"] },
  { slug: "rutgers", name: "Rutgers University", city: "New Brunswick, NJ", ttoName: "Rutgers Office of Research Commercialization", website: "https://rutgers.technologypublisher.com", specialties: ["Drug Discovery", "Oncology", "Infectious Disease"] },
  { slug: "stevens", name: "Stevens Institute of Technology", city: "Hoboken, NJ", ttoName: "Stevens TTO", website: "https://stevens.technologypublisher.com", specialties: ["Bioelectronics", "Biosensors", "Drug Delivery"] },
  { slug: "rpi", name: "Rensselaer Polytechnic Institute", city: "Troy, NY", ttoName: "RPI Office of TT", website: "https://rpi.technologypublisher.com", specialties: ["Biomaterials", "Drug Delivery", "Bioelectronics"] },
  { slug: "stonybrook", name: "Stony Brook University", city: "Stony Brook, NY", ttoName: "Stony Brook TTO", website: "https://stonybrook.technologypublisher.com", specialties: ["Oncology", "Drug Discovery", "Neuroscience"] },
  { slug: "cincinnati", name: "University of Cincinnati", city: "Cincinnati, OH", ttoName: "UC Office of Technology Transfer", website: "https://uc.technologypublisher.com", specialties: ["Oncology", "Drug Delivery", "Cardiovascular"] },
  { slug: "buffalo", name: "University at Buffalo", city: "Buffalo, NY", ttoName: "UB Technology Transfer", website: "https://buffalo.technologypublisher.com", specialties: ["Oncology", "Drug Discovery", "Neuroscience"] },
  { slug: "rowan", name: "Rowan University", city: "Glassboro, NJ", ttoName: "Rowan Innovation Ventures", website: "https://rowan.technologypublisher.com", specialties: ["Biomaterials", "Drug Delivery", "Diagnostics"] },
  { slug: "georgemason", name: "George Mason University", city: "Fairfax, VA", ttoName: "Mason Enterprise Center", website: "https://mason.technologypublisher.com", specialties: ["Biosensors", "Drug Delivery", "Bioelectronics"] },
  { slug: "umaine", name: "University of Maine", city: "Orono, ME", ttoName: "UMaine Office of Innovation", website: "https://umaine.technologypublisher.com", specialties: ["Biomaterials", "Agricultural Biotech", "Drug Delivery"] },
  { slug: "binghamton", name: "Binghamton University", city: "Binghamton, NY", ttoName: "Binghamton TTO", website: "https://binghamton.technologypublisher.com", specialties: ["Oncology", "Drug Discovery", "Biosensors"] },
  { slug: "usc", name: "University of Southern California", city: "Los Angeles, CA", ttoName: "USC Stevens Center for Innovation", website: "https://usc.technologypublisher.com", specialties: ["Neuroscience", "Drug Delivery", "Oncology"] },
  { slug: "oregonstate", name: "Oregon State University", city: "Corvallis, OR", ttoName: "OSU Office for Commercialization", website: "https://oregonstate.technologypublisher.com", specialties: ["Agricultural Biotech", "Drug Discovery", "Biomaterials"] },
  { slug: "gsu", name: "Georgia State University", city: "Atlanta, GA", ttoName: "GSU Office of Technology Transfer", website: "https://gsu.technologypublisher.com", specialties: ["Drug Discovery", "Oncology", "Infectious Disease"] },
  { slug: "northeastern", name: "Northeastern University", city: "Boston, MA", ttoName: "Northeastern TTO", website: "https://nu.technologypublisher.com", specialties: ["Drug Delivery", "Biosensors", "Bioelectronics"] },
  { slug: "uvm", name: "University of Vermont", city: "Burlington, VT", ttoName: "UVM Office of Technology Commercialization", website: "https://uvm.technologypublisher.com", specialties: ["Metabolic Disease", "Oncology", "Drug Discovery"] },
  { slug: "usd", name: "University of South Dakota", city: "Vermillion, SD", ttoName: "USD Office of Research", website: "https://usd.technologypublisher.com", specialties: ["Drug Discovery", "Diagnostics", "Rare Disease"] },
  { slug: "txstate", name: "Texas State University", city: "San Marcos, TX", ttoName: "Texas State TTO", website: "https://txstate.technologypublisher.com", specialties: ["Drug Delivery", "Biosensors", "Materials Science"] },
  { slug: "yale", name: "Yale University", city: "New Haven, CT", ttoName: "Yale OCS", website: "https://ventures.yale.edu/yale-technologies", specialties: ["Oncology", "Immunotherapy", "Structural Biology"] },
  { slug: "purdue", name: "Purdue University", city: "West Lafayette, IN", ttoName: "Purdue Research Foundation OTC", website: "https://licensing.prf.org/products", specialties: ["Drug Delivery", "Bioelectronics", "Agricultural Biotech"] },
  { slug: "umn", name: "University of Minnesota", city: "Minneapolis, MN", ttoName: "University of Minnesota Technology Commercialization", website: "https://license.umn.edu/products", specialties: ["Oncology", "Neuroscience", "Gene Therapy"] },
  { slug: "miami", name: "University of Miami", city: "Miami, FL", ttoName: "UM Office of Technology Transfer", website: "https://miami.technologypublisher.com", specialties: ["Oncology", "Immunology", "Drug Discovery"] },
  { slug: "upstate", name: "SUNY Upstate Medical University", city: "Syracuse, NY", ttoName: "Upstate Medical TTO", website: "https://upstate.technologypublisher.com", specialties: ["Oncology", "Rare Disease", "Diagnostics"] },
  { slug: "suny", name: "SUNY System", city: "Albany, NY", ttoName: "SUNY Research Foundation", website: "https://suny.technologypublisher.com", specialties: ["Drug Discovery", "Biosensors", "Biomaterials"] },
  { slug: "alabama", name: "University of Alabama", city: "Tuscaloosa, AL", ttoName: "UA Office of Technology Transfer", website: "https://ua.technologypublisher.com", specialties: ["Drug Delivery", "Oncology", "Materials Science"] },
  { slug: "wyoming", name: "University of Wyoming", city: "Laramie, WY", ttoName: "UW Technology Transfer", website: "https://uwyo.technologypublisher.com", specialties: ["Agricultural Biotech", "Drug Discovery", "Energy"] },
  { slug: "idaho", name: "University of Idaho", city: "Moscow, ID", ttoName: "UI Office of Technology Transfer", website: "https://uidaho.technologypublisher.com", specialties: ["Agricultural Biotech", "Drug Discovery", "Biosensors"] },

  // ── New US Institutions ───────────────────────────────────────────────────
  // Florida
  { slug: "fsu", name: "Florida State University", city: "Tallahassee, FL", ttoName: "FSU Office of Commercialization", website: "https://commercialization.fsu.edu", specialties: ["Drug Discovery", "Neuroscience", "Materials Science"] , noPublicPortal: true },
  { slug: "ucf", name: "University of Central Florida", city: "Orlando, FL", ttoName: "UCF Office of Technology Transfer", website: "https://tt.research.ucf.edu", specialties: ["Bioelectronics", "Drug Delivery", "Diagnostics"]  },
  { slug: "fiu", name: "Florida International University", city: "Miami, FL", ttoName: "FIU Office of Technology Management", website: "https://research.fiu.edu/otm", specialties: ["Oncology", "Biosensors", "Drug Delivery"]  },
  // Texas
  { slug: "tamu", name: "Texas A&M University", city: "College Station, TX", ttoName: "Texas A&M Innovation Partners", website: "https://innovationpartners.tamu.edu", specialties: ["Agricultural Biotech", "Drug Delivery", "Oncology"] , noPublicPortal: true },
  { slug: "rice", name: "Rice University", city: "Houston, TX", ttoName: "Rice University OTT", website: "https://ott.rice.edu", specialties: ["Drug Delivery", "Bioelectronics", "Oncology"]  },
  { slug: "uhouston", name: "University of Houston", city: "Houston, TX", ttoName: "UH Office of Technology Transfer", website: "https://www.uh.edu/research/technology-transfer", specialties: ["Drug Discovery", "Biosensors", "Oncology"] , noPublicPortal: true },
  { slug: "texastech", name: "Texas Tech University", city: "Lubbock, TX", ttoName: "Texas Tech Innovation Hub", website: "https://www.depts.ttu.edu/research/commercialization", specialties: ["Drug Discovery", "Biomaterials", "Agricultural Biotech"]  },
  { slug: "unt", name: "University of North Texas", city: "Denton, TX", ttoName: "UNT Innovation & Commercialization", website: "https://research.unt.edu/innovation", specialties: ["Drug Discovery", "Biomaterials", "Diagnostics"] , noPublicPortal: true },
  { slug: "baylor", name: "Baylor University", city: "Waco, TX", ttoName: "Baylor Commercialization Office", website: "https://research.baylor.edu/commercialization", specialties: ["Drug Discovery", "Oncology", "Neuroscience"]  },
  // Pacific NW
  { slug: "portlandstate", name: "Portland State University", city: "Portland, OR", ttoName: "PSU Innovation & Commercialization", website: "https://www.pdx.edu/research/innovation-commercialization", specialties: ["Biosensors", "Drug Delivery", "Biomaterials"] , noPublicPortal: true },
  // Mountain West
  { slug: "umontana", name: "University of Montana", city: "Missoula, MT", ttoName: "UM Office of Technology Transfer", website: "https://www.umt.edu/research/technology-transfer", specialties: ["Drug Discovery", "Infectious Disease", "Agricultural Biotech"] , noPublicPortal: true },
  { slug: "montanastate", name: "Montana State University", city: "Bozeman, MT", ttoName: "MSU Technology Transfer", website: "https://www.montana.edu/research/techtransfer", specialties: ["Drug Delivery", "Biosensors", "Agricultural Biotech"] },
  { slug: "unm", name: "University of New Mexico", city: "Albuquerque, NM", ttoName: "UNM Rainforest Innovations", website: "https://rainforestinnovations.com", specialties: ["Drug Discovery", "Oncology", "Biosensors"]  },
  { slug: "nmsu", name: "New Mexico State University", city: "Las Cruces, NM", ttoName: "NMSU Arrowhead Center", website: "https://arrowheadcenter.nmsu.edu", specialties: ["Agricultural Biotech", "Drug Discovery", "Biosensors"] , noPublicPortal: true },
  { slug: "unr", name: "University of Nevada, Reno", city: "Reno, NV", ttoName: "UNR Office of Technology Transfer", website: "https://www.unr.edu/research/technology-transfer", specialties: ["Drug Discovery", "Neuroscience", "Biosensors"] , noPublicPortal: true },
  { slug: "unlv", name: "University of Nevada, Las Vegas", city: "Las Vegas, NV", ttoName: "UNLV Innovation Office", website: "https://www.unlv.edu/research/innovation", specialties: ["Drug Delivery", "Diagnostics", "Biomaterials"] , noPublicPortal: true },
  { slug: "usu", name: "Utah State University", city: "Logan, UT", ttoName: "USU Innovation Campus", website: "https://innovationcampus.usu.edu", specialties: ["Drug Delivery", "Agricultural Biotech", "Biosensors"]  },
  { slug: "byu", name: "Brigham Young University", city: "Provo, UT", ttoName: "BYU Technology Transfer Office", website: "https://techtransfer.byu.edu", specialties: ["Drug Delivery", "Biosensors", "Biomaterials"] , noPublicPortal: true },
  { slug: "uaf", name: "University of Alaska Fairbanks", city: "Fairbanks, AK", ttoName: "UAF Innovation Office", website: "https://www.uaf.edu/research/innovation", specialties: ["Biosensors", "Drug Discovery", "Environmental Health"] },
  { slug: "uaa", name: "University of Alaska Anchorage", city: "Anchorage, AK", ttoName: "UAA Innovation Office", website: "https://www.uaa.alaska.edu/research", specialties: ["Diagnostics", "Biosensors", "Environmental Health"] , noPublicPortal: true },
  // Midwest
  { slug: "und", name: "University of North Dakota", city: "Grand Forks, ND", ttoName: "UND Innovation Office", website: "https://und.edu/research/innovation", specialties: ["Drug Discovery", "Diagnostics", "Rare Disease"] , noPublicPortal: true },
  { slug: "ndsu", name: "North Dakota State University", city: "Fargo, ND", ttoName: "NDSU Technology Transfer", website: "https://www.ndsu.edu/research/techtransfer", specialties: ["Agricultural Biotech", "Drug Delivery", "Biomaterials"] },
  { slug: "sdstate", name: "South Dakota State University", city: "Brookings, SD", ttoName: "SDSU Innovation Office", website: "https://www.sdstate.edu/research/innovation", specialties: ["Agricultural Biotech", "Drug Delivery", "Diagnostics"] },
  { slug: "indiana", name: "Indiana University", city: "Bloomington, IN", ttoName: "IU Innovation & Commercialization Office", website: "https://innovation.iu.edu", specialties: ["Drug Discovery", "Oncology", "Neuroscience"] },
  { slug: "notredame", name: "University of Notre Dame", city: "Notre Dame, IN", ttoName: "Notre Dame IDEA Center", website: "https://ideacenter.nd.edu", specialties: ["Drug Delivery", "Oncology", "Rare Disease"] , noPublicPortal: true },
  { slug: "warf", name: "University of Wisconsin", city: "Madison, WI", ttoName: "Wisconsin Alumni Research Foundation", website: "https://www.warf.org", specialties: ["Drug Discovery", "Gene Therapy", "Oncology"] , noPublicPortal: true },
  // Southeast
  { slug: "auburn", name: "Auburn University", city: "Auburn, AL", ttoName: "Auburn Commercialization Office", website: "https://www.auburn.edu/research/innovation", specialties: ["Drug Discovery", "Agricultural Biotech", "Biomaterials"]  },
  { slug: "uga", name: "University of Georgia", city: "Athens, GA", ttoName: "UGA Innovation Gateway", website: "https://research.uga.edu/gateway", specialties: ["Infectious Disease", "Agricultural Biotech", "Drug Discovery"]  },
  { slug: "uarkansas", name: "University of Arkansas", city: "Fayetteville, AR", ttoName: "UA Tech Ventures", website: "https://techventures.uark.edu", specialties: ["Agricultural Biotech", "Drug Delivery", "Biomaterials"] , noPublicPortal: true },
  { slug: "uams", name: "University of Arkansas for Medical Sciences", city: "Little Rock, AR", ttoName: "UAMS BioVentures", website: "https://bioventures.uams.edu", specialties: ["Oncology", "Drug Discovery", "Rare Disease"] , noPublicPortal: true },
  { slug: "olemiss", name: "University of Mississippi", city: "Oxford, MS", ttoName: "Ole Miss Research & Innovation", website: "https://research.olemiss.edu/innovation", specialties: ["Drug Discovery", "Pharmaceutics", "Natural Products"] },
  // Northeast/Mid-Atlantic
  { slug: "udel", name: "University of Delaware", city: "Newark, DE", ttoName: "UD Office of Technology Transfer", website: "https://www.udel.edu/research/technology-transfer", specialties: ["Drug Delivery", "Biomaterials", "Oncology"]  },
  { slug: "temple", name: "Temple University", city: "Philadelphia, PA", ttoName: "Temple Innovation Office", website: "https://research.temple.edu/innovation", specialties: ["Drug Discovery", "Oncology", "Infectious Disease"] , noPublicPortal: true },
  { slug: "drexel", name: "Drexel University", city: "Philadelphia, PA", ttoName: "Drexel Applied Innovation Office", website: "https://drexel.edu/research/innovation", specialties: ["Biomaterials", "Drug Delivery", "Bioelectronics"] , noPublicPortal: true },
  { slug: "bucknell", name: "Bucknell University", city: "Lewisburg, PA", ttoName: "Bucknell Innovation Office", website: "https://www.bucknell.edu/research/innovation", specialties: ["Drug Delivery", "Biosensors", "Biomaterials"] , noPublicPortal: true },
  { slug: "sunyalbany", name: "SUNY Albany", city: "Albany, NY", ttoName: "SUNY Albany Innovation Office", website: "https://www.albany.edu/research/innovation", specialties: ["Drug Discovery", "Oncology", "Infectious Disease"] , noPublicPortal: true },
  { slug: "uconn", name: "University of Connecticut", city: "Storrs, CT", ttoName: "UConn Technology Commercialization", website: "https://innovation.uconn.edu", specialties: ["Drug Delivery", "Oncology", "Biomaterials"]  },
  { slug: "dartmouth", name: "Dartmouth College", city: "Hanover, NH", ttoName: "Dartmouth Technology Transfer", website: "https://techtransfer.dartmouth.edu", specialties: ["Drug Discovery", "Oncology", "Bioelectronics"]  },
  { slug: "brandeis", name: "Brandeis University", city: "Waltham, MA", ttoName: "Brandeis Office of Technology Licensing", website: "https://www.brandeis.edu/research/innovation", specialties: ["Drug Discovery", "Neuroscience", "Structural Biology"]  },
  { slug: "unh", name: "University of New Hampshire", city: "Durham, NH", ttoName: "UNH Innovation Office", website: "https://www.unh.edu/research/innovation", specialties: ["Drug Discovery", "Agricultural Biotech", "Biomaterials"] , noPublicPortal: true },
  { slug: "uri", name: "University of Rhode Island", city: "Kingston, RI", ttoName: "URI Innovation Office", website: "https://web.uri.edu/research/commercialization", specialties: ["Drug Delivery", "Oncology", "Natural Products"]  },
  { slug: "mountsinai", name: "Icahn School of Medicine at Mount Sinai", city: "New York, NY", ttoName: "Mount Sinai Technology Transfer", website: "https://icahn.mssm.edu/research/technology-transfer", specialties: ["Oncology", "Neuroscience", "Gene Therapy"] },
  // Other US
  { slug: "caltech", name: "California Institute of Technology", city: "Pasadena, CA", ttoName: "Caltech Office of Technology Transfer", website: "https://techtransfer.caltech.edu", specialties: ["Drug Delivery", "Bioelectronics", "Gene Editing"] , noPublicPortal: true },
  { slug: "asu", name: "Arizona State University", city: "Tempe, AZ", ttoName: "ASU Skysong Innovations", website: "https://skysonginnovations.com", specialties: ["Drug Discovery", "Diagnostics", "Biomaterials"] },
  { slug: "uillinois", name: "University of Illinois", city: "Urbana-Champaign, IL", ttoName: "UI Office of Technology Management", website: "https://otm.illinois.edu", specialties: ["Drug Delivery", "Bioelectronics", "Genomics"] },

  // ── Europe ────────────────────────────────────────────────────────────────
  // UK
  { slug: "oxford", name: "University of Oxford", city: "Oxford, UK", ttoName: "Oxford University Innovation", website: "https://innovation.ox.ac.uk", specialties: ["Drug Discovery", "Vaccines", "Oncology"], continent: "Europe" , noPublicPortal: true },
  { slug: "cambridge", name: "University of Cambridge", city: "Cambridge, UK", ttoName: "Cambridge Enterprise", website: "https://www.enterprise.cam.ac.uk", specialties: ["Drug Discovery", "Genomics", "Oncology"], continent: "Europe" },
  { slug: "imperial", name: "Imperial College London", city: "London, UK", ttoName: "Imperial College Enterprise", website: "https://www.imperial.ac.uk/enterprise", specialties: ["Drug Delivery", "Immunology", "Bioelectronics"], continent: "Europe" , noPublicPortal: true },
  { slug: "ucl", name: "University College London", city: "London, UK", ttoName: "UCL Business", website: "https://www.uclb.com", specialties: ["Gene Therapy", "Oncology", "Neuroscience"], continent: "Europe" , noPublicPortal: true },
  { slug: "manchester", name: "University of Manchester", city: "Manchester, UK", ttoName: "Manchester Innovation Factory", website: "https://www.uominnovationfactory.com", specialties: ["Drug Discovery", "Oncology", "Biomaterials"], continent: "Europe" },
  { slug: "edinburgh", name: "University of Edinburgh", city: "Edinburgh, UK", ttoName: "Edinburgh Commercialisation Service", website: "https://www.ed.ac.uk/research/innovation", specialties: ["Drug Discovery", "Gene Therapy", "Rare Disease"], continent: "Europe" , noPublicPortal: true },
  { slug: "bristol", name: "University of Bristol", city: "Bristol, UK", ttoName: "Bristol Research & Enterprise Development", website: "https://www.bristol.ac.uk/red", specialties: ["Drug Discovery", "Neuroscience", "Oncology"], continent: "Europe" , noPublicPortal: true },
  { slug: "glasgow", name: "University of Glasgow", city: "Glasgow, UK", ttoName: "Glasgow Technology Transfer Office", website: "https://www.gla.ac.uk/research/enterprise", specialties: ["Drug Discovery", "Infectious Disease", "Diagnostics"], continent: "Europe" , noPublicPortal: true },
  { slug: "birmingham", name: "University of Birmingham", city: "Birmingham, UK", ttoName: "Birmingham Enterprise", website: "https://www.birmingham.ac.uk/business/university-enterprise", specialties: ["Drug Discovery", "Oncology", "Immunology"], continent: "Europe" , noPublicPortal: true },
  { slug: "nottingham", name: "University of Nottingham", city: "Nottingham, UK", ttoName: "Nottingham Research & Innovation", website: "https://www.nottingham.ac.uk/research/innovation", specialties: ["Drug Delivery", "Drug Discovery", "Biomaterials"], continent: "Europe" , noPublicPortal: true },
  { slug: "leeds", name: "University of Leeds", city: "Leeds, UK", ttoName: "Leeds Commercialisation Team", website: "https://business.leeds.ac.uk/research-innovation", specialties: ["Drug Delivery", "Biomaterials", "Oncology"], continent: "Europe" },
  { slug: "sheffield", name: "University of Sheffield", city: "Sheffield, UK", ttoName: "Sheffield Commercialisation Office", website: "https://www.sheffield.ac.uk/commercialisation", specialties: ["Drug Delivery", "Biomaterials", "Gene Therapy"], continent: "Europe" , noPublicPortal: true },
  { slug: "southampton", name: "University of Southampton", city: "Southampton, UK", ttoName: "Southampton Research & Innovation", website: "https://www.southampton.ac.uk/research-innovation", specialties: ["Drug Delivery", "Bioelectronics", "Oncology"], continent: "Europe" },
  { slug: "warwick", name: "University of Warwick", city: "Coventry, UK", ttoName: "Warwick Innovation Group", website: "https://warwick.ac.uk/services/innovations", specialties: ["Drug Discovery", "Diagnostics", "Biomaterials"], continent: "Europe" , noPublicPortal: true },
  { slug: "kcl", name: "King's College London", city: "London, UK", ttoName: "King's College London Commercialisation Institute", website: "https://www.kcl.ac.uk/research/commercialisation", specialties: ["Drug Discovery", "Oncology", "Neuroscience"], continent: "Europe" },
  { slug: "liverpool", name: "University of Liverpool", city: "Liverpool, UK", ttoName: "Liverpool Technology Transfer", website: "https://www.liverpool.ac.uk/research/research-partnerships/technology-transfer", specialties: ["Drug Discovery", "Infectious Disease", "Oncology"], continent: "Europe" },
  { slug: "durhamuni", name: "Durham University", city: "Durham, UK", ttoName: "Durham Research & Innovation", website: "https://www.dur.ac.uk/research/innovation", specialties: ["Drug Discovery", "Oncology", "Biomaterials"], continent: "Europe" },
  // Switzerland
  { slug: "ethzurich", name: "ETH Zurich", city: "Zurich, Switzerland", ttoName: "ETH Zurich Technology Transfer", website: "https://transfer.ethz.ch", specialties: ["Drug Delivery", "Bioelectronics", "Gene Editing"], continent: "Europe" },
  { slug: "epfl", name: "EPFL", city: "Lausanne, Switzerland", ttoName: "EPFL Technology Transfer Office", website: "https://tto.epfl.ch", specialties: ["Drug Delivery", "Bioelectronics", "Oncology"], continent: "Europe" , noPublicPortal: true },
  { slug: "ubasel", name: "University of Basel", city: "Basel, Switzerland", ttoName: "Basel Technology Transfer", website: "https://www.unibas.ch/en/Research/Technology-Transfer.html", specialties: ["Drug Discovery", "Oncology", "Rare Disease"], continent: "Europe" , noPublicPortal: true },
  { slug: "ulausanne", name: "University of Lausanne", city: "Lausanne, Switzerland", ttoName: "UNIL Innovation & Partnerships", website: "https://www.unil.ch/innovation", specialties: ["Oncology", "Immunology", "Neuroscience"], continent: "Europe" , noPublicPortal: true },
  { slug: "ugeneva", name: "University of Geneva", city: "Geneva, Switzerland", ttoName: "Geneva Technology Transfer", website: "https://www.unige.ch/research/innovation", specialties: ["Drug Discovery", "Infectious Disease", "Oncology"], continent: "Europe" , noPublicPortal: true },
  { slug: "uzurich", name: "University of Zurich", city: "Zurich, Switzerland", ttoName: "UZH Technology Transfer", website: "https://www.uzh.ch/en/research/technologytransfer.html", specialties: ["Oncology", "Neuroscience", "Drug Discovery"], continent: "Europe" , noPublicPortal: true },
  // Benelux
  { slug: "kuleuven", name: "KU Leuven", city: "Leuven, Belgium", ttoName: "KU Leuven Research & Development", website: "https://lrd.kuleuven.be", specialties: ["Drug Discovery", "Oncology", "Immunology"], continent: "Europe" , noPublicPortal: true },
  { slug: "ugent", name: "Ghent University", city: "Ghent, Belgium", ttoName: "Ghent University TechTransfer", website: "https://www.ugent.be/techtransfer", specialties: ["Drug Discovery", "Oncology", "Agricultural Biotech"], continent: "Europe" , noPublicPortal: true },
  { slug: "groningen", name: "University of Groningen", city: "Groningen, Netherlands", ttoName: "Groningen Knowledge Transfer", website: "https://www.rug.nl/research/innovation", specialties: ["Drug Discovery", "Metabolic Disease", "Oncology"], continent: "Europe" , noPublicPortal: true },
  { slug: "uamsterdam", name: "University of Amsterdam", city: "Amsterdam, Netherlands", ttoName: "Amsterdam Innovation Exchange", website: "https://www.ixamsterdam.nl", specialties: ["Drug Discovery", "Oncology", "Immunology"], continent: "Europe" , noPublicPortal: true },
  { slug: "vuamsterdam", name: "Vrije Universiteit Amsterdam", city: "Amsterdam, Netherlands", ttoName: "VU Knowledge Transfer", website: "https://vu.nl/en/research/knowledge-transfer", specialties: ["Drug Discovery", "Neuroscience", "Oncology"], continent: "Europe" , noPublicPortal: true },
  { slug: "leiden", name: "Leiden University", city: "Leiden, Netherlands", ttoName: "Leiden Knowledge Transfer Office", website: "https://www.universiteitleiden.nl/en/research/knowledge-transfer", specialties: ["Drug Discovery", "Oncology", "Infectious Disease"], continent: "Europe" , noPublicPortal: true },
  // Nordic
  { slug: "karolinska", name: "Karolinska Institutet", city: "Stockholm, Sweden", ttoName: "Karolinska Innovations", website: "https://ki.se/en/innovation", specialties: ["Oncology", "Neuroscience", "Drug Discovery"], continent: "Europe" , noPublicPortal: true },
  { slug: "inven2", name: "University of Oslo", city: "Oslo, Norway", ttoName: "Inven2 Technology Transfer", website: "https://inven2.com", specialties: ["Drug Discovery", "Oncology", "Rare Disease"], continent: "Europe" , noPublicPortal: true },
  { slug: "vis", name: "University of Bergen", city: "Bergen, Norway", ttoName: "VIS Innovation", website: "https://visinnovasjon.no", specialties: ["Drug Discovery", "Marine Biotech", "Infectious Disease"], continent: "Europe" , noPublicPortal: true },
  { slug: "ntnu", name: "NTNU", city: "Trondheim, Norway", ttoName: "NTNU Technology Transfer", website: "https://ntnu.edu/tto", specialties: ["Bioelectronics", "Drug Delivery", "Biomaterials"], continent: "Europe" , noPublicPortal: true },
  { slug: "ucph", name: "University of Copenhagen", city: "Copenhagen, Denmark", ttoName: "Copenhagen Tech Transfer", website: "https://techtransfer.ku.dk", specialties: ["Drug Discovery", "Oncology", "Rare Disease"], continent: "Europe" , noPublicPortal: true },
  { slug: "aarhus", name: "Aarhus University", city: "Aarhus, Denmark", ttoName: "Aarhus Technology Transfer", website: "https://techtransfer.au.dk", specialties: ["Drug Discovery", "Agricultural Biotech", "Oncology"], continent: "Europe" , noPublicPortal: true },
  { slug: "dtu", name: "Technical University of Denmark", city: "Kongens Lyngby, Denmark", ttoName: "DTU Technology Transfer", website: "https://techtransfer.dtu.dk", specialties: ["Bioelectronics", "Drug Delivery", "Diagnostics"], continent: "Europe" , noPublicPortal: true },
  { slug: "lund", name: "Lund University", city: "Lund, Sweden", ttoName: "Lund Innovation Office", website: "https://www.lunduniversity.lu.se/research/innovation", specialties: ["Drug Discovery", "Oncology", "Neuroscience"], continent: "Europe" , noPublicPortal: true },
  { slug: "chalmers", name: "Chalmers University of Technology", city: "Gothenburg, Sweden", ttoName: "Chalmers Ventures", website: "https://chalmersventures.com", specialties: ["Drug Delivery", "Bioelectronics", "Biosensors"], continent: "Europe" , noPublicPortal: true },
  { slug: "gothenburg", name: "University of Gothenburg", city: "Gothenburg, Sweden", ttoName: "Gothenburg Innovation Office", website: "https://www.gu.se/en/innovation", specialties: ["Drug Discovery", "Oncology", "Marine Biotech"], continent: "Europe" , noPublicPortal: true },
  { slug: "helsinki", name: "University of Helsinki", city: "Helsinki, Finland", ttoName: "Helsinki Innovation Services", website: "https://www.helsinki.fi/en/research/services-for-researchers/innovation-services", specialties: ["Drug Discovery", "Oncology", "Infectious Disease"], continent: "Europe" },
  { slug: "aalto", name: "Aalto University", city: "Espoo, Finland", ttoName: "Aalto Innovation Services", website: "https://www.aalto.fi/en/services/innovation-services", specialties: ["Bioelectronics", "Drug Delivery", "Diagnostics"], continent: "Europe" },
  { slug: "tampere", name: "Tampere University", city: "Tampere, Finland", ttoName: "Tampere Innovation Services", website: "https://www.tuni.fi/en/research/innovation-services", specialties: ["Drug Discovery", "Bioelectronics", "Diagnostics"], continent: "Europe" },
  // Germany
  { slug: "tum", name: "Technical University of Munich", city: "Munich, Germany", ttoName: "TUM ForTe Technology Transfer", website: "https://www.forte.tum.de", specialties: ["Drug Delivery", "Bioelectronics", "Oncology"], continent: "Europe" , noPublicPortal: true },
  { slug: "lmu", name: "Ludwig Maximilian University of Munich", city: "Munich, Germany", ttoName: "LMU Munich Innovation Office", website: "https://www.en.uni-muenchen.de/research/innovation", specialties: ["Drug Discovery", "Oncology", "Neuroscience"], continent: "Europe" },
  { slug: "rwth", name: "RWTH Aachen University", city: "Aachen, Germany", ttoName: "RWTH Aachen Innovation", website: "https://www.innovation.rwth-aachen.de", specialties: ["Bioelectronics", "Drug Delivery", "Biomaterials"], continent: "Europe" },
  { slug: "ufreiburg", name: "University of Freiburg", city: "Freiburg, Germany", ttoName: "Freiburg Innovation Office", website: "https://www.uni-freiburg.de/research/innovation", specialties: ["Neuroscience", "Drug Discovery", "Oncology"], continent: "Europe" , noPublicPortal: true },
  { slug: "ubonn", name: "University of Bonn", city: "Bonn, Germany", ttoName: "Bonn Technology Transfer", website: "https://www.uni-bonn.de/en/research/transfer", specialties: ["Drug Discovery", "Oncology", "Rare Disease"], continent: "Europe" , noPublicPortal: true },
  { slug: "ucologne", name: "University of Cologne", city: "Cologne, Germany", ttoName: "Cologne Innovation Office", website: "https://innovation.uni-koeln.de", specialties: ["Drug Discovery", "Oncology", "Metabolic Disease"], continent: "Europe" , noPublicPortal: true },
  { slug: "utubingen", name: "University of Tübingen", city: "Tübingen, Germany", ttoName: "Tübingen Technology Transfer", website: "https://uni-tuebingen.de/en/research/transfer", specialties: ["Drug Discovery", "Neuroscience", "Oncology"], continent: "Europe" , noPublicPortal: true },
  { slug: "heidelberg", name: "University of Heidelberg", city: "Heidelberg, Germany", ttoName: "Heidelberg Technology Transfer", website: "https://www.uni-heidelberg.de/en/research/transfer", specialties: ["Drug Discovery", "Oncology", "Rare Disease"], continent: "Europe" , noPublicPortal: true },
  // Israel
  { slug: "weizmann", name: "Weizmann Institute of Science", city: "Rehovot, Israel", ttoName: "Yeda Research and Development", website: "https://yeda.weizmann.ac.il", specialties: ["Drug Discovery", "Oncology", "Immunology"], continent: "Europe" , noPublicPortal: true },
  { slug: "technion", name: "Technion – Israel Institute of Technology", city: "Haifa, Israel", ttoName: "Technion T3 Technology Transfer", website: "https://t3.technion.ac.il", specialties: ["Drug Delivery", "Bioelectronics", "Diagnostics"], continent: "Europe" , noPublicPortal: true },
  // Canada
  { slug: "tcd", name: "Trinity College Dublin", city: "Dublin, Ireland", ttoName: "Trinity Research & Innovation", website: "https://www.tcd.ie/research/innovation", specialties: ["Drug Discovery", "Immunology", "Neuroscience"], continent: "Europe" },
  { slug: "ulb", name: "Université Libre de Bruxelles", city: "Brussels, Belgium", ttoName: "ULB Technology Transfer", website: "https://www.ulb.be/en/research/technology-transfer", specialties: ["Drug Discovery", "Oncology", "Immunology"], continent: "Europe" },
  { slug: "utoronto", name: "University of Toronto", city: "Toronto, Canada", ttoName: "U of T Innovations & Partnerships", website: "https://research.utoronto.ca/partnerships-commercialization", specialties: ["Gene Therapy", "Oncology", "Drug Delivery"], continent: "North America" },
  { slug: "western", name: "Western University", city: "London, Canada", ttoName: "WORLDiscoveries", website: "https://www.worldiscoveries.ca", specialties: ["Drug Discovery", "Oncology", "Neuroscience"], continent: "North America" },
  { slug: "queensu", name: "Queen's University", city: "Kingston, Canada", ttoName: "PARTEQ Innovations", website: "https://www.queensu.ca/partnershipsandinnovation", specialties: ["Drug Discovery", "Oncology", "Biomaterials"], continent: "North America" },
  { slug: "ualberta", name: "University of Alberta", city: "Edmonton, Canada", ttoName: "TEC Edmonton", website: "https://www.tecedmonton.com", specialties: ["Drug Discovery", "Oncology", "Drug Delivery"], continent: "North America" },
  { slug: "mcgill", name: "McGill University", city: "Montreal, Canada", ttoName: "McGill Innovation + Partnerships", website: "https://www.mcgill.ca/research/researchers/commercialization", specialties: ["Oncology", "Neuroscience", "Drug Discovery"], continent: "North America"  },
  { slug: "ubc", name: "University of British Columbia", city: "Vancouver, Canada", ttoName: "UBC UILO", website: "https://uilo.ubc.ca", specialties: ["Drug Delivery", "Oncology", "Immunology"], continent: "North America"  },
  { slug: "ucalgary", name: "University of Calgary", city: "Calgary, Canada", ttoName: "Calgary Research & Innovation", website: "https://research.ucalgary.ca", specialties: ["Drug Discovery", "Oncology", "Cardiovascular"], continent: "North America"  },
  { slug: "usask", name: "University of Saskatchewan", city: "Saskatoon, Canada", ttoName: "USask Innovation Enterprise", website: "https://research.usask.ca/innovation", specialties: ["Agricultural Biotech", "Drug Discovery", "Vaccines"], continent: "North America" },
  { slug: "umanitoba", name: "University of Manitoba", city: "Winnipeg, Canada", ttoName: "Manitoba Technology Transfer", website: "https://umanitoba.ca/research/innovation", specialties: ["Drug Discovery", "Infectious Disease", "Agricultural Biotech"], continent: "North America" , noPublicPortal: true },
  { slug: "uvic", name: "University of Victoria", city: "Victoria, Canada", ttoName: "UVic Industry Partnerships", website: "https://www.uvic.ca/research/innovation", specialties: ["Drug Discovery", "Biosensors", "Drug Delivery"], continent: "North America"  },
  { slug: "sfu", name: "Simon Fraser University", city: "Burnaby, Canada", ttoName: "SFU Industry Liaison Office", website: "https://www.sfu.ca/ilo.html", specialties: ["Drug Delivery", "Bioelectronics", "Oncology"], continent: "North America" , noPublicPortal: true },

  // ── Asia-Pacific ──────────────────────────────────────────────────────────
  { slug: "umelbourne", name: "University of Melbourne", city: "Melbourne, Australia", ttoName: "Melbourne Research Innovation", website: "https://research.unimelb.edu.au", specialties: ["Drug Discovery", "Oncology", "Rare Disease"], continent: "Asia-Pacific" , noPublicPortal: true },
  { slug: "monash", name: "Monash University", city: "Melbourne, Australia", ttoName: "Monash University Commercialisation", website: "https://commercialisation.monash.edu", specialties: ["Drug Delivery", "Oncology", "Infectious Disease"], continent: "Asia-Pacific"  },
  { slug: "usydney", name: "University of Sydney", city: "Sydney, Australia", ttoName: "Sydney Commercial Development", website: "https://www.sydney.edu.au/research/industry-and-community/commercialisation.html", specialties: ["Drug Discovery", "Oncology", "Biomaterials"], continent: "Asia-Pacific" , noPublicPortal: true },
  { slug: "uniquest", name: "University of Queensland", city: "Brisbane, Australia", ttoName: "UniQuest", website: "https://uniquest.com.au", specialties: ["Drug Discovery", "Vaccines", "Oncology"], continent: "Asia-Pacific" , noPublicPortal: true },
  { slug: "nus", name: "National University of Singapore", city: "Singapore", ttoName: "NUS Industry Liaison Office", website: "https://ilo.nus.edu.sg", specialties: ["Drug Delivery", "Diagnostics", "Oncology"], continent: "Asia-Pacific"  },
  { slug: "hkust", name: "Hong Kong University of Science and Technology", city: "Hong Kong", ttoName: "HKUST Knowledge Transfer Office", website: "https://kto.hkust.edu.hk", specialties: ["Drug Delivery", "Bioelectronics", "Diagnostics"], continent: "Asia-Pacific" , noPublicPortal: true },
  { slug: "hku", name: "University of Hong Kong", city: "Hong Kong", ttoName: "HKU Technology Transfer Office", website: "https://tto.hku.hk", specialties: ["Drug Discovery", "Oncology", "Infectious Disease"], continent: "Asia-Pacific" , noPublicPortal: true },
  { slug: "griffith", name: "Griffith University", city: "Brisbane, Australia", ttoName: "Griffith Enterprise", website: "https://www.griffith.edu.au/research/enterprise", specialties: ["Drug Discovery", "Oncology", "Infectious Disease"], continent: "Asia-Pacific" },
  { slug: "ntu", name: "Nottingham Trent University", city: "Nottingham, UK", ttoName: "NTU Research & Innovation", website: "https://www.ntu.ac.uk/research/research-innovation", specialties: ["Drug Discovery", "Biomaterials", "Diagnostics"], continent: "Europe" },
  { slug: "uhaw", name: "University of Hawaii", city: "Honolulu, HI", ttoName: "UH Office of Innovation and Commercialization", website: "https://www.otti.hawaii.edu", specialties: ["Drug Discovery", "Marine Biotech", "Infectious Disease"] },

  // ── Hospital & Medical Research Centers ──────────────────────────────────
  { slug: "mgh", name: "Massachusetts General Hospital", city: "Boston, MA", ttoName: "MGH Technology Ventures", website: "https://mghtv.partners.org", specialties: ["Oncology", "Neuroscience", "Rare Disease"], noPublicPortal: true },
  { slug: "brigham-womens", name: "Brigham and Women's Hospital", city: "Boston, MA", ttoName: "BWH Technology Development", website: "https://www.brighamandwomens.org/research/technology", specialties: ["Cardiovascular", "Oncology", "Immunology"], noPublicPortal: true },
  { slug: "mskcc", name: "Memorial Sloan Kettering Cancer Center", city: "New York, NY", ttoName: "MSK Technology Development", website: "https://www.mskcc.org/research/technology-development", specialties: ["Oncology", "Immunotherapy", "CAR-T"], noPublicPortal: true },
  { slug: "chop", name: "Children's Hospital of Philadelphia", city: "Philadelphia, PA", ttoName: "CHOP Technology Transfer", website: "https://www.chop.edu/research/technology-transfer", specialties: ["Rare Disease", "Gene Therapy", "Pediatric Oncology"], noPublicPortal: true },
  { slug: "cchmc", name: "Cincinnati Children's Hospital Medical Center", city: "Cincinnati, OH", ttoName: "Cincinnati Children's Technology Transfer", website: "https://www.cincinnatichildrens.org/research/technology-transfer", specialties: ["Rare Disease", "Gene Therapy", "Pediatric Medicine"], noPublicPortal: true },
  { slug: "cleveland-clinic", name: "Cleveland Clinic", city: "Cleveland, OH", ttoName: "Cleveland Clinic Innovations", website: "https://innovations.clevelandclinic.org", specialties: ["Cardiovascular", "Oncology", "Neuroscience"] },
  { slug: "cedars-sinai", name: "Cedars-Sinai Medical Center", city: "Los Angeles, CA", ttoName: "Cedars-Sinai Technology Transfer", website: "https://www.cedars-sinai.org/research/technology-transfer.html", specialties: ["Oncology", "Cardiovascular", "Neuroscience"], noPublicPortal: true },
  { slug: "houston-methodist", name: "Houston Methodist", city: "Houston, TX", ttoName: "Houston Methodist Research Institute TTO", website: "https://www.houstonmethodist.org/research/technology-commercialization", specialties: ["Cardiovascular", "Oncology", "Drug Delivery"], noPublicPortal: true },
  { slug: "moffitt", name: "Moffitt Cancer Center", city: "Tampa, FL", ttoName: "Moffitt Oncology Research Innovation", website: "https://moffitt.org/research-science/technology-transfer", specialties: ["Oncology", "Immunotherapy", "CAR-T"], noPublicPortal: true },
  { slug: "nationwide-childrens", name: "Nationwide Children's Hospital", city: "Columbus, OH", ttoName: "Nationwide Children's Technology Development", website: "https://www.nationwidechildrens.org/research/technology", specialties: ["Rare Disease", "Gene Therapy", "Pediatric Medicine"], noPublicPortal: true },
  { slug: "fred-hutch", name: "Fred Hutchinson Cancer Center", city: "Seattle, WA", ttoName: "Fred Hutch Technology Transfer", website: "https://www.fredhutch.org/en/research/technology-transfer.html", specialties: ["Oncology", "Immunotherapy", "Gene Therapy"], noPublicPortal: true },
  { slug: "jax", name: "The Jackson Laboratory", city: "Bar Harbor, ME", ttoName: "JAX Technology Transfer", website: "https://www.jax.org/research-and-faculty/research-labs/technology-commercialization", specialties: ["Genomics", "Rare Disease", "Oncology"] },

  // ── Additional US Universities ────────────────────────────────────────────
  { slug: "nyu", name: "New York University", city: "New York, NY", ttoName: "NYU Technology Opportunities & Ventures", website: "https://www.nyu.edu/research/tov.html", specialties: ["Neuroscience", "Oncology", "Drug Discovery"] },
  { slug: "weill-cornell", name: "Weill Cornell Medicine", city: "New York, NY", ttoName: "Weill Cornell Technology Transfer", website: "https://weillcornell.org/research/technology-transfer", specialties: ["Oncology", "Neuroscience", "Gene Therapy"], noPublicPortal: true },
  { slug: "baylor-med", name: "Baylor College of Medicine", city: "Houston, TX", ttoName: "Baylor College of Medicine TTO", website: "https://www.bcm.edu/research/technology-commercialization", specialties: ["Gene Therapy", "Oncology", "Infectious Disease"] },
  { slug: "ucsd", name: "UC San Diego", city: "La Jolla, CA", ttoName: "UC San Diego Technology Transfer", website: "https://ucsd.technologypublisher.com", specialties: ["Drug Discovery", "Oncology", "Neuroscience"] },
  { slug: "ucsb", name: "UC Santa Barbara", city: "Santa Barbara, CA", ttoName: "UCSB Office of Technology & Industry Alliances", website: "https://tia.ucsb.edu", specialties: ["Drug Delivery", "Biomaterials", "Bioelectronics"] },
  { slug: "uci", name: "UC Irvine", city: "Irvine, CA", ttoName: "UCI Applied Innovation", website: "https://uci.technologypublisher.com", specialties: ["Drug Discovery", "Oncology", "Neuroscience"] },
  { slug: "ku", name: "University of Kansas", city: "Lawrence, KS", ttoName: "KU Center for Technology Commercialization", website: "https://ku.technologypublisher.com", specialties: ["Drug Discovery", "Pharmaceutics", "Oncology"] },
  { slug: "nih-ott", name: "NIH Office of Technology Transfer", city: "Bethesda, MD", ttoName: "NIH OTT", website: "https://www.ott.nih.gov", specialties: ["Drug Discovery", "Diagnostics", "Vaccines", "Infectious Disease"] },
];

const NAME_ALIASES: Record<string, string> = {
  "johns hopkins": "jhu",
  "johns hopkins university": "jhu",
  "ucsf": "ucsf",
  "uc san francisco": "ucsf",
  "university of california san francisco": "ucsf",
  "mit": "mit",
  "massachusetts institute of technology": "mit",
  "harvard": "harvard",
  "stanford": "stanford",
  "mayo": "mayo",
  "mayo clinic": "mayo",
  "fred hutch": "fred-hutch",
  "fred hutchinson": "fred-hutch",
  "fred hutchinson cancer center": "fred-hutch",
  "fred hutchinson cancer research center": "fred-hutch",
  "msk": "mskcc",
  "memorial sloan kettering": "mskcc",
  "memorial sloan-kettering": "mskcc",
  "memorial sloan kettering cancer center": "mskcc",
  "chop": "chop",
  "children's hospital of philadelphia": "chop",
  "mgh": "mgh",
  "massachusetts general hospital": "mgh",
  "mass general": "mgh",
  "mass general hospital": "mgh",
  "brigham and women's": "brigham-womens",
  "brigham and womens": "brigham-womens",
  "brigham and women's hospital": "brigham-womens",
  "columbia": "columbia",
  "nih": "nih-ott",
  "nih office of technology transfer": "nih-ott",
  "national institutes of health": "nih-ott",
  "northwestern": "northwestern",
  "northwestern university": "northwestern",
  "uc berkeley": "ucberkeley",
  "university of california berkeley": "ucberkeley",
  "uc san diego": "ucsd",
  "university of california san diego": "ucsd",
  "uc santa barbara": "ucsb",
  "university of california santa barbara": "ucsb",
  "uc irvine": "uci",
  "university of california irvine": "uci",
  "uc davis": "ucdavis",
  "university of california davis": "ucdavis",
  "ucla": "ucla",
  "university of california los angeles": "ucla",
  "nyu": "nyu",
  "new york university": "nyu",
  "baylor college of medicine": "baylor-med",
  "moffitt": "moffitt",
  "moffitt cancer center": "moffitt",
  "cleveland clinic": "cleveland-clinic",
  "cedars-sinai": "cedars-sinai",
  "cedars sinai": "cedars-sinai",
  "cedars-sinai medical center": "cedars-sinai",
  "jackson lab": "jax",
  "jackson laboratory": "jax",
  "the jackson laboratory": "jax",
  "cchmc": "cchmc",
  "cincinnati children's": "cchmc",
  "cincinnati children's hospital": "cchmc",
  "cincinnati childrens hospital medical center": "cchmc",
  "houston methodist": "houston-methodist",
  "nationwide children's": "nationwide-childrens",
  "nationwide childrens hospital": "nationwide-childrens",
};

export function slugifyInstitutionName(name: string): string {
  const lower = name.toLowerCase().trim();
  if (NAME_ALIASES[lower]) return NAME_ALIASES[lower];
  const found = INSTITUTIONS.find((inst) => inst.name.toLowerCase() === lower);
  if (found) return found.slug;
  return lower.replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

export const BLOCKED_SLUGS = new Set([
  "mayo",
  "columbia",
]);
