export type Institution = {
  slug: string;
  name: string;
  city: string;
  ttoName: string;
  website: string;
  specialties: string[];
};

export const INSTITUTIONS: Institution[] = [
  { slug: "stanford", name: "Stanford University", city: "Palo Alto, CA", ttoName: "Stanford OTT", website: "https://ottech.stanford.edu", specialties: ["Oncology", "Neuroscience", "Gene Therapy"] },
  { slug: "mit", name: "MIT", city: "Cambridge, MA", ttoName: "MIT Technology Licensing Office", website: "https://tlo.mit.edu", specialties: ["Bioelectronics", "Drug Delivery", "Immunology"] },
  { slug: "harvard", name: "Harvard University", city: "Boston, MA", ttoName: "Harvard OTD", website: "https://otd.harvard.edu", specialties: ["Oncology", "Gene Editing", "Immunotherapy"] },
  { slug: "jhu", name: "Johns Hopkins University", city: "Baltimore, MD", ttoName: "Johns Hopkins TTO", website: "https://ventures.jhu.edu", specialties: ["Infectious Disease", "Oncology", "Neuroscience"] },
  { slug: "ucsf", name: "University of California San Francisco", city: "San Francisco, CA", ttoName: "UCSF Innovation Ventures", website: "https://inno.ucsf.edu", specialties: ["Oncology", "Rare Disease", "Immunology"] },
  { slug: "duke", name: "Duke University", city: "Durham, NC", ttoName: "Duke OLV", website: "https://olv.duke.edu", specialties: ["Cardiovascular", "Immunotherapy", "mRNA"] },
  { slug: "columbia", name: "Columbia University", city: "New York, NY", ttoName: "Columbia Technology Ventures", website: "https://techventures.columbia.edu", specialties: ["Neuroscience", "Oncology", "Gene Therapy"] },
  { slug: "upenn", name: "University of Pennsylvania", city: "Philadelphia, PA", ttoName: "Penn Center for Innovation", website: "https://pci.upenn.edu", specialties: ["Gene Therapy", "CAR-T", "mRNA"] },
  { slug: "northwestern", name: "Northwestern University", city: "Evanston, IL", ttoName: "Northwestern TTO", website: "https://tto.northwestern.edu", specialties: ["Drug Delivery", "Oncology", "Bioelectronics"] },
  { slug: "cornell", name: "Cornell University", city: "Ithaca, NY", ttoName: "Cornell Center for TT", website: "https://ctt.cornell.edu", specialties: ["Metabolic Disease", "Antimicrobials", "Oncology"] },
  { slug: "ucberkeley", name: "UC Berkeley", city: "Berkeley, CA", ttoName: "UC Berkeley Intellectual Property Office", website: "https://ipira.berkeley.edu", specialties: ["CRISPR", "Synthetic Biology", "Drug Discovery"] },
  { slug: "uwashington", name: "University of Washington", city: "Seattle, WA", ttoName: "UW CoMotion", website: "https://comotion.uw.edu", specialties: ["Neuroscience", "Oncology", "Structural Biology"] },
  { slug: "wustl", name: "Washington University in St. Louis", city: "St. Louis, MO", ttoName: "WashU OTM", website: "https://otm.wustl.edu", specialties: ["Neuroscience", "Metabolic Disease", "Immunology"] },
  { slug: "umich", name: "University of Michigan", city: "Ann Arbor, MI", ttoName: "U-M Tech Transfer", website: "https://umich.flintbox.com", specialties: ["Cardiovascular", "Gene Therapy", "Oncology"] },
  { slug: "gatech", name: "Georgia Institute of Technology", city: "Atlanta, GA", ttoName: "Georgia Tech VentureLab", website: "https://gatech.flintbox.com", specialties: ["Robotics", "Advanced Materials", "Biomedical Engineering"] },
  { slug: "mayo", name: "Mayo Clinic", city: "Rochester, MN", ttoName: "Mayo Clinic Ventures", website: "https://ventures.mayoclinic.org", specialties: ["Diagnostics", "Oncology", "Rare Disease"] },
  { slug: "scripps", name: "Scripps Research", city: "La Jolla, CA", ttoName: "Scripps Research TTVD", website: "https://www.scripps.edu/science-and-medicine/ttvd", specialties: ["Drug Discovery", "Antibody Engineering", "Oncology"] },
  { slug: "salk", name: "Salk Institute", city: "La Jolla, CA", ttoName: "Salk TTO", website: "https://www.salk.edu/partnerships-commercialization", specialties: ["Gene Regulation", "Oncology", "Aging"] },
  { slug: "mdanderson", name: "MD Anderson Cancer Center", city: "Houston, TX", ttoName: "MD Anderson TTO", website: "https://www.mdanderson.org/research/departments-labs-institutes/programs-centers/technology-commercialization.html", specialties: ["Oncology", "Immunotherapy", "CAR-T"] },
  { slug: "upitt", name: "University of Pittsburgh", city: "Pittsburgh, PA", ttoName: "Pitt Innovation Institute", website: "https://www.innovation.pitt.edu", specialties: ["Regenerative Medicine", "Oncology", "Organ Transplant"] },
  { slug: "uchicago", name: "University of Chicago", city: "Chicago, IL", ttoName: "UChicago Polsky Center", website: "https://polsky.uchicago.edu/programs-and-services/george-shultz-innovation-fund", specialties: ["Immunology", "Drug Delivery", "Oncology"] },
  { slug: "vanderbilt", name: "Vanderbilt University", city: "Nashville, TN", ttoName: "Vanderbilt Center for Technology Transfer", website: "https://ctt.vanderbilt.edu", specialties: ["Small Molecules", "Metabolic Disease", "Infectious Disease"] },
  { slug: "emory", name: "Emory University", city: "Atlanta, GA", ttoName: "Emory OTT", website: "https://ott.emory.edu", specialties: ["Infectious Disease", "Neuroscience", "Vaccines"] },
  { slug: "bu", name: "Boston University", city: "Boston, MA", ttoName: "BU Technology Development", website: "https://www.bu.edu/otd", specialties: ["Oncology", "Drug Delivery", "Rare Disease"] },
  { slug: "georgetown", name: "Georgetown University", city: "Washington, DC", ttoName: "Georgetown OTL", website: "https://otl.georgetown.edu", specialties: ["Oncology", "Immunology", "Small Molecules"] },
  { slug: "utexas", name: "University of Texas", city: "Austin, TX", ttoName: "UT Office of Technology Commercialization", website: "https://research.utexas.edu/otc", specialties: ["Oncology", "Gene Therapy", "Bioelectronics"] },
  { slug: "cwru", name: "Case Western Reserve University", city: "Cleveland, OH", ttoName: "CWRU TTO", website: "https://research.case.edu/tto", specialties: ["Orthopedics", "Neuroscience", "Biomaterials"] },
  { slug: "ucolorado", name: "University of Colorado", city: "Aurora, CO", ttoName: "CU Innovations", website: "https://innovations.cu.edu", specialties: ["Oncology", "Respiratory", "Rare Disease"] },
  { slug: "princeton", name: "Princeton University", city: "Princeton, NJ", ttoName: "Princeton OTL", website: "https://puotl.technologypublisher.com", specialties: ["Drug Discovery", "Materials Science", "Neuroscience"] },
  { slug: "ucla", name: "UCLA", city: "Los Angeles, CA", ttoName: "UCLA Technology Development Group", website: "https://ucla.technologypublisher.com", specialties: ["Oncology", "Stem Cells", "Immunotherapy"] },
  { slug: "brown", name: "Brown University", city: "Providence, RI", ttoName: "Brown Technology Innovations", website: "https://brown.technologypublisher.com", specialties: ["Neuroscience", "Drug Delivery", "Biomaterials"] },
  { slug: "rochester", name: "University of Rochester", city: "Rochester, NY", ttoName: "UR Ventures", website: "https://rochester.technologypublisher.com", specialties: ["Oncology", "Optics", "Drug Delivery"] },
  { slug: "tufts", name: "Tufts University", city: "Medford, MA", ttoName: "Tufts Technology Services", website: "https://tufts.technologypublisher.com", specialties: ["Drug Delivery", "Biomaterials", "Infectious Disease"] },
  { slug: "uthealth", name: "UT Health", city: "Houston, TX", ttoName: "UT Health Office of Technology Management", website: "https://uthealth.technologypublisher.com", specialties: ["Oncology", "Cardiovascular", "Diagnostics"] },
  { slug: "coloradostate", name: "Colorado State University", city: "Fort Collins, CO", ttoName: "CSU Ventures", website: "https://csuventures.technologypublisher.com", specialties: ["Infectious Disease", "Drug Delivery", "Agricultural Biotech"] },
  { slug: "virginiatech", name: "Virginia Tech", city: "Blacksburg, VA", ttoName: "Virginia Tech Intellectual Properties", website: "https://vtip.technologypublisher.com", specialties: ["Biosensors", "Drug Delivery", "Oncology"] },
  { slug: "usf", name: "University of South Florida", city: "Tampa, FL", ttoName: "USF Technology Transfer", website: "https://usf.technologypublisher.com", specialties: ["Oncology", "Neuroscience", "Infectious Disease"] },
  { slug: "waynestate", name: "Wayne State University", city: "Detroit, MI", ttoName: "Wayne State Tech Transfer", website: "https://wayne.technologypublisher.com", specialties: ["Oncology", "Drug Discovery", "Rare Disease"] },
  { slug: "utdallas", name: "UT Dallas", city: "Richardson, TX", ttoName: "UT Dallas Technology Commercialization", website: "https://utdallas.technologypublisher.com", specialties: ["Bioelectronics", "Neuroscience", "Drug Delivery"] },
  { slug: "msstate", name: "Mississippi State University", city: "Starkville, MS", ttoName: "MSU Technology Management", website: "https://msstate-innovations.technologypublisher.com", specialties: ["Agricultural Biotech", "Diagnostics", "Biosensors"] },
  { slug: "utoledo", name: "University of Toledo", city: "Toledo, OH", ttoName: "UT Technology Transfer", website: "https://utoledo.technologypublisher.com", specialties: ["Drug Discovery", "Oncology", "Metabolic Disease"] },
  { slug: "njit", name: "New Jersey Institute of Technology", city: "Newark, NJ", ttoName: "NJIT Technology Transfer", website: "https://njit.technologypublisher.com", specialties: ["Biomaterials", "Drug Delivery", "Biosensors"] },
  { slug: "calpoly", name: "Cal Poly San Luis Obispo", city: "San Luis Obispo, CA", ttoName: "Cal Poly Technology Transfer", website: "https://calpoly.technologypublisher.com", specialties: ["Agricultural Biotech", "Biosensors", "Drug Delivery"] },
  { slug: "slu", name: "Saint Louis University", city: "St. Louis, MO", ttoName: "SLU Technology Management", website: "https://slu.technologypublisher.com", specialties: ["Oncology", "Infectious Disease", "Drug Discovery"] },
  { slug: "ucdavis", name: "UC Davis", city: "Davis, CA", ttoName: "UC Davis InnovationAccess", website: "https://ucdavis.technologypublisher.com", specialties: ["Agricultural Biotech", "Oncology", "Regenerative Medicine"] },
  { slug: "utah", name: "University of Utah", city: "Salt Lake City, UT", ttoName: "University of Utah Technology Licensing Office", website: "https://utah.technologypublisher.com", specialties: ["Drug Delivery", "Bioelectronics", "Oncology"] },
  { slug: "uva", name: "University of Virginia", city: "Charlottesville, VA", ttoName: "UVA Licensing & Ventures Group", website: "https://uva.technologypublisher.com", specialties: ["Oncology", "Neuroscience", "Drug Discovery"] },
  { slug: "uoregon", name: "University of Oregon", city: "Eugene, OR", ttoName: "UO Office for Research", website: "https://uoregon.technologypublisher.com", specialties: ["Neuroscience", "Drug Discovery", "Biomaterials"] },
  { slug: "gwu", name: "George Washington University", city: "Washington, DC", ttoName: "GWU Office of Technology Transfer", website: "https://gwu.technologypublisher.com", specialties: ["Oncology", "Infectious Disease", "Diagnostics"] },
  { slug: "czbiohub", name: "CZ Biohub", city: "San Francisco, CA", ttoName: "CZ Biohub Technology Transfer", website: "https://czbiohub.technologypublisher.com", specialties: ["CRISPR", "Diagnostics", "Infectious Disease"] },
  { slug: "musc", name: "Medical University of South Carolina", city: "Charleston, SC", ttoName: "MUSC Foundation for Research Development", website: "https://musc.technologypublisher.com", specialties: ["Oncology", "Cardiovascular", "Rare Disease"] },
  { slug: "southcarolina", name: "University of South Carolina", city: "Columbia, SC", ttoName: "USC Technology Commercialization Office", website: "https://sc.technologypublisher.com", specialties: ["Drug Delivery", "Biomaterials", "Oncology"] },
  { slug: "lehigh", name: "Lehigh University", city: "Bethlehem, PA", ttoName: "Lehigh Office of Technology Transfer", website: "https://lehighott.technologypublisher.com", specialties: ["Biosensors", "Drug Delivery", "Materials Science"] },
  { slug: "clemson", name: "Clemson University", city: "Clemson, SC", ttoName: "Clemson University Research Foundation", website: "https://curf.technologypublisher.com", specialties: ["Biomaterials", "Agricultural Biotech", "Drug Delivery"] },
  { slug: "iowastate", name: "Iowa State University", city: "Ames, IA", ttoName: "Iowa State University Research Foundation", website: "https://isurftech.technologypublisher.com", specialties: ["Agricultural Biotech", "Drug Delivery", "Biosensors"] },
  { slug: "tgen", name: "Translational Genomics Research Institute", city: "Phoenix, AZ", ttoName: "TGen Technology Transfer", website: "https://tgen.technologypublisher.com", specialties: ["Genomics", "Oncology", "Rare Disease"] },
  { slug: "wsu", name: "Washington State University", city: "Pullman, WA", ttoName: "WSU Office of Commercialization", website: "https://wsu.technologypublisher.com", specialties: ["Agricultural Biotech", "Drug Delivery", "Biosensors"] },
  { slug: "arizona", name: "University of Arizona", city: "Tucson, AZ", ttoName: "Tech Launch Arizona", website: "https://arizona.technologypublisher.com", specialties: ["Oncology", "Drug Discovery", "Optics"] },
  { slug: "pennstate", name: "Penn State University", city: "University Park, PA", ttoName: "Penn State Office of TT", website: "https://pennstate.technologypublisher.com", specialties: ["Biomaterials", "Drug Delivery", "Biosensors"] },
  { slug: "rutgers", name: "Rutgers University", city: "New Brunswick, NJ", ttoName: "Rutgers Office of Research Commercialization", website: "https://rutgers.technologypublisher.com", specialties: ["Drug Discovery", "Oncology", "Infectious Disease"] },
  { slug: "stevens", name: "Stevens Institute of Technology", city: "Hoboken, NJ", ttoName: "Stevens TTO", website: "https://stevens.technologypublisher.com", specialties: ["Bioelectronics", "Biosensors", "Drug Delivery"] },
  { slug: "rpi", name: "Rensselaer Polytechnic Institute", city: "Troy, NY", ttoName: "RPI Office of TT", website: "https://rpi.technologypublisher.com", specialties: ["Biomaterials", "Drug Delivery", "Bioelectronics"] },
  { slug: "stonybrook", name: "Stony Brook University", city: "Stony Brook, NY", ttoName: "Stony Brook TTO", website: "https://stonybrook.technologypublisher.com", specialties: ["Oncology", "Drug Discovery", "Neuroscience"] },
  { slug: "cincinnati", name: "University of Cincinnati", city: "Cincinnati, OH", ttoName: "UC Office of Technology Transfer", website: "https://uc.technologypublisher.com", specialties: ["Oncology", "Drug Delivery", "Cardiovascular"] },
  { slug: "buffalo", name: "University at Buffalo", city: "Buffalo, NY", ttoName: "UB Technology Transfer", website: "https://buffalo.technologypublisher.com", specialties: ["Oncology", "Drug Discovery", "Neuroscience"] },
  { slug: "rowan", name: "Rowan University", city: "Glassboro, NJ", ttoName: "Rowan Innovation Ventures", website: "https://rowan.technologypublisher.com", specialties: ["Biomaterials", "Drug Delivery", "Diagnostics"] },
  { slug: "georgemason", name: "George Mason University", city: "Fairfax, VA", ttoName: "Mason Enterprise Center", website: "https://mason.technologypublisher.com", specialties: ["Biosensors", "Drug Delivery", "Bioelectronics"] },
  { slug: "umaine", name: "University of Maine", city: "Orono, ME", ttoName: "UMaine Office of Innovation", website: "https://umaine.technologypublisher.com", specialties: ["Biomaterials", "Agricultural Biotech", "Drug Delivery"] },
  { slug: "binghamton", name: "Binghamton University", city: "Binghamton, NY", ttoName: "Binghamton TTO", website: "https://binghamton.technologypublisher.com", specialties: ["Oncology", "Drug Discovery", "Biosensors"] },
  { slug: "usc", name: "University of Southern California", city: "Los Angeles, CA", ttoName: "USC Stevens Center for Innovation", website: "https://usc.technologypublisher.com", specialties: ["Neuroscience", "Drug Delivery", "Oncology"] },
  { slug: "oregonstate", name: "Oregon State University", city: "Corvallis, OR", ttoName: "OSU Office for Commercialization", website: "https://oregonstate.technologypublisher.com", specialties: ["Agricultural Biotech", "Drug Discovery", "Biomaterials"] },
  { slug: "gsu", name: "Georgia State University", city: "Atlanta, GA", ttoName: "GSU Office of Technology Transfer", website: "https://gsu.technologypublisher.com", specialties: ["Drug Discovery", "Oncology", "Infectious Disease"] },
  { slug: "northeastern", name: "Northeastern University", city: "Boston, MA", ttoName: "Northeastern TTO", website: "https://nu.technologypublisher.com", specialties: ["Drug Delivery", "Biosensors", "Bioelectronics"] },
  { slug: "uvm", name: "University of Vermont", city: "Burlington, VT", ttoName: "UVM Office of Technology Commercialization", website: "https://uvm.technologypublisher.com", specialties: ["Metabolic Disease", "Oncology", "Drug Discovery"] },
  { slug: "usd", name: "University of South Dakota", city: "Vermillion, SD", ttoName: "USD Office of Research", website: "https://usd.technologypublisher.com", specialties: ["Drug Discovery", "Diagnostics", "Rare Disease"] },
  { slug: "txstate", name: "Texas State University", city: "San Marcos, TX", ttoName: "Texas State TTO", website: "https://txstate.technologypublisher.com", specialties: ["Drug Delivery", "Biosensors", "Materials Science"] },
  { slug: "yale", name: "Yale University", city: "New Haven, CT", ttoName: "Yale OCS", website: "https://ventures.yale.edu/yale-technologies", specialties: ["Oncology", "Immunotherapy", "Structural Biology"] },
  { slug: "purdue", name: "Purdue University", city: "West Lafayette, IN", ttoName: "Purdue Research Foundation OTC", website: "https://licensing.prf.org/products", specialties: ["Drug Delivery", "Bioelectronics", "Agricultural Biotech"] },
  { slug: "umn", name: "University of Minnesota", city: "Minneapolis, MN", ttoName: "University of Minnesota Technology Commercialization", website: "https://license.umn.edu/products", specialties: ["Oncology", "Neuroscience", "Gene Therapy"] },
  { slug: "miami", name: "University of Miami", city: "Miami, FL", ttoName: "UM Office of Technology Transfer", website: "https://miami.technologypublisher.com", specialties: ["Oncology", "Immunology", "Drug Discovery"] },
  { slug: "upstate", name: "SUNY Upstate Medical University", city: "Syracuse, NY", ttoName: "Upstate Medical TTO", website: "https://upstate.technologypublisher.com", specialties: ["Oncology", "Rare Disease", "Diagnostics"] },
  { slug: "suny", name: "SUNY System", city: "Albany, NY", ttoName: "SUNY Research Foundation", website: "https://suny.technologypublisher.com", specialties: ["Drug Discovery", "Biosensors", "Biomaterials"] },
  { slug: "alabama", name: "University of Alabama", city: "Tuscaloosa, AL", ttoName: "UA Office of Technology Transfer", website: "https://ua.technologypublisher.com", specialties: ["Drug Delivery", "Oncology", "Materials Science"] },
  { slug: "wyoming", name: "University of Wyoming", city: "Laramie, WY", ttoName: "UW Technology Transfer", website: "https://uwyo.technologypublisher.com", specialties: ["Agricultural Biotech", "Drug Discovery", "Energy"] },
  { slug: "idaho", name: "University of Idaho", city: "Moscow, ID", ttoName: "UI Office of Technology Transfer", website: "https://uidaho.technologypublisher.com", specialties: ["Agricultural Biotech", "Drug Discovery", "Biosensors"] },
];

export const BLOCKED_SLUGS = new Set([
  "ucsf", "duke", "mayo", "ucolorado", "columbia",
]);
