import type { RawSignal } from "../../types";

const BAYLOR_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "CMV-Specific T Cell Therapy for Immune-Compromised Transplant Recipients",
    text: "Baylor's Center for Cell and Gene Therapy has manufactured CMV-specific T cells (VSTs) from third-party donors using GMP-grade protocols, creating a banked, off-the-shelf T cell product for cytomegalovirus disease in hematopoietic stem cell transplant recipients. Phase 2 data from 52 patients show 73% complete CMV viremia clearance after a single infusion, with no graft-versus-host disease. IP covers the manufacturing process, the donor selection algorithm, and the infusion protocol.",
    authors_or_owner: "Baylor College of Medicine Office of Research",
    institution_or_sponsor: "Baylor College of Medicine",
    date: "2024-08-15",
    stage_hint: "phase 2",
    url: "https://www.bcm.edu/research/office-of-research/technology-transfer",
    metadata: { licensing_status: "available", contact_office: "BCM Technology Transfer", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "HER2-CAR T Cell with Switch Receptor for Solid Tumor Therapy",
    text: "A HER2-targeted CAR T cell engineered with a TGF-β 'switch receptor' that converts immunosuppressive TGF-β signals in the tumor microenvironment into activating IL-4/IL-2 signals, enhancing T cell persistence in solid tumors. Phase 1 data from 20 HER2+ solid tumor patients (osteosarcoma, medulloblastoma) show objective responses in 8/20 patients, including 2 complete responses in patients with recurrent pediatric osteosarcoma. IP covers the switch receptor construct and the CAR design.",
    authors_or_owner: "Baylor College of Medicine Office of Research",
    institution_or_sponsor: "Baylor College of Medicine",
    date: "2025-01-28",
    stage_hint: "phase 1",
    url: "https://www.bcm.edu/research/office-of-research/technology-transfer",
    metadata: { licensing_status: "available", contact_office: "BCM Technology Transfer", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Epstein-Barr Virus (EBV) mRNA Vaccine for Prophylaxis and Post-Transplant Lymphoma Prevention",
    text: "An mRNA vaccine encoding a cocktail of EBV latent membrane proteins (LMP1, LMP2A) and lytic antigens (gp350, EBNA1) formulated in LNPs for prophylactic immunization against primary EBV infection and post-transplant EBV-driven lymphoproliferative disease. Preclinical data in humanized mouse models demonstrate T cell responses against all four antigen components. Designed for: (1) adolescent prophylaxis (preventing infectious mononucleosis and EBV-associated cancers) and (2) pre-transplant immunization.",
    authors_or_owner: "Baylor College of Medicine Office of Research",
    institution_or_sponsor: "Baylor College of Medicine",
    date: "2024-11-05",
    stage_hint: "preclinical",
    url: "https://www.bcm.edu/research/office-of-research/technology-transfer",
    metadata: { licensing_status: "available", contact_office: "BCM Technology Transfer", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "GD2-CAR T Cell for Pediatric Neuroblastoma with Armored IL-15 Co-Stimulation",
    text: "An anti-GD2 CAR T cell construct co-expressing membrane-bound IL-15 (mbIL-15) that provides autonomous T cell survival signaling without the toxicity of secreted IL-15. Phase 1/2 interim data in 14 pediatric high-risk neuroblastoma patients: 8/14 objective responses, 4 complete responses. The mbIL-15 design overcomes the persistence failure that limited prior GD2-CAR-T programs. Technology covers the CAR design, mbIL-15 construct, and manufacturing protocol.",
    authors_or_owner: "Baylor College of Medicine Office of Research",
    institution_or_sponsor: "Baylor College of Medicine",
    date: "2024-09-10",
    stage_hint: "phase 1",
    url: "https://www.bcm.edu/research/office-of-research/technology-transfer",
    metadata: { licensing_status: "available", contact_office: "BCM Technology Transfer", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Allogeneic Natural Killer T Cell (NKT) Therapy for CD1d-Positive Tumors",
    text: "An off-the-shelf invariant NKT cell therapy (iNKT) engineered to express a CD1d-restricted TCR, an anti-GD2 CAR, and IL-15 autocrine signaling, providing triple-mechanism tumor killing against GD2+/CD1d+ tumors. Unlike conventional T or NK cell therapies, iNKT cells do not cause GvHD, enabling true allogeneic use without HLA matching. In multiple myeloma and neuroblastoma models, the armored iNKT cells show superior efficacy to NK cells and conventional CAR-T.",
    authors_or_owner: "Baylor College of Medicine Office of Research",
    institution_or_sponsor: "Baylor College of Medicine",
    date: "2024-06-20",
    stage_hint: "preclinical",
    url: "https://www.bcm.edu/research/office-of-research/technology-transfer",
    metadata: { licensing_status: "available", contact_office: "BCM Technology Transfer", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Virus-Specific T Cell Therapy Panel for Immunodeficiency Viral Reactivations",
    text: "A GMP-manufactured multi-virus-specific T cell (mVST) product targeting CMV, EBV, adenovirus, BK virus, and HHV-6 from a single donor T cell expansion, providing prophylaxis or treatment for the major opportunistic viral infections complicating stem cell transplantation. A third-party mVST bank of 40 donors provides HLA-matched products for >90% of transplant recipients. Phase 2 study showed 76% complete antiviral response rate with no grade 3+ toxicities.",
    authors_or_owner: "Baylor College of Medicine Office of Research",
    institution_or_sponsor: "Baylor College of Medicine",
    date: "2025-02-15",
    stage_hint: "phase 2",
    url: "https://www.bcm.edu/research/office-of-research/technology-transfer",
    metadata: { licensing_status: "available", contact_office: "BCM Technology Transfer", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Methylation-Reprogrammed iPSC Line for Accelerated CAR-T Manufacturing",
    text: "An iPSC line with epigenetic pre-programming of the T cell differentiation loci that produces functional CD8+ cytotoxic T cells from iPSC in 7 days versus the standard 21-28 day protocol. The epigenetic state is stable through CAR transgene integration and multiple passages. Benchmark studies show equivalent antitumor cytotoxicity and persistence to conventional CAR-T and 3x higher CAR expression density than standard iPSC-derived T cells.",
    authors_or_owner: "Baylor College of Medicine Office of Research",
    institution_or_sponsor: "Baylor College of Medicine",
    date: "2024-10-25",
    stage_hint: "preclinical",
    url: "https://www.bcm.edu/research/office-of-research/technology-transfer",
    metadata: { licensing_status: "available", contact_office: "BCM Technology Transfer", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Synthetic Antigen-Presenting Cell Platform for Scalable TCR-T Cell Manufacturing",
    text: "A K562-based artificial antigen-presenting cell (aAPC) platform genetically modified to express HLA-A*02:01, costimulatory ligands (4-1BBL, CD80), and tumor antigen peptides for rapid expansion of antigen-specific T cells without the need for autologous APCs or dendritic cells. The platform enables manufacturing of large-scale, highly pure neoantigen-specific T cell products from peripheral blood in 8-10 days. Adaptable to any HLA type and antigen of interest.",
    authors_or_owner: "Baylor College of Medicine Office of Research",
    institution_or_sponsor: "Baylor College of Medicine",
    date: "2024-07-08",
    stage_hint: "preclinical",
    url: "https://www.bcm.edu/research/office-of-research/technology-transfer",
    metadata: { licensing_status: "available", contact_office: "BCM Technology Transfer", patent_status: "patented", owner_type: "university" },
  },
];

export function getBaylorListings(): RawSignal[] {
  return BAYLOR_LISTINGS.map((l, i) => ({ ...l, id: `baylor-tt-${i}` }));
}
