import type { RawSignal } from "../../types";

const BROAD_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "Prime Editing Delivery System for In Vivo Liver Gene Correction",
    text: "Broad Institute researchers have engineered a lipid nanoparticle formulation optimized for hepatic delivery of prime editing machinery (pegRNA + PE3 nickase) with >60% editing efficiency in mouse liver at clinically relevant mRNA doses. The technology includes a proprietary pegRNA design toolkit and LNP surface modifications that reduce immunogenicity. Targeting applications in alpha-1 antitrypsin deficiency and hereditary ATTR amyloidosis.",
    authors_or_owner: "Broad Institute Technology",
    institution_or_sponsor: "Broad Institute of MIT and Harvard",
    date: "2025-01-15",
    stage_hint: "preclinical",
    url: "https://www.broadinstitute.org/technology-licensing",
    metadata: {
      licensing_status: "available",
      contact_office: "Broad Institute Technology Licensing",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "CRISPR Interference (CRISPRi) Screen Platform for Drug Target Identification",
    text: "A genome-wide CRISPRi screen library and computational analysis platform developed at the Broad that systematically identifies essential genes in disease-relevant cell models. The platform has been validated across >50 cancer cell lines and produces high-confidence target lists with orthogonal validation. Optimized for pooled screening in primary human cells and patient-derived organoids. IP covers the library design, arrayed screening protocol, and the analysis pipeline.",
    authors_or_owner: "Broad Institute Technology",
    institution_or_sponsor: "Broad Institute of MIT and Harvard",
    date: "2024-08-20",
    stage_hint: "discovery",
    url: "https://www.broadinstitute.org/technology-licensing",
    metadata: {
      licensing_status: "available",
      contact_office: "Broad Institute Technology Licensing",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Small Molecule PCSK9 Inhibitor for LDL Cholesterol Reduction",
    text: "Broad chemists have identified a small molecule that disrupts the PCSK9-LDLR protein-protein interaction with IC50 in the low nanomolar range and oral bioavailability of 42% in rats. Unlike injectable anti-PCSK9 monoclonal antibodies, the oral formulation addresses a significant unmet need for high-risk cardiovascular patients with compliance or access barriers. The compound class is novel and does not overlap with existing IP.",
    authors_or_owner: "Broad Institute Technology",
    institution_or_sponsor: "Broad Institute of MIT and Harvard",
    date: "2024-11-03",
    stage_hint: "preclinical",
    url: "https://www.broadinstitute.org/technology-licensing",
    metadata: {
      licensing_status: "available",
      contact_office: "Broad Institute Technology Licensing",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Epigenetic Reprogramming of Exhausted T Cells via TET2 Modulation",
    text: "A gene editing strategy that prevents T cell exhaustion by transiently suppressing TET2 during ex vivo CAR-T manufacturing, creating cells with a memory-like epigenetic state. CAR-T cells manufactured with this method show 3–5x greater persistence in chronic antigen stimulation models and superior tumor control in solid tumor models where exhaustion is a key resistance mechanism. Compatible with existing CAR construct designs.",
    authors_or_owner: "Broad Institute Technology",
    institution_or_sponsor: "Broad Institute of MIT and Harvard",
    date: "2024-06-30",
    stage_hint: "preclinical",
    url: "https://www.broadinstitute.org/technology-licensing",
    metadata: {
      licensing_status: "available",
      contact_office: "Broad Institute Technology Licensing",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Polygenic Risk Score Platform for Coronary Artery Disease Patient Stratification",
    text: "A validated polygenic risk score (PRS) and clinical decision algorithm for identifying the top 20% of individuals at elevated lifetime risk of coronary artery disease — a group who derive the greatest absolute benefit from preventive therapies. The score, trained on UK Biobank and validated in multiple ancestry cohorts, is packaged as an assay-agnostic computational toolkit suitable for integration with standard clinical genotyping arrays or whole-genome sequencing data.",
    authors_or_owner: "Broad Institute Technology",
    institution_or_sponsor: "Broad Institute of MIT and Harvard",
    date: "2024-03-18",
    stage_hint: "discovery",
    url: "https://www.broadinstitute.org/technology-licensing",
    metadata: {
      licensing_status: "available",
      contact_office: "Broad Institute Technology Licensing",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "RNA Aptamer-Drug Conjugate for Targeted Delivery to GBM",
    text: "A tumor-targeting RNA aptamer selected for high-affinity binding to EGFRvIII, the mutant receptor exclusively expressed on glioblastoma cells, conjugated to a brain-penetrant cytotoxin. The aptamer-drug conjugate (ApDC) crosses the blood-brain barrier via active transport and achieves selective tumor accumulation with a >10-fold therapeutic index improvement over unconjugated cytotoxin in orthotopic GBM xenograft models.",
    authors_or_owner: "Broad Institute Technology",
    institution_or_sponsor: "Broad Institute of MIT and Harvard",
    date: "2025-02-10",
    stage_hint: "preclinical",
    url: "https://www.broadinstitute.org/technology-licensing",
    metadata: {
      licensing_status: "available",
      contact_office: "Broad Institute Technology Licensing",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Base Editing Correction of Sickle Cell Disease Mutation at Scale",
    text: "An adenine base editor (ABE8e) delivered via optimized electroporation of hematopoietic stem and progenitor cells (HSPCs) that converts the HbS point mutation to a benign HbG variant with >80% editing efficiency and >95% allele correction in CD34+ cells. The corrected HSPCs show normal multilineage differentiation and engraftment in immunodeficient mice, with no off-target events detected by rhAmpSeq. IND-enabling studies ongoing.",
    authors_or_owner: "Broad Institute Technology",
    institution_or_sponsor: "Broad Institute of MIT and Harvard",
    date: "2024-12-15",
    stage_hint: "preclinical",
    url: "https://www.broadinstitute.org/technology-licensing",
    metadata: {
      licensing_status: "available",
      contact_office: "Broad Institute Technology Licensing",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Transcription Factor Proximity Proteomics for Drug Target Discovery",
    text: "A BioID2-based proximity labeling approach applied to oncogenic transcription factors (MYC, STAT3, beta-catenin) in live tumor cells to map the full protein interaction network under native chromatin conditions. The platform generates a comprehensive interactome map that reveals novel druggable protein-protein interactions and co-factors not identified by traditional pulldown proteomics. Validated target candidates include three novel co-activator proteins with no existing drug programs.",
    authors_or_owner: "Broad Institute Technology",
    institution_or_sponsor: "Broad Institute of MIT and Harvard",
    date: "2024-09-25",
    stage_hint: "discovery",
    url: "https://www.broadinstitute.org/technology-licensing",
    metadata: {
      licensing_status: "available",
      contact_office: "Broad Institute Technology Licensing",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
];

export function getBroadListings(): RawSignal[] {
  return BROAD_LISTINGS.map((l, i) => ({ ...l, id: `broad-tt-${i}` }));
}
