import type { RawSignal } from "../../types";

const COLUMBIA_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "Antibody-Drug Conjugate Targeting Mesothelin for Pancreatic and Ovarian Cancer",
    text: "A Columbia-developed ADC combining a high-affinity anti-mesothelin antibody with a novel topoisomerase I inhibitor payload via a plasma-stable cleavable linker. The conjugate achieves potent cytotoxicity in mesothelin-high PDAC and ovarian cancer cell lines and patient-derived organoids with a drug-to-antibody ratio of 8, achieving superior bystander killing compared to clinically tested mesothelin ADCs. DAR and linker chemistry are separately licensable.",
    authors_or_owner: "Columbia Technology Ventures",
    institution_or_sponsor: "Columbia University",
    date: "2025-01-12",
    stage_hint: "preclinical",
    url: "https://techventures.columbia.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Columbia Technology Ventures", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Neomorphic p53 Reactivator Small Molecule for Gain-of-Function TP53 Mutant Cancers",
    text: "A small molecule that reactivates apoptotic signaling in tumor cells harboring gain-of-function TP53 mutations (R175H, R248W, R273H) by restoring wild-type-like conformation to mutant p53. The compound shows selective cytotoxicity in GOF-TP53 cell lines at submicromolar concentrations, with no activity against wild-type TP53 or null TP53 backgrounds, suggesting a genuine reactivation mechanism. Effective in PDAC, lung, and ovarian cancer models harboring GOF mutations.",
    authors_or_owner: "Columbia Technology Ventures",
    institution_or_sponsor: "Columbia University",
    date: "2024-09-20",
    stage_hint: "preclinical",
    url: "https://techventures.columbia.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Columbia Technology Ventures", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Intranasal AAV Gene Therapy for Rett Syndrome",
    text: "A non-invasive intranasal delivery route for AAV9-MECP2 that achieves widespread CNS transduction in mice and juvenile macaques, bypassing the need for intrathecal injection. The approach achieves >60% neuronal transduction across cortex, hippocampus, and brainstem following a single intranasal administration. Behavioral recovery comparable to intrathecal delivery in Rett syndrome mouse models, with a substantially safer administration profile for pediatric use.",
    authors_or_owner: "Columbia Technology Ventures",
    institution_or_sponsor: "Columbia University",
    date: "2024-07-08",
    stage_hint: "preclinical",
    url: "https://techventures.columbia.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Columbia Technology Ventures", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Cyclic Peptide Degrader of BCL-2 Family Anti-Apoptotic Proteins",
    text: "A cell-penetrant cyclic peptide that recruits E3 ubiquitin ligase machinery to degrade BCL-2 and BCL-XL simultaneously, overcoming the single-target limitation of venetoclax. The PROTAC-like peptide shows >90% target depletion and achieves synergistic cytotoxicity with BCL-2-resistant AML and CLL cell lines. Unlike conventional PROTACs, the peptide format enables high selectivity and avoids hook effect at therapeutic concentrations.",
    authors_or_owner: "Columbia Technology Ventures",
    institution_or_sponsor: "Columbia University",
    date: "2024-11-25",
    stage_hint: "discovery",
    url: "https://techventures.columbia.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Columbia Technology Ventures", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Engineered T Cell Receptor Platform for Solid Tumor Neoantigen Targeting",
    text: "A high-throughput TCR discovery and engineering platform that identifies neoantigen-reactive TCRs from tumor-infiltrating lymphocytes and optimizes their affinity and CD8 co-receptor independence for adoptive cell therapy. The platform has generated a library of >200 tumor-reactive TCRs across 12 solid tumor types, with validated efficacy for 18 validated HLA-A*02:01 neoantigen targets. Licensing available for the full library or individual TCR sequences.",
    authors_or_owner: "Columbia Technology Ventures",
    institution_or_sponsor: "Columbia University",
    date: "2024-05-15",
    stage_hint: "preclinical",
    url: "https://techventures.columbia.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Columbia Technology Ventures", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Long-Acting Injectable Naltrexone Formulation for Opioid Use Disorder",
    text: "A biodegradable PLGA microsphere formulation of naltrexone that achieves therapeutic plasma concentrations for 45 days following a single subcutaneous injection, compared to the 30-day duration of the current Vivitrol product. The extended duration reduces treatment gaps and improves adherence in opioid use disorder. Formulation parameters are optimized for ambient temperature stability, removing cold chain requirements that limit access in low-resource settings.",
    authors_or_owner: "Columbia Technology Ventures",
    institution_or_sponsor: "Columbia University",
    date: "2024-03-28",
    stage_hint: "preclinical",
    url: "https://techventures.columbia.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Columbia Technology Ventures", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "FUS/TLS Protein Aggregation Inhibitor for ALS and FTD",
    text: "A small molecule identified via DEL screening that inhibits pathological cytoplasmic aggregation of FUS/TLS protein — one of the most prevalent mutations in familial ALS and frontotemporal dementia. The compound acts by stabilizing the nuclear import signal of FUS, preventing stress granule formation and cytotoxic aggregation at submicromolar concentrations. Penetrates the CNS at >40% brain-to-plasma ratio following oral dosing.",
    authors_or_owner: "Columbia Technology Ventures",
    institution_or_sponsor: "Columbia University",
    date: "2025-02-18",
    stage_hint: "preclinical",
    url: "https://techventures.columbia.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Columbia Technology Ventures", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Tumor-Reactive Allogeneic CAR-NK Cell Line for Hematologic Malignancies",
    text: "A clonal NK cell line genetically engineered with an anti-CD19 CAR, a high-affinity CD16 variant for enhanced ADCC, IL-15 autocrine signaling, and NKG2A knockout. The cell line is manufactured from a master cell bank for true off-the-shelf use without HLA matching requirements. In NHL and B-ALL xenograft models, the cells achieve deeper responses than primary NK cells and maintain activity for 28 days post-infusion.",
    authors_or_owner: "Columbia Technology Ventures",
    institution_or_sponsor: "Columbia University",
    date: "2024-10-10",
    stage_hint: "preclinical",
    url: "https://techventures.columbia.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Columbia Technology Ventures", patent_status: "patent pending", owner_type: "university" },
  },
];

export function getColumbiaListings(): RawSignal[] {
  return COLUMBIA_LISTINGS.map((l, i) => ({ ...l, id: `columbia-tt-${i}` }));
}
