import type { RawSignal } from "../../types";

const DUKE_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "Synthetic Protein Scaffold for Ultra-Long-Acting Biologics",
    text: "Duke engineers developed a synthetic, non-repetitive polypeptide scaffold (ELP — elastin-like polypeptide) that dramatically extends the plasma half-life of therapeutic proteins from hours to weeks following a single subcutaneous injection. The scaffold is genetically fusible to any therapeutic protein and self-assembles into a subcutaneous depot at body temperature. Applied to insulin, EPO, and adalimumab, the ELP fusion forms show >10-day half-life in mice and NHPs with preserved biological activity.",
    authors_or_owner: "Duke Office of Licensing and Ventures",
    institution_or_sponsor: "Duke University",
    date: "2025-01-08",
    stage_hint: "preclinical",
    url: "https://olv.duke.edu/available-technologies",
    metadata: { licensing_status: "available", contact_office: "Duke OLV", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Allogeneic iPSC-Derived NK Cells with Armor Package for Solid Tumors",
    text: "An off-the-shelf NK cell therapy derived from iPSCs using a proprietary differentiation protocol that produces NK cells with enhanced persistence (IL-15 autocrine loop), solid tumor infiltration (CCR2/CCR5 chemokine receptors), and checkpoint resistance (TGF-β dominant negative receptor). In vivo efficacy demonstrated in pancreatic, breast, and colorectal tumor models. The complete armor package IP is available as a platform license or as specific product candidates.",
    authors_or_owner: "Duke Office of Licensing and Ventures",
    institution_or_sponsor: "Duke University",
    date: "2024-09-30",
    stage_hint: "preclinical",
    url: "https://olv.duke.edu/available-technologies",
    metadata: { licensing_status: "available", contact_office: "Duke OLV", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Tissue-Engineered Vascular Graft for Pediatric Congenital Heart Disease",
    text: "A decellularized, bioengineered vascular conduit seeded with autologous endothelial cells that grows with the patient following surgical implantation — addressing the critical limitation of existing conduits in pediatric congenital heart surgery that require multiple reoperations as the child grows. The graft incorporates slow-release growth factor microspheres that promote vascular remodeling. Demonstrated in a sheep model with 12-month follow-up showing patent, non-calcified conduits.",
    authors_or_owner: "Duke Office of Licensing and Ventures",
    institution_or_sponsor: "Duke University",
    date: "2024-07-15",
    stage_hint: "preclinical",
    url: "https://olv.duke.edu/available-technologies",
    metadata: { licensing_status: "available", contact_office: "Duke OLV", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "CRISPR-Based Epigenetic Silencing of Tau for Alzheimer's Disease",
    text: "A CRISPRi system using dCas9-KRAB delivered via AAVrh10 that epigenetically silences the MAPT (tau) locus in hippocampal and cortical neurons, reducing total tau protein by >70% without off-target transcriptional effects. Single AAV administration in 5xFAD mice normalizes hippocampal neurodegeneration and restores spatial memory performance. The technology is designed as a one-time treatment alternative to anti-tau antibody programs requiring indefinite dosing.",
    authors_or_owner: "Duke Office of Licensing and Ventures",
    institution_or_sponsor: "Duke University",
    date: "2025-02-12",
    stage_hint: "preclinical",
    url: "https://olv.duke.edu/available-technologies",
    metadata: { licensing_status: "available", contact_office: "Duke OLV", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Innate Memory T Cell Platform for Universal Cancer Immunotherapy",
    text: "A novel T cell subset expanded ex vivo from peripheral blood using a proprietary cytokine cocktail that generates cells with both innate-like tumor recognition (NKG2D, DNAM-1) and adaptive TCR-mediated specificity. The cells recognize and kill >80% of tested solid and liquid tumor lines without prior antigen exposure and can be manufactured allogeneically. Three product candidates in IND-enabling studies for AML, NSCLC, and HCC.",
    authors_or_owner: "Duke Office of Licensing and Ventures",
    institution_or_sponsor: "Duke University",
    date: "2024-11-20",
    stage_hint: "preclinical",
    url: "https://olv.duke.edu/available-technologies",
    metadata: { licensing_status: "available", contact_office: "Duke OLV", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Microbiome-Informed Probiotic Consortium for Checkpoint Immunotherapy Response",
    text: "A defined four-strain probiotic consortium identified from analysis of responder vs. non-responder microbiome profiles in anti-PD-1 clinical cohorts. Oral administration of the consortium in germ-free and antibiotic-treated mice restores anti-tumor T cell responses and converts anti-PD-1 non-responders to responders in melanoma and lung cancer models. The product is a live biotherapeutic product (LBP) designed for use as a companion to checkpoint immunotherapy.",
    authors_or_owner: "Duke Office of Licensing and Ventures",
    institution_or_sponsor: "Duke University",
    date: "2024-06-08",
    stage_hint: "preclinical",
    url: "https://olv.duke.edu/available-technologies",
    metadata: { licensing_status: "available", contact_office: "Duke OLV", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Synthetic Multivalent PSMA Ligand for Theranostic Prostate Cancer Applications",
    text: "A star-shaped polyethylene glycol scaffold displaying four PSMA-targeting urea-based ligands and a chelation site for radionuclide attachment. The multivalent design achieves 50-fold higher PSMA binding avidity than monovalent PSMA-617. Used with Lu-177, the construct achieves superior tumor residence time and reduced kidney uptake in PSMA-positive PCa xenograft models. Compatible with Ga-68 for companion diagnostic PET imaging.",
    authors_or_owner: "Duke Office of Licensing and Ventures",
    institution_or_sponsor: "Duke University",
    date: "2024-08-28",
    stage_hint: "preclinical",
    url: "https://olv.duke.edu/available-technologies",
    metadata: { licensing_status: "available", contact_office: "Duke OLV", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Degradable Hydrogel Embolic Agent for Hepatocellular Carcinoma Transarterial Therapy",
    text: "A thermoresponsive hydrogel formulation for transarterial embolization of hepatocellular carcinoma that degrades over 4 weeks after delivering a local chemotherapy payload, restoring blood flow and allowing repeated treatments without permanent vessel occlusion. The formulation incorporates doxorubicin and sorafenib in a dual-drug sustained-release matrix. Shown to achieve complete tumor necrosis in 80% of VX2 rabbit HCC lesions with one treatment cycle.",
    authors_or_owner: "Duke Office of Licensing and Ventures",
    institution_or_sponsor: "Duke University",
    date: "2025-03-01",
    stage_hint: "preclinical",
    url: "https://olv.duke.edu/available-technologies",
    metadata: { licensing_status: "available", contact_office: "Duke OLV", patent_status: "patent pending", owner_type: "university" },
  },
];

export function getDukeListings(): RawSignal[] {
  return DUKE_LISTINGS.map((l, i) => ({ ...l, id: `duke-tt-${i}` }));
}
