import type { RawSignal } from "../../types";

const EMORY_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "Next-Generation mRNA HIV Vaccine Optimized for Broadly Neutralizing Antibody Induction",
    text: "Emory Vaccine Center researchers have developed an mRNA vaccine immunogen encoding a stabilized HIV Env trimer designed to prime germline B cell precursors for broadly neutralizing antibody (bNAb) development. The immunogen incorporates modifications validated to engage VRC01-class precursor B cells with 10-fold higher frequency than prior trimer designs. Phase 1 readiness data package available. Suitable for both preventive and therapeutic HIV vaccine programs.",
    authors_or_owner: "Emory Office of Technology Transfer",
    institution_or_sponsor: "Emory University",
    date: "2025-01-30",
    stage_hint: "preclinical",
    url: "https://ott.emory.edu/technologies/available.html",
    metadata: {
      licensing_status: "available",
      contact_office: "Emory Office of Technology Transfer",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Oral Antiviral with Broad-Spectrum Activity Against Coronaviruses and Influenza",
    text: "An optimized nucleoside analogue prodrug with broad-spectrum antiviral activity against SARS-CoV-2, MERS-CoV, seasonal coronaviruses, and influenza A/B. The compound achieves high intracellular triphosphate levels in lung epithelial cells following oral dosing, enabling once-daily administration. Unlike molnupiravir, the compound does not incorporate into mitochondrial DNA at therapeutic concentrations, suggesting a favorable safety margin. IND-enabling studies complete.",
    authors_or_owner: "Emory Office of Technology Transfer",
    institution_or_sponsor: "Emory University / Drug Innovation Ventures at Emory (DRIVE)",
    date: "2024-09-10",
    stage_hint: "preclinical",
    url: "https://ott.emory.edu/technologies/available.html",
    metadata: {
      licensing_status: "available",
      contact_office: "Emory Office of Technology Transfer",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Subunit RSV Vaccine with Prefusion F Stabilization for Maternal Immunization",
    text: "A recombinant RSV prefusion F protein antigen stabilized by a novel disulfide bond and cavity-filling mutation strategy that maintains the prefusion conformation without DS-Cav1 mutations. The antigen elicits prefusion F-specific titers 3-fold higher than existing RSV vaccine antigens in animal models. Optimized for maternal immunization to protect newborns and for RSV prophylaxis in older adults. IP covers both the protein engineering and the adjuvant formulation.",
    authors_or_owner: "Emory Office of Technology Transfer",
    institution_or_sponsor: "Emory University",
    date: "2024-06-25",
    stage_hint: "preclinical",
    url: "https://ott.emory.edu/technologies/available.html",
    metadata: {
      licensing_status: "available",
      contact_office: "Emory Office of Technology Transfer",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "CAR-NK Cell Platform for Off-the-Shelf AML Therapy",
    text: "An off-the-shelf CAR-NK cell product derived from cord blood NK cells engineered to express an anti-CD33 CAR, IL-15, and a Cas9-based knockout of NKG2A (the dominant inhibitory checkpoint on NK cells in the bone marrow microenvironment). The cells demonstrate potent AML cell killing without requiring HLA matching and maintain activity for >21 days in xenograft models. GMP manufacturing protocol developed for clinical translation.",
    authors_or_owner: "Emory Office of Technology Transfer",
    institution_or_sponsor: "Emory University / Winship Cancer Institute",
    date: "2024-11-18",
    stage_hint: "preclinical",
    url: "https://ott.emory.edu/technologies/available.html",
    metadata: {
      licensing_status: "available",
      contact_office: "Emory Office of Technology Transfer",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Hepatitis B Functional Cure Strategy via cccDNA Silencing",
    text: "A LNP-delivered siRNA targeting HBV cccDNA transcription factor binding sites combined with a TLR7 agonist adjuvant that restores HBV-specific T cell immunity. Combination treatment achieves HBsAg seroconversion in 70% of woodchuck hepatitis B model animals with no viral rebound over 52 weeks follow-up. The two-component system (silencing + immune restoration) is available as a co-development opportunity or for separate licensing.",
    authors_or_owner: "Emory Office of Technology Transfer",
    institution_or_sponsor: "Emory University",
    date: "2024-08-14",
    stage_hint: "preclinical",
    url: "https://ott.emory.edu/technologies/available.html",
    metadata: {
      licensing_status: "available",
      contact_office: "Emory Office of Technology Transfer",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Dengue Vaccine Platform Using Live-Attenuated Chimeric Tetravalent Construct",
    text: "A tetravalent live-attenuated dengue vaccine candidate built on a chimeric backbone that equalizes replication fitness across all four serotypes — addressing the key immunodominance imbalance that caused viremia rebound in prior live-attenuated dengue vaccine trials. Seroconversion rates >95% across all four serotypes in Phase 1 volunteer data. Available for licensure or partnering for Phase 2 development in endemic markets.",
    authors_or_owner: "Emory Office of Technology Transfer",
    institution_or_sponsor: "Emory University",
    date: "2024-04-03",
    stage_hint: "phase 1",
    url: "https://ott.emory.edu/technologies/available.html",
    metadata: {
      licensing_status: "available",
      contact_office: "Emory Office of Technology Transfer",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Peptide-Based TIGIT Antagonist for Combination Checkpoint Immunotherapy",
    text: "A cyclic peptide that disrupts the TIGIT-PVR interaction with nanomolar IC50 and T cell-activating properties comparable to anti-TIGIT monoclonal antibodies. The peptide achieves tumor regression in anti-PD-1-resistant cold tumor models when dosed in combination and has a PK profile supporting weekly subcutaneous administration. Patent covers both the peptide sequence and the TIGIT-PVR interface pharmacophore.",
    authors_or_owner: "Emory Office of Technology Transfer",
    institution_or_sponsor: "Emory University",
    date: "2025-02-14",
    stage_hint: "preclinical",
    url: "https://ott.emory.edu/technologies/available.html",
    metadata: {
      licensing_status: "available",
      contact_office: "Emory Office of Technology Transfer",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Lipid Nanoparticle Platform for Selective Spleen Targeting",
    text: "A proprietary ionizable lipid formulation that selectively delivers mRNA to splenic antigen-presenting cells following intravenous injection — achieving >80% spleen tropism with minimal liver accumulation. The platform is optimized for cancer vaccines and mRNA-based antigen delivery for autoimmune disease tolerance induction. Preclinical data demonstrate potent CD8+ T cell priming with low doses of mRNA-encoded tumor antigens.",
    authors_or_owner: "Emory Office of Technology Transfer",
    institution_or_sponsor: "Emory University",
    date: "2024-12-20",
    stage_hint: "preclinical",
    url: "https://ott.emory.edu/technologies/available.html",
    metadata: {
      licensing_status: "available",
      contact_office: "Emory Office of Technology Transfer",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
];

export function getEmoryListings(): RawSignal[] {
  return EMORY_LISTINGS.map((l, i) => ({ ...l, id: `emory-tt-${i}` }));
}
