import type { RawSignal } from "../../types";

const HARVARD_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "Bispecific Antibody Targeting IL-4Rα and TSLP for Severe Asthma",
    text: "Harvard immunologists have engineered a bispecific antibody that simultaneously blocks IL-4Rα and TSLP — two non-redundant drivers of type 2 inflammation — in a single molecule. Head-to-head studies against dupilumab and tezepelumab show superior suppression of eosinophil activation and bronchial hyperresponsiveness in NHP models of allergen-induced asthma. The format achieves half-life extension compatible with monthly subcutaneous dosing.",
    authors_or_owner: "Harvard Office of Technology Development",
    institution_or_sponsor: "Harvard University",
    date: "2025-01-25",
    stage_hint: "preclinical",
    url: "https://otd.harvard.edu/explore-technologies",
    metadata: {
      licensing_status: "available",
      contact_office: "Harvard Office of Technology Development",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "mRNA Therapeutic for Metabolic Reprogramming in NASH",
    text: "A liver-targeted mRNA encoding a truncated, constitutively active form of FGF21 with extended half-life, delivered via proprietary ionizable lipid nanoparticles optimized for hepatic tropism. Monthly IV dosing in diet-induced NASH mouse models achieves resolution of hepatic steatosis, fibrosis regression from F3 to F1, and normalization of metabolic parameters. The mRNA construct is separately licensable from the LNP delivery system.",
    authors_or_owner: "Harvard Office of Technology Development",
    institution_or_sponsor: "Harvard University",
    date: "2024-10-30",
    stage_hint: "preclinical",
    url: "https://otd.harvard.edu/explore-technologies",
    metadata: {
      licensing_status: "available",
      contact_office: "Harvard Office of Technology Development",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Photoswitchable Kinase Inhibitor for Spatiotemporal Drug Control",
    text: "A class of azobenzene-modified kinase inhibitors that can be toggled between active and inactive states by light of different wavelengths, enabling precise spatiotemporal control of drug activity in tissue. Developed initially for BRAF inhibition in melanoma, the photoswitchable scaffold has been extended to CDK4/6 and EGFR. Potential applications include ocular drug delivery, tumor bed illumination during surgery, and light-activated prodrug strategies.",
    authors_or_owner: "Harvard Office of Technology Development",
    institution_or_sponsor: "Harvard University",
    date: "2024-06-18",
    stage_hint: "discovery",
    url: "https://otd.harvard.edu/explore-technologies",
    metadata: {
      licensing_status: "available",
      contact_office: "Harvard Office of Technology Development",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Organ-on-Chip Platform for Drug-Induced Cardiotoxicity Testing",
    text: "A microfluidic heart-on-a-chip device incorporating iPSC-derived cardiomyocytes, cardiac fibroblasts, and endothelial cells under continuous flow that replicates human cardiac electrophysiology and contractility. The platform predicts QT prolongation, structural cardiotoxicity, and mitochondrial dysfunction with >90% concordance with clinical adverse event data across a 40-compound benchmark set. Available for licensing as a research tool or for pharmaceutical safety screening partnerships.",
    authors_or_owner: "Harvard Office of Technology Development",
    institution_or_sponsor: "Harvard University / Wyss Institute",
    date: "2024-08-05",
    stage_hint: "discovery",
    url: "https://otd.harvard.edu/explore-technologies",
    metadata: {
      licensing_status: "available",
      contact_office: "Harvard Office of Technology Development",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Galectin-9 Neutralizing Antibody for Immune Checkpoint Blockade",
    text: "A high-affinity monoclonal antibody against galectin-9, an immunosuppressive lectin that promotes T cell exhaustion and myeloid cell polarization within the tumor microenvironment. In triple-negative breast cancer and HCC syngeneic models, anti-galectin-9 treatment reverses CD8+ T cell exhaustion and synergizes with anti-PD-1 to achieve complete tumor regression in >60% of mice. The antibody does not compete with known anti-TIM-3 or anti-PD-L1 binding epitopes.",
    authors_or_owner: "Harvard Office of Technology Development",
    institution_or_sponsor: "Harvard University / Dana-Farber",
    date: "2024-12-01",
    stage_hint: "preclinical",
    url: "https://otd.harvard.edu/explore-technologies",
    metadata: {
      licensing_status: "available",
      contact_office: "Harvard Office of Technology Development",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "CRISPR-Mediated Hyper-IL-6 Gene Circuit for On-Demand Cytokine Control",
    text: "A synthetic gene circuit inserted into the AAVS1 safe harbor locus that places IL-6 trans-signaling under the control of a drug-inducible promoter, enabling physicians to titrate anti-inflammatory IL-6 decoy activity on demand. Designed for autoimmune conditions where IL-6 signaling is episodically elevated (flares). The approach avoids continuous systemic immunosuppression while providing precise flare control. Applicable to rheumatoid arthritis, Castleman disease, and cytokine release syndromes.",
    authors_or_owner: "Harvard Office of Technology Development",
    institution_or_sponsor: "Harvard University",
    date: "2024-04-08",
    stage_hint: "discovery",
    url: "https://otd.harvard.edu/explore-technologies",
    metadata: {
      licensing_status: "available",
      contact_office: "Harvard Office of Technology Development",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Peptide Macrocycle Library for Targeting Undruggable PPI Interfaces",
    text: "A 500,000-compound macrocyclic peptide library constructed using a proprietary split-intein cyclization platform that generates conformationally constrained macrocycles optimized for cell permeability and protease resistance. The library has been screened against 8 intractable protein-protein interaction targets (MYC-MAX, p53-MDM2, BCL-6 corepressor domain) yielding hit rates 15-fold higher than linear peptide libraries. Full screening and hit optimization services are available alongside library licensing.",
    authors_or_owner: "Harvard Office of Technology Development",
    institution_or_sponsor: "Harvard University",
    date: "2025-02-20",
    stage_hint: "discovery",
    url: "https://otd.harvard.edu/explore-technologies",
    metadata: {
      licensing_status: "available",
      contact_office: "Harvard Office of Technology Development",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Extracellular Vesicle-Based Liquid Biopsy for Early Pancreatic Cancer Detection",
    text: "A plasma-based liquid biopsy assay that captures tumor-derived extracellular vesicles and quantifies a 12-protein surface signature associated with early-stage pancreatic ductal adenocarcinoma (PDAC). In a prospective cohort of 280 patients, the assay detected stage I/II PDAC with 88% sensitivity at 95% specificity — significantly outperforming CA19-9 alone. The assay has been validated on a standard clinical flow cytometry platform for clinical translation.",
    authors_or_owner: "Harvard Office of Technology Development",
    institution_or_sponsor: "Harvard University / Massachusetts General Hospital",
    date: "2024-07-22",
    stage_hint: "preclinical",
    url: "https://otd.harvard.edu/explore-technologies",
    metadata: {
      licensing_status: "available",
      contact_office: "Harvard Office of Technology Development",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
];

export function getHarvardListings(): RawSignal[] {
  return HARVARD_LISTINGS.map((l, i) => ({ ...l, id: `harvard-tt-${i}` }));
}
