import type { RawSignal } from "../../types";

const JHU_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "AAV-Delivered microRNA Sponge for Heart Failure Gene Therapy",
    text: "Johns Hopkins cardiologists have developed a cardiac-tropic AAV9 vector expressing a competitive endogenous RNA (ceRNA) that sequesters miR-25, a microRNA upregulated in heart failure that suppresses SERCA2a expression. Intracardiac delivery restores calcium handling and cardiac contractility in both ischemic and non-ischemic heart failure models. A Phase 1 enabling package is complete; preclinical toxicology studies are ongoing.",
    authors_or_owner: "Johns Hopkins Technology Ventures",
    institution_or_sponsor: "Johns Hopkins University",
    date: "2025-01-08",
    stage_hint: "preclinical",
    url: "https://ventures.jhu.edu/technologies-for-licensing",
    metadata: {
      licensing_status: "available",
      contact_office: "Johns Hopkins Technology Ventures",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Neoantigen Peptide Vaccine Platform with Adjuvant Optimization",
    text: "A personalized neoantigen vaccine platform that combines rapid next-generation sequencing of tumor biopsies, proprietary immunogenicity prediction algorithms, and a self-assembling peptide-lipid nanoparticle adjuvant system. Clinical pilot data from 12 patients with resected colorectal cancer demonstrate robust neoantigen-specific T cell responses in 10/12 patients. The adjuvant nanoparticle formulation is separately licensable.",
    authors_or_owner: "Johns Hopkins Technology Ventures",
    institution_or_sponsor: "Johns Hopkins University",
    date: "2024-09-14",
    stage_hint: "phase 1",
    url: "https://ventures.jhu.edu/technologies-for-licensing",
    metadata: {
      licensing_status: "available",
      contact_office: "Johns Hopkins Technology Ventures",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "PSMA-Targeted Alpha Particle Therapy for Metastatic Prostate Cancer",
    text: "A novel PSMA-binding small molecule conjugated to an actinium-225 chelator for targeted alpha particle radiotherapy of metastatic castration-resistant prostate cancer. The compound shows superior tumor dose deposition and lower kidney uptake compared to PSMA-617 in head-to-head biodistribution studies. IP covers the targeting molecule, chelator design, and dosing protocol.",
    authors_or_owner: "Johns Hopkins Technology Ventures",
    institution_or_sponsor: "Johns Hopkins University",
    date: "2024-11-30",
    stage_hint: "preclinical",
    url: "https://ventures.jhu.edu/technologies-for-licensing",
    metadata: {
      licensing_status: "available",
      contact_office: "Johns Hopkins Technology Ventures",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "STING Agonist Prodrug with Tumor-Selective Activation",
    text: "A cyclic dinucleotide STING agonist prodrug that is activated selectively within the acidic tumor microenvironment, overcoming the delivery limitations that have hampered systemic STING agonist development. Intratumoral and intravenous formulations both achieve tumor-localized innate immune activation without systemic cytokine elevation. Synergistic activity demonstrated with anti-PD-1 in cold tumor models (pancreatic, prostate).",
    authors_or_owner: "Johns Hopkins Technology Ventures",
    institution_or_sponsor: "Johns Hopkins University",
    date: "2024-07-05",
    stage_hint: "preclinical",
    url: "https://ventures.jhu.edu/technologies-for-licensing",
    metadata: {
      licensing_status: "available",
      contact_office: "Johns Hopkins Technology Ventures",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "AI-Driven Retinal OCT Biomarker for Early Alzheimer's Detection",
    text: "A validated machine learning model trained on paired retinal OCT and brain amyloid PET data that identifies early Alzheimer's disease-associated retinal microvascular and structural changes with 84% sensitivity and 81% specificity in a 600-patient prospective cohort. The diagnostic algorithm is deployable on standard clinical OCT devices without hardware modification, enabling low-cost screening at ophthalmology visits.",
    authors_or_owner: "Johns Hopkins Technology Ventures",
    institution_or_sponsor: "Johns Hopkins University",
    date: "2024-05-22",
    stage_hint: "preclinical",
    url: "https://ventures.jhu.edu/technologies-for-licensing",
    metadata: {
      licensing_status: "available",
      contact_office: "Johns Hopkins Technology Ventures",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Synthetic Hydrogel Matrix for Ex Vivo HSC Expansion",
    text: "A polyethylene glycol-based synthetic hydrogel engineered with tunable stiffness and biomimetic ligands that recapitulates the bone marrow niche to support >50-fold expansion of long-term hematopoietic stem cells (LT-HSCs) over 14 days without loss of multipotency. The platform enables clinical-scale HSC manufacturing for gene therapy and transplant applications and outperforms current cytokine-only expansion systems.",
    authors_or_owner: "Johns Hopkins Technology Ventures",
    institution_or_sponsor: "Johns Hopkins University",
    date: "2024-10-17",
    stage_hint: "preclinical",
    url: "https://ventures.jhu.edu/technologies-for-licensing",
    metadata: {
      licensing_status: "available",
      contact_office: "Johns Hopkins Technology Ventures",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Topoisomerase II Inhibitor with Reduced Cardiotoxicity for Breast Cancer",
    text: "A novel topoisomerase IIα-selective inhibitor that achieves potent DNA damage in tumor cells while sparing topoisomerase IIβ — the isoform responsible for doxorubicin-induced cardiomyopathy. The compound shows comparable efficacy to doxorubicin in HER2+ and triple-negative breast cancer models with no detectable cardiac troponin elevation at therapeutic doses in non-human primates.",
    authors_or_owner: "Johns Hopkins Technology Ventures",
    institution_or_sponsor: "Johns Hopkins University",
    date: "2025-02-05",
    stage_hint: "preclinical",
    url: "https://ventures.jhu.edu/technologies-for-licensing",
    metadata: {
      licensing_status: "available",
      contact_office: "Johns Hopkins Technology Ventures",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Oral Butyrate Prodrug for Inflammatory Bowel Disease",
    text: "A novel ester prodrug of butyrate that resists hydrolysis in the small intestine and delivers butyrate selectively to the colonic mucosa, where it exerts anti-inflammatory effects via HDAC inhibition and GPR109a activation. The compound achieves 8-fold higher colonic butyrate concentrations than oral butyrate in murine DSS colitis and butyrate enema comparators, with statistically significant histology improvement and cytokine reduction.",
    authors_or_owner: "Johns Hopkins Technology Ventures",
    institution_or_sponsor: "Johns Hopkins University",
    date: "2024-08-11",
    stage_hint: "preclinical",
    url: "https://ventures.jhu.edu/technologies-for-licensing",
    metadata: {
      licensing_status: "available",
      contact_office: "Johns Hopkins Technology Ventures",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
];

export function getJohnsHopkinsListings(): RawSignal[] {
  return JHU_LISTINGS.map((l, i) => ({ ...l, id: `jhu-tt-${i}` }));
}
