import type { RawSignal } from "../../types";

const MAYO_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "Ultra-Sensitive ctDNA Liquid Biopsy for Multi-Cancer Early Detection",
    text: "Mayo Clinic has developed a next-generation cell-free DNA methylation analysis platform capable of detecting circulating tumor DNA at parts-per-million sensitivity for multi-cancer early detection. The assay combines whole-genome bisulfite sequencing with AI-based tissue-of-origin deconvolution to detect 12 cancer types with high specificity from a single blood draw. Validated in a prospective cohort of 8,000 subjects with 3-year follow-up. CLIA lab process fully developed.",
    authors_or_owner: "Mayo Clinic Ventures",
    institution_or_sponsor: "Mayo Clinic",
    date: "2024-11-05",
    stage_hint: "discovery",
    url: "https://www.mayo.edu/research/mayo-clinic-ventures",
    metadata: { licensing_status: "available", contact_office: "Mayo Clinic Ventures", patent_status: "patented", owner_type: "hospital" },
  },
  {
    source_type: "tech_transfer",
    title: "Senolytic Drug Combination for Frailty and Age-Related Disease",
    text: "Mayo Clinic, pioneers of senolytic research, have identified an optimized dasatinib + quercetin combination protocol with defined dosing, intermittent regimen, and novel formulation that maximizes senescent cell clearance while minimizing adverse events. Clinical studies in idiopathic pulmonary fibrosis, diabetic kidney disease, and frailty demonstrate biomarker-confirmed senolytic activity and clinical benefit. Multiple clinical trials ongoing with partnerships for IND-stage next-generation senolytics.",
    authors_or_owner: "Mayo Clinic Ventures",
    institution_or_sponsor: "Mayo Clinic",
    date: "2024-06-20",
    stage_hint: "phase 2",
    url: "https://www.mayo.edu/research/mayo-clinic-ventures",
    metadata: { licensing_status: "available", contact_office: "Mayo Clinic Ventures", patent_status: "patented", owner_type: "hospital" },
  },
  {
    source_type: "tech_transfer",
    title: "Bioengineered Cardiac Patch for Myocardial Infarction Regeneration",
    text: "Mayo Clinic bioengineers have developed a decellularized extracellular matrix cardiac patch seeded with iPSC-derived cardiomyocytes and vascular cells that integrates with host myocardium and improves cardiac function post-MI. The patch releases paracrine factors promoting endogenous regeneration and reduces adverse remodeling. Porcine MI studies show 20% improvement in ejection fraction at 90 days. Surgical application is minimally invasive via thoracoscopy.",
    authors_or_owner: "Mayo Clinic Ventures",
    institution_or_sponsor: "Mayo Clinic",
    date: "2024-03-15",
    stage_hint: "preclinical",
    url: "https://www.mayo.edu/research/mayo-clinic-ventures",
    metadata: { licensing_status: "available", contact_office: "Mayo Clinic Ventures", patent_status: "patent pending", owner_type: "hospital" },
  },
  {
    source_type: "tech_transfer",
    title: "AI Diagnostic Algorithm for Rare Disease Identification from EHR",
    text: "Mayo Clinic has developed and clinically validated an AI algorithm that identifies patients with rare, underdiagnosed diseases (including systemic mastocytosis, amyloidosis, and hereditary angioedema) from electronic health record data years before clinical diagnosis. The algorithm analyzes unstructured clinical notes, lab trends, and diagnosis codes using a transformer architecture trained on Mayo's longitudinal EHR database. Demonstrated 3-year lead time improvement in rare disease diagnosis.",
    authors_or_owner: "Mayo Clinic Ventures",
    institution_or_sponsor: "Mayo Clinic",
    date: "2023-09-12",
    stage_hint: "discovery",
    url: "https://www.mayo.edu/research/mayo-clinic-ventures",
    metadata: { licensing_status: "available", contact_office: "Mayo Clinic Ventures", patent_status: "patent pending", owner_type: "hospital" },
  },
  {
    source_type: "tech_transfer",
    title: "Exosome-Delivered microRNA Therapeutic for Cardiac Repair",
    text: "Mayo Clinic researchers have developed engineered exosomes loaded with a specific microRNA (miR-302) that activates cardiomyocyte cell cycle re-entry, promoting endogenous cardiac repair after myocardial infarction. The exosomes are derived from cardiac progenitor cells and target cardiomyocytes via specific surface peptides. In porcine MI models, IV administration improves ejection fraction and reduces scar area. Scalable GMP manufacturing protocol established.",
    authors_or_owner: "Mayo Clinic Ventures",
    institution_or_sponsor: "Mayo Clinic",
    date: "2024-08-22",
    stage_hint: "preclinical",
    url: "https://www.mayo.edu/research/mayo-clinic-ventures",
    metadata: { licensing_status: "available", contact_office: "Mayo Clinic Ventures", patent_status: "patent pending", owner_type: "hospital" },
  },
  {
    source_type: "tech_transfer",
    title: "Xenotransplantation Tolerance Induction Protocol",
    text: "Mayo Clinic transplant researchers have developed a tolerance induction protocol combining regulatory T cell therapy with targeted costimulation blockade that prevents rejection of porcine xenograft kidneys in non-human primates for over 6 months without chronic immunosuppression. The protocol uses GLP-1 receptor signaling enhancement to expand Tregs and suppress alloreactive responses. Positioned to support clinical xenotransplantation programs.",
    authors_or_owner: "Mayo Clinic Ventures",
    institution_or_sponsor: "Mayo Clinic",
    date: "2024-07-09",
    stage_hint: "preclinical",
    url: "https://www.mayo.edu/research/mayo-clinic-ventures",
    metadata: { licensing_status: "available", contact_office: "Mayo Clinic Ventures", patent_status: "patent pending", owner_type: "hospital" },
  },
  {
    source_type: "tech_transfer",
    title: "Biodegradable Nerve Conduit with Neurotrophic Factor Release",
    text: "Mayo Clinic neurosurgeons have developed a bioabsorbable nerve repair conduit incorporating sustained-release microspheres of NGF and GDNF. The conduit provides structural guidance and neurotrophic support for peripheral nerve regeneration across gaps up to 5 cm. Clinical-grade manufacturing uses FDA-approved PLGA materials. Large animal studies show functional nerve recovery superior to autograft in gaps of 3–5 cm, addressing a key unmet need in peripheral nerve surgery.",
    authors_or_owner: "Mayo Clinic Ventures",
    institution_or_sponsor: "Mayo Clinic",
    date: "2023-11-28",
    stage_hint: "preclinical",
    url: "https://www.mayo.edu/research/mayo-clinic-ventures",
    metadata: { licensing_status: "available", contact_office: "Mayo Clinic Ventures", patent_status: "patented", owner_type: "hospital" },
  },
  {
    source_type: "tech_transfer",
    title: "Plasma Protein Signature for Alzheimer's Disease Staging",
    text: "Mayo Clinic neurologists have identified a 7-plasma-protein signature enabling accurate staging of Alzheimer's disease pathology across the preclinical, MCI, and dementia continuum without PET imaging or CSF lumbar puncture. The panel incorporates phospho-tau 217, GFAP, NfL, and four novel proteins first characterized at Mayo. Validated in the Mayo Clinic Study of Aging (n=3,500). Clinical-grade Simoa and mass spectrometry assay formats developed.",
    authors_or_owner: "Mayo Clinic Ventures",
    institution_or_sponsor: "Mayo Clinic",
    date: "2024-04-30",
    stage_hint: "discovery",
    url: "https://www.mayo.edu/research/mayo-clinic-ventures",
    metadata: { licensing_status: "available", contact_office: "Mayo Clinic Ventures", patent_status: "patented", owner_type: "hospital" },
  },
];

export function getMayoListings(): RawSignal[] {
  return MAYO_LISTINGS.map((listing) => ({
    ...listing,
    id: `mayo-${Math.random().toString(36).slice(2, 9)}`,
  }));
}
