import type { RawSignal } from "../../types";

const MDANDERSON_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "Tumor Microenvironment Repolarizing Nanoparticle for Solid Tumors",
    text: "MD Anderson researchers have engineered lipid nanoparticles that selectively accumulate in solid tumors and deliver a macrophage repolarization payload converting immunosuppressive M2 tumor-associated macrophages to pro-inflammatory M1 phenotypes. The nanoparticles are surface-modified with mannose for active macrophage targeting. In multiple syngeneic tumor models (pancreatic, colorectal, prostate), treatment synergizes with checkpoint inhibitors to produce complete responses in previously resistant tumors.",
    authors_or_owner: "MD Anderson Technology Commercialization",
    institution_or_sponsor: "MD Anderson Cancer Center",
    date: "2024-10-22",
    stage_hint: "preclinical",
    url: "https://www.mdanderson.org/research/departments-labs-institutes/programs-centers/institute-for-applied-cancer-science.html",
    metadata: { licensing_status: "available", contact_office: "MD Anderson Technology Commercialization", patent_status: "patent pending", owner_type: "hospital" },
  },
  {
    source_type: "tech_transfer",
    title: "VEGFR3/LYVE-1 Dual-Targeting Antibody for Lymph Node Metastasis",
    text: "MD Anderson cancer biologists have developed a bispecific antibody simultaneously blocking VEGFR3 and LYVE-1 to prevent lymphangiogenesis-mediated tumor dissemination to sentinel lymph nodes. This dual-blockade strategy is differentiated from VEGF-C pathway monotherapy and reduces lymph node metastasis by 80% in breast, melanoma, and head-and-neck cancer models. The antibody retains activity in VEGFR3-inhibitor-resistant settings through the orthogonal LYVE-1 mechanism.",
    authors_or_owner: "MD Anderson Technology Commercialization",
    institution_or_sponsor: "MD Anderson Cancer Center",
    date: "2024-07-30",
    stage_hint: "preclinical",
    url: "https://www.mdanderson.org/research/departments-labs-institutes/programs-centers/institute-for-applied-cancer-science.html",
    metadata: { licensing_status: "available", contact_office: "MD Anderson Technology Commercialization", patent_status: "patent pending", owner_type: "hospital" },
  },
  {
    source_type: "tech_transfer",
    title: "Neoantigen Peptide Vaccine for KRAS G12D Pancreatic Cancer",
    text: "MD Anderson has developed a multi-peptide vaccine targeting KRAS G12D neoantigens that generates high-avidity T cell responses in pancreatic ductal adenocarcinoma patients. The vaccine is formulated with a proprietary adjuvant system that overcomes the immunosuppressive PDAC microenvironment. Phase I trial results show T cell response in 70% of patients with disease control signals. Combination with PD-1 inhibition being evaluated.",
    authors_or_owner: "MD Anderson Technology Commercialization",
    institution_or_sponsor: "MD Anderson Cancer Center",
    date: "2024-05-12",
    stage_hint: "phase 1",
    url: "https://www.mdanderson.org/research/departments-labs-institutes/programs-centers/institute-for-applied-cancer-science.html",
    metadata: { licensing_status: "available", contact_office: "MD Anderson Technology Commercialization", patent_status: "patented", owner_type: "hospital" },
  },
  {
    source_type: "tech_transfer",
    title: "Cell-Free Methylation Sequencing Platform for Minimal Residual Disease",
    text: "MD Anderson has developed a highly sensitive cell-free DNA methylation sequencing assay for detecting minimal residual disease after cancer treatment. The platform achieves 10^-6 sensitivity for tumor-derived ctDNA using cancer-specific methylation signatures and combines whole-genome and targeted sequencing. Validated for MRD monitoring in AML, colorectal, and lung cancer. Demonstrated ability to detect relapse 4–8 months before clinical imaging.",
    authors_or_owner: "MD Anderson Technology Commercialization",
    institution_or_sponsor: "MD Anderson Cancer Center",
    date: "2024-03-08",
    stage_hint: "discovery",
    url: "https://www.mdanderson.org/research/departments-labs-institutes/programs-centers/institute-for-applied-cancer-science.html",
    metadata: { licensing_status: "available", contact_office: "MD Anderson Technology Commercialization", patent_status: "patent pending", owner_type: "hospital" },
  },
  {
    source_type: "tech_transfer",
    title: "IL-33 Decoy Receptor Fusion Protein for Atopic and Fibrotic Disease",
    text: "MD Anderson immunologists have engineered a soluble IL-33 decoy receptor fusion protein with dramatically enhanced IL-33 neutralization capacity compared to anti-IL-33 antibodies. The fusion protein combines the IL-33 binding domain of ST2 with a long-acting Fc for monthly dosing. Validated in atopic dermatitis, asthma, and IPF animal models. Differentiated from approved dupilumab by direct IL-33 neutralization and coverage of broader downstream pathways.",
    authors_or_owner: "MD Anderson Technology Commercialization",
    institution_or_sponsor: "MD Anderson Cancer Center",
    date: "2024-09-16",
    stage_hint: "preclinical",
    url: "https://www.mdanderson.org/research/departments-labs-institutes/programs-centers/institute-for-applied-cancer-science.html",
    metadata: { licensing_status: "available", contact_office: "MD Anderson Technology Commercialization", patent_status: "patent pending", owner_type: "hospital" },
  },
  {
    source_type: "tech_transfer",
    title: "Bispecific NK Cell Engager for Hematologic Malignancies",
    text: "MD Anderson has engineered a bispecific NK cell engager targeting CD16 on NK cells and CD38 on multiple myeloma and B-cell lymphoma cells. The molecule recruits and activates endogenous NK cells for tumor killing without the manufacturing complexity of adoptive NK therapy. Preclinical studies demonstrate activity comparable to CAR-NK approaches in myeloma models. The bispecific format is Fc-optimized for enhanced NK activation and extended half-life.",
    authors_or_owner: "MD Anderson Technology Commercialization",
    institution_or_sponsor: "MD Anderson Cancer Center",
    date: "2024-06-25",
    stage_hint: "preclinical",
    url: "https://www.mdanderson.org/research/departments-labs-institutes/programs-centers/institute-for-applied-cancer-science.html",
    metadata: { licensing_status: "available", contact_office: "MD Anderson Technology Commercialization", patent_status: "patent pending", owner_type: "hospital" },
  },
  {
    source_type: "tech_transfer",
    title: "EZH2/DNMT3A Dual Inhibitor for Epigenetic Reprogramming of Solid Tumors",
    text: "MD Anderson epigenomics researchers have developed a heterobifunctional small molecule that simultaneously inhibits EZH2 and DNMT3A to reverse epigenetic silencing of tumor suppressor genes and restore immunogenicity in immune-cold solid tumors. The compound increases MHC-I expression, antigen presentation, and infiltrating T cell density, converting immune-excluded tumors to inflamed phenotypes responsive to checkpoint immunotherapy. Demonstrated in TNBC, colorectal, and ovarian cancer models.",
    authors_or_owner: "MD Anderson Technology Commercialization",
    institution_or_sponsor: "MD Anderson Cancer Center",
    date: "2024-01-20",
    stage_hint: "preclinical",
    url: "https://www.mdanderson.org/research/departments-labs-institutes/programs-centers/institute-for-applied-cancer-science.html",
    metadata: { licensing_status: "available", contact_office: "MD Anderson Technology Commercialization", patent_status: "patent pending", owner_type: "hospital" },
  },
  {
    source_type: "tech_transfer",
    title: "CTC Capture and Functional Profiling Platform for Treatment Selection",
    text: "MD Anderson engineers have developed a microfluidic circulating tumor cell capture platform using herringbone-chip geometry that achieves 98% capture efficiency and enables viable, single-cell functional profiling of CTCs from routine blood draws. The platform supports ex vivo drug sensitivity testing, genomic sequencing, and proteomics from 5–10 mL blood. Demonstrated clinical utility for treatment selection in metastatic breast cancer and prostate cancer.",
    authors_or_owner: "MD Anderson Technology Commercialization",
    institution_or_sponsor: "MD Anderson Cancer Center",
    date: "2023-10-30",
    stage_hint: "discovery",
    url: "https://www.mdanderson.org/research/departments-labs-institutes/programs-centers/institute-for-applied-cancer-science.html",
    metadata: { licensing_status: "available", contact_office: "MD Anderson Technology Commercialization", patent_status: "patented", owner_type: "hospital" },
  },
];

export function getMdAndersonListings(): RawSignal[] {
  return MDANDERSON_LISTINGS.map((listing) => ({
    ...listing,
    id: `mdanderson-${Math.random().toString(36).slice(2, 9)}`,
  }));
}
