import type { RawSignal } from "../../types";

const MIT_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "Microfluidic Organ-on-Chip for Drug Toxicity Screening",
    text: "MIT researchers have developed a modular organ-on-chip platform that replicates human liver, kidney, and gut physiology for drug toxicity screening. The device integrates human iPSC-derived cells and maintains viability for extended periods. The platform can reduce late-stage drug attrition by predicting organ-specific toxicity earlier in development.",
    authors_or_owner: "MIT Technology Licensing Office",
    institution_or_sponsor: "Massachusetts Institute of Technology",
    date: "2024-07-10",
    stage_hint: "discovery",
    url: "https://tlo.mit.edu",
    metadata: {
      licensing_status: "available",
      contact_office: "MIT Technology Licensing Office",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Hydrogel Injectable Depot for Sustained Protein Drug Release",
    text: "A self-healing hydrogel formulation that enables sustained release of protein biologics (including antibodies and cytokines) over weeks to months from a single subcutaneous injection. The gel's mechanical properties and degradation rate can be tuned for different drugs. Demonstrated for IL-2 delivery in cancer immunotherapy settings.",
    authors_or_owner: "MIT Technology Licensing Office",
    institution_or_sponsor: "Massachusetts Institute of Technology",
    date: "2024-10-22",
    stage_hint: "preclinical",
    url: "https://tlo.mit.edu",
    metadata: {
      licensing_status: "available",
      contact_office: "MIT Technology Licensing Office",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "AI-Designed Peptide Macrocycles for Undruggable Protein Targets",
    text: "MIT researchers used deep learning to design cyclic peptides that can bind to historically undruggable protein-protein interaction surfaces. The pipeline generates and validates binders for targets such as MYC, RAS, and p53, which have resisted small molecule drug discovery for decades. Demonstrated binding and cellular activity for MYC.",
    authors_or_owner: "MIT Technology Licensing Office",
    institution_or_sponsor: "Massachusetts Institute of Technology",
    date: "2025-01-30",
    stage_hint: "discovery",
    url: "https://tlo.mit.edu",
    metadata: {
      licensing_status: "available",
      contact_office: "MIT Technology Licensing Office",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "RNA-Encoded Cell Therapy with Transient Expression Control",
    text: "A platform for delivering cell therapy using mRNA rather than viral vectors to express therapeutic transgenes. The transient expression profile reduces genotoxicity risk, and the approach enables rapid manufacturing. Initial application in CAR-NK cells for hematologic malignancies shows comparable efficacy to virally-transduced counterparts with improved safety.",
    authors_or_owner: "MIT Technology Licensing Office",
    institution_or_sponsor: "Massachusetts Institute of Technology",
    date: "2024-09-15",
    stage_hint: "preclinical",
    url: "https://tlo.mit.edu",
    metadata: {
      licensing_status: "available",
      contact_office: "MIT Technology Licensing Office",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Lipid Nanoparticle Ionizable Lipid Library for Extrahepatic Delivery",
    text: "MIT's Langer Lab has generated a library of over 300 ionizable lipid structures systematically optimized for extrahepatic mRNA delivery (lung, spleen, muscle). Specific lipid structures within the library achieve >50% transfection in pulmonary epithelium, representing a breakthrough for inhaled mRNA therapeutics and pulmonary gene editing.",
    authors_or_owner: "MIT Technology Licensing Office",
    institution_or_sponsor: "Massachusetts Institute of Technology",
    date: "2024-05-20",
    stage_hint: "preclinical",
    url: "https://tlo.mit.edu",
    metadata: {
      licensing_status: "available",
      contact_office: "MIT Technology Licensing Office",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Programmable Bacteria for Localized Tumor Immunotherapy",
    text: "Engineered Escherichia coli that selectively colonize solid tumors and produce immunostimulatory payloads (IL-12, anti-PD-L1 nanobodies) locally. The bacteria are auxotrophic and cannot survive outside the hypoxic tumor microenvironment. Phase I-ready candidate for pancreatic cancer, with favorable safety data in germ-free mouse models.",
    authors_or_owner: "MIT Technology Licensing Office",
    institution_or_sponsor: "Massachusetts Institute of Technology",
    date: "2024-12-18",
    stage_hint: "preclinical",
    url: "https://tlo.mit.edu",
    metadata: {
      licensing_status: "available",
      contact_office: "MIT Technology Licensing Office",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Nanoparticle Targeting System for Selective Lymph Node Delivery",
    text: "A charge-switching nanoparticle design that passively drains to lymph nodes after subcutaneous injection and selectively delivers cargo to dendritic cells and macrophages in the lymph node cortex. Applications include cancer vaccines, autoimmune tolerance induction, and gene correction of lymphocyte subsets.",
    authors_or_owner: "MIT Technology Licensing Office",
    institution_or_sponsor: "Massachusetts Institute of Technology",
    date: "2024-08-05",
    stage_hint: "preclinical",
    url: "https://tlo.mit.edu",
    metadata: {
      licensing_status: "available",
      contact_office: "MIT Technology Licensing Office",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "CRISPR-Cas12a Ultra-Sensitive Diagnostics Platform",
    text: "A SHERLOCK-based CRISPR diagnostic platform using Cas12a for attomolar-level nucleic acid detection without PCR amplification. The platform can be adapted to any nucleic acid target in under 2 weeks and is compatible with lateral flow readouts. Applications in infectious disease, oncology liquid biopsy, and genetic disease screening.",
    authors_or_owner: "MIT Technology Licensing Office",
    institution_or_sponsor: "Massachusetts Institute of Technology",
    date: "2024-04-01",
    stage_hint: "discovery",
    url: "https://tlo.mit.edu",
    metadata: {
      licensing_status: "licensed",
      contact_office: "MIT Technology Licensing Office",
      patent_status: "patented",
      owner_type: "university",
    },
  },
];

export function getMitListings(): RawSignal[] {
  return MIT_LISTINGS.map((l, i) => ({ ...l, id: `mit-tt-${i}` }));
}
