import type { RawSignal } from "../../types";

const NORTHWESTERN_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "SNAc (Spherical Nucleic Acid) Platform for Intracellular siRNA Delivery Without Carriers",
    text: "Northwestern's pioneering spherical nucleic acid (SNA) technology presents siRNA in a dense spherical shell configuration that enables receptor-independent cellular uptake via scavenger receptors expressed ubiquitously. The platform achieves >90% intracellular delivery of intact siRNA without lipid nanoparticles or viral vectors, and penetrates physiological barriers including the blood-brain barrier, skin, and tumor microenvironment. Multiple SNA products in active licensing discussions.",
    authors_or_owner: "Northwestern University Innovation and New Ventures Office",
    institution_or_sponsor: "Northwestern University",
    date: "2024-11-10",
    stage_hint: "preclinical",
    url: "https://invo.northwestern.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Northwestern INVO", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Reprogrammed Macrophage Therapy for Peritoneal Metastasis",
    text: "An ex vivo-reprogrammed macrophage therapy (M1-polarized, CAR-modified) targeting EpCAM+ peritoneal metastases in ovarian and colorectal cancer. The macrophages are modified to resist M2 polarization in the immunosuppressive ascites microenvironment while retaining their natural tissue infiltration capabilities. Intraperitoneal delivery achieves selective tumor regression without the cytokine release syndrome seen with T cell-based approaches.",
    authors_or_owner: "Northwestern University Innovation and New Ventures Office",
    institution_or_sponsor: "Northwestern University",
    date: "2024-08-05",
    stage_hint: "preclinical",
    url: "https://invo.northwestern.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Northwestern INVO", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Nanotechnology Patch for Transdermal Immunotherapy Delivery",
    text: "A microneedle patch incorporating dissolving polymer tips loaded with immune-modulating cargo (antigens, adjuvants, or siRNA) for painless transdermal delivery to skin-resident antigen-presenting cells. The patch requires no refrigeration and self-administers in under 60 seconds. Demonstrated efficacy equivalent to subcutaneous injection for flu antigen immunization and for regulatory T cell induction in atopic dermatitis. Scalable manufacturing with standard pharmaceutical coating equipment.",
    authors_or_owner: "Northwestern University Innovation and New Ventures Office",
    institution_or_sponsor: "Northwestern University",
    date: "2025-01-28",
    stage_hint: "preclinical",
    url: "https://invo.northwestern.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Northwestern INVO", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "WEE1 Kinase Degrader (PROTAC) for Replication Stress-High Cancers",
    text: "A PROTAC degrader of WEE1 kinase that achieves superior and sustained G2/M checkpoint abrogation compared to catalytic WEE1 inhibitors such as adavosertib, which showed dose-limiting toxicity. The degrader depletes WEE1 protein by >90% within 4 hours, forcing S-phase-arrested cancer cells into mitotic catastrophe. Selective activity in CCNE1-amplified ovarian, endometrial, and SCLC tumors with minimal effect on normal WEE1-high tissues.",
    authors_or_owner: "Northwestern University Innovation and New Ventures Office",
    institution_or_sponsor: "Northwestern University",
    date: "2024-10-08",
    stage_hint: "discovery",
    url: "https://invo.northwestern.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Northwestern INVO", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Exosome-Based Drug Delivery for CNS Drug Resistant Epilepsy",
    text: "Brain-targeted exosomes surface-engineered with rabies virus glycoprotein (RVG) peptide for receptor-mediated transcytosis across the blood-brain barrier, loaded with ASO or siRNA targeting KCNQ2/KCNQ3 ion channel variants associated with drug-resistant neonatal epilepsy. IV injection achieves >30% CNS delivery with preferential neuronal uptake. Demonstrated seizure reduction in a KCNQ2 GOF mouse model where existing ASO strategies failed due to poor CNS penetration.",
    authors_or_owner: "Northwestern University Innovation and New Ventures Office",
    institution_or_sponsor: "Northwestern University",
    date: "2024-06-20",
    stage_hint: "preclinical",
    url: "https://invo.northwestern.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Northwestern INVO", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Programmable Cytokine Release Hydrogel for Post-Surgical Tumor Site Treatment",
    text: "A injectable hydrogel that is surgically deposited in the tumor resection cavity and releases a programmable sequence of cytokines (IFN-alpha for innate activation, then IL-12 for T cell priming, then IL-2 for expansion) over 21 days. The sequential cytokine release mimics a natural immune response cascade, training tumor-antigen-specific T cells against residual disease. Shown to prevent local recurrence and distant metastasis in GBM and TNBC resection mouse models.",
    authors_or_owner: "Northwestern University Innovation and New Ventures Office",
    institution_or_sponsor: "Northwestern University",
    date: "2025-02-25",
    stage_hint: "preclinical",
    url: "https://invo.northwestern.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Northwestern INVO", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Small Molecule Activator of Nrf2 for Acute Kidney Injury Prevention",
    text: "A covalent Nrf2 activator with improved potency and selectivity versus sulforaphane and bardoxolone analogs, designed for short-course prophylactic dosing to prevent contrast-induced acute kidney injury (AKI) in at-risk patients undergoing contrast imaging or surgery. Oral pre-treatment at 24 and 2 hours before nephrotoxic insult achieves >60% reduction in serum creatinine elevation in rat cisplatin and contrast AKI models.",
    authors_or_owner: "Northwestern University Innovation and New Ventures Office",
    institution_or_sponsor: "Northwestern University",
    date: "2024-09-15",
    stage_hint: "preclinical",
    url: "https://invo.northwestern.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Northwestern INVO", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Circular RNA Platform for Stable and Immunosilent Therapeutic Protein Expression",
    text: "A circularized RNA expression platform that produces therapeutic proteins with 5-10x longer half-life than linear mRNA while avoiding innate immune activation by pathogen sensors (RIG-I, MDA5, TLR3) that limit linear mRNA tolerability. The circular RNA is produced using a novel intron-mediated ligation chemistry compatible with standard IVT manufacturing. Validated for factor VIII, EPO, and anti-VEGF Fab expression in hepatic and non-hepatic cell types.",
    authors_or_owner: "Northwestern University Innovation and New Ventures Office",
    institution_or_sponsor: "Northwestern University",
    date: "2024-12-18",
    stage_hint: "preclinical",
    url: "https://invo.northwestern.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Northwestern INVO", patent_status: "patent pending", owner_type: "university" },
  },
];

export function getNorthwesternListings(): RawSignal[] {
  return NORTHWESTERN_LISTINGS.map((l, i) => ({ ...l, id: `northwestern-tt-${i}` }));
}
