import type { RawSignal } from "../../types";

const OXFORD_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "GLP-1/GIP Dual Agonist Peptide for Metabolic Disease",
    text: "Oxford researchers have developed a novel dual GLP-1/GIP receptor agonist peptide with superior half-life and glycemic control compared to existing GLP-1 monotherapies. The compound shows weight loss equivalent to semaglutide with improved glucose tolerance in diabetic rodent models. The IP covers the specific peptide sequence and modifications.",
    authors_or_owner: "Oxford University Innovation",
    institution_or_sponsor: "University of Oxford",
    date: "2024-11-05",
    stage_hint: "preclinical",
    url: "https://innovation.ox.ac.uk",
    metadata: {
      licensing_status: "available",
      contact_office: "Oxford University Innovation",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Antibody-Drug Conjugate Targeting FOLR1 in Ovarian Cancer",
    text: "A next-generation ADC targeting folate receptor alpha (FOLR1), which is overexpressed in the majority of ovarian, lung, and endometrial cancers. The linker-payload system achieves bystander killing and is designed for low antigen density targets. Preclinical data shows complete tumor regression in 80% of FOLR1+ xenograft models.",
    authors_or_owner: "Oxford University Innovation",
    institution_or_sponsor: "University of Oxford",
    date: "2024-06-28",
    stage_hint: "preclinical",
    url: "https://innovation.ox.ac.uk",
    metadata: {
      licensing_status: "available",
      contact_office: "Oxford University Innovation",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "First-in-Class PCAF/GCN5 Dual Inhibitor for AML",
    text: "Oxford Structural Genomics Consortium researchers have developed highly selective small molecule inhibitors of the PCAF and GCN5 bromodomains. These epigenetic targets are essential for MYC-driven transcription in AML. The inhibitors show potent anti-proliferative activity in AML cell lines and primary patient samples with low off-target toxicity.",
    authors_or_owner: "Oxford University Innovation",
    institution_or_sponsor: "University of Oxford",
    date: "2025-01-12",
    stage_hint: "preclinical",
    url: "https://innovation.ox.ac.uk",
    metadata: {
      licensing_status: "available",
      contact_office: "Oxford University Innovation",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Oral siRNA Nanoparticle for Gut-Targeted Gene Silencing",
    text: "A pH-stable nanoparticle formulation enabling oral delivery of siRNA to the intestinal epithelium. The system protects siRNA from gastrointestinal degradation and achieves >60% gene knockdown in colorectal tissue in vivo. Target applications include inflammatory bowel disease, colorectal cancer, and familial adenomatous polyposis.",
    authors_or_owner: "Oxford University Innovation",
    institution_or_sponsor: "University of Oxford",
    date: "2024-09-03",
    stage_hint: "preclinical",
    url: "https://innovation.ox.ac.uk",
    metadata: {
      licensing_status: "available",
      contact_office: "Oxford University Innovation",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Engineered T Cell Receptor for HPV-Associated Cancers",
    text: "Oxford Immunology researchers have identified and affinity-matured a T cell receptor (TCR) specific for the HPV16 E7 oncoprotein presented on HLA-A*02:01. The engineered TCR shows superior tumor killing compared to natural TCRs and demonstrates potent activity against cervical, oropharyngeal, and anal cancers. The approach is compatible with allogeneic cell manufacturing.",
    authors_or_owner: "Oxford University Innovation",
    institution_or_sponsor: "University of Oxford",
    date: "2024-07-17",
    stage_hint: "preclinical",
    url: "https://innovation.ox.ac.uk",
    metadata: {
      licensing_status: "available",
      contact_office: "Oxford University Innovation",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "AAV Vector with Enhanced CNS Tropism for Rare Neurological Diseases",
    text: "A directed-evolution AAV capsid with dramatically improved transduction of CNS neurons following intrathecal or intravenous administration. The capsid achieves 10-50x greater neuronal transduction than AAV9 in NHP studies. Licensed to one rare disease program; additional CNS indications remain available for partnership.",
    authors_or_owner: "Oxford University Innovation",
    institution_or_sponsor: "University of Oxford",
    date: "2024-04-09",
    stage_hint: "preclinical",
    url: "https://innovation.ox.ac.uk",
    metadata: {
      licensing_status: "available",
      contact_office: "Oxford University Innovation",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Combination Bacteriophage Cocktail for Drug-Resistant Bacterial Infections",
    text: "A well-characterized bacteriophage cocktail targeting carbapenem-resistant Acinetobacter baumannii (CRAB), one of the most dangerous drug-resistant pathogens on the WHO priority list. The cocktail was developed through collaborative work at the Oxford Centre for Clinical Microbiology and has been used compassionately in three patients with positive outcomes.",
    authors_or_owner: "Oxford University Innovation",
    institution_or_sponsor: "University of Oxford",
    date: "2025-03-01",
    stage_hint: "phase 1",
    url: "https://innovation.ox.ac.uk",
    metadata: {
      licensing_status: "available",
      contact_office: "Oxford University Innovation",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Selective NLRP3 Inflammasome Inhibitor for Inflammatory Disease",
    text: "A highly selective orally bioavailable small molecule inhibitor of the NLRP3 inflammasome, a key innate immunity target implicated in gout, atherosclerosis, NASH, and neuroinflammation. The compound shows improved selectivity and pharmacokinetics compared to earlier NLRP3 inhibitors. Pre-IND enabling studies are underway.",
    authors_or_owner: "Oxford University Innovation",
    institution_or_sponsor: "University of Oxford",
    date: "2024-10-14",
    stage_hint: "preclinical",
    url: "https://innovation.ox.ac.uk",
    metadata: {
      licensing_status: "available",
      contact_office: "Oxford University Innovation",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
];

export function getOxfordListings(): RawSignal[] {
  return OXFORD_LISTINGS.map((l, i) => ({ ...l, id: `oxford-tt-${i}` }));
}
