import type { RawSignal } from "../../types";

const PENN_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "In Vivo mRNA Liver-Directed Base Editing for Transthyretin Amyloidosis",
    text: "Penn researchers have developed a lipid nanoparticle-delivered mRNA encoding an adenine base editor targeting the TTR gene, achieving permanent TTR silencing in hepatocytes with a single IV dose. In NHP studies, the approach achieves >95% serum TTR reduction at 1 mg/kg, sustained at 85% over 18 months of follow-up. Provides a potential one-time treatment alternative to patisiran/inclisiran for TTR amyloid cardiomyopathy and polyneuropathy.",
    authors_or_owner: "Penn Center for Innovation",
    institution_or_sponsor: "University of Pennsylvania",
    date: "2025-02-05",
    stage_hint: "preclinical",
    url: "https://pci.upenn.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Penn Center for Innovation", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Muscle-Tropic AAV Capsid for Duchenne Muscular Dystrophy Micro-Dystrophin",
    text: "A novel AAV capsid variant selected via directed evolution for superior transduction efficiency in skeletal and cardiac muscle following IV administration. The capsid achieves 5-fold higher muscle transduction than AAV9 at equivalent dose, enabling delivery of a functional micro-dystrophin construct at significantly lower vector doses in DMD mouse and dog models. Lower dose requirements reduce manufacturing cost and immunogenicity risk.",
    authors_or_owner: "Penn Center for Innovation",
    institution_or_sponsor: "University of Pennsylvania",
    date: "2024-10-14",
    stage_hint: "preclinical",
    url: "https://pci.upenn.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Penn Center for Innovation", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "CAR-T Cell Engineering via Non-Viral Sleeping Beauty Transposon",
    text: "A non-viral CAR-T manufacturing platform using Sleeping Beauty transposon/transposase to integrate CAR constructs into defined genomic safe harbors. The approach eliminates the AAV or lentiviral vectors required in conventional manufacturing, reducing costs by an estimated 60% and eliminating concerns about insertional mutagenesis from semi-random viral integration. Demonstrated CAR-T function equivalent to lentiviral products in B-ALL xenograft models.",
    authors_or_owner: "Penn Center for Innovation",
    institution_or_sponsor: "University of Pennsylvania",
    date: "2024-07-22",
    stage_hint: "preclinical",
    url: "https://pci.upenn.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Penn Center for Innovation", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Bispecific CAR T Cell Targeting CD19 and CD22 for Relapsed B-ALL",
    text: "A tandem bispecific CAR construct targeting both CD19 and CD22 on a single T cell, designed to prevent antigen escape relapse that is the primary mechanism of failure after CD19-only CAR-T therapy. Phase 1 data from 18 pediatric B-ALL patients with prior CAR-T failure show 78% complete remission rate. Technology covers the bispecific CAR design, the antigen-binding domain sequences, and the clinical manufacturing protocol.",
    authors_or_owner: "Penn Center for Innovation",
    institution_or_sponsor: "University of Pennsylvania",
    date: "2024-09-05",
    stage_hint: "phase 1",
    url: "https://pci.upenn.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Penn Center for Innovation", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Personalized mRNA Cancer Vaccine with Self-Amplifying RNA Backbone",
    text: "A personalized cancer vaccine platform using a self-amplifying RNA (saRNA) backbone derived from an alphavirus replicon that produces 10-100x higher antigen expression per dose than conventional mRNA. The higher antigen output enables neoantigen vaccines at 10-50 μg doses versus 100-1000 μg for conventional mRNA vaccines, reducing manufacturing time and cost for personalized approaches. Validated immune responses in colorectal and melanoma patient cohorts.",
    authors_or_owner: "Penn Center for Innovation",
    institution_or_sponsor: "University of Pennsylvania",
    date: "2025-01-18",
    stage_hint: "phase 1",
    url: "https://pci.upenn.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Penn Center for Innovation", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Synthetic Nanoparticle Vaccine for Broadly Reactive Influenza Immunization",
    text: "A ferritin nanoparticle displaying the influenza hemagglutinin (HA) stem domain — the conserved, cross-reactive target that elicits broadly neutralizing antibodies — in an octameric display configuration that mimics natural viral geometry. A single immunization generates stem-reactive antibodies that neutralize H1N1, H3N2, H5N1, and H7N9 strains in ferret challenge models. Platform is adaptable to other viral envelope proteins (RSV F, SARS-CoV-2 spike).",
    authors_or_owner: "Penn Center for Innovation",
    institution_or_sponsor: "University of Pennsylvania",
    date: "2024-05-30",
    stage_hint: "preclinical",
    url: "https://pci.upenn.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Penn Center for Innovation", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "In Vivo Partial Reprogramming for Age-Related Macular Degeneration",
    text: "A retinal gene therapy using AAV2/8 to deliver a doxycycline-inducible OSK (Oct4/Sox2/Klf4) partial reprogramming cassette that restores youthful epigenetic methylation patterns to aged retinal ganglion cells, reversing age-related visual decline and optic nerve damage. Following a single intravitreal injection in aged mice, visual acuity improved to levels comparable to young controls. The inducible system allows controlled reprogramming without oncogenic risk.",
    authors_or_owner: "Penn Center for Innovation",
    institution_or_sponsor: "University of Pennsylvania",
    date: "2024-12-20",
    stage_hint: "preclinical",
    url: "https://pci.upenn.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Penn Center for Innovation", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Genome-Wide Off-Target Assessment Platform for Clinical Gene Editing Programs",
    text: "A GUIDE-seq variant optimized for primary human hematopoietic cells that provides a comprehensive, unbiased genome-wide off-target editing profile for any nuclease (Cas9, base editors, prime editors) at clinically relevant low-dose conditions. The platform enables regulatory-grade safety characterization and has been used to support three IND submissions. Licensable as a validated assay with protocol and bioinformatics pipeline.",
    authors_or_owner: "Penn Center for Innovation",
    institution_or_sponsor: "University of Pennsylvania",
    date: "2024-08-12",
    stage_hint: "discovery",
    url: "https://pci.upenn.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Penn Center for Innovation", patent_status: "patented", owner_type: "university" },
  },
];

export function getPennListings(): RawSignal[] {
  return PENN_LISTINGS.map((l, i) => ({ ...l, id: `penn-tt-${i}` }));
}
