import type { RawSignal } from "../../types";

const SALK_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "NRF2 Pathway Activator for Neurodegeneration and Inflammatory Disease",
    text: "Salk Institute researchers have developed a selective NRF2 pathway activator that upregulates the cytoprotective antioxidant response without the off-target effects associated with electrophilic NRF2 inducers. The compound is a direct KEAP1-NRF2 protein-protein interaction disruptor with drug-like properties and CNS penetration. Demonstrated neuroprotection in ALS, Parkinson's, and TBI models. Anti-inflammatory activity also validated in colitis and sepsis models.",
    authors_or_owner: "Salk Institute Technology Transfer",
    institution_or_sponsor: "Salk Institute for Biological Studies",
    date: "2024-08-14",
    stage_hint: "preclinical",
    url: "https://www.salk.edu/about/technology-transfer",
    metadata: { licensing_status: "available", contact_office: "Salk Institute Technology Transfer", patent_status: "patent pending", owner_type: "research_institute" },
  },
  {
    source_type: "tech_transfer",
    title: "Partial Reprogramming Factors for In Vivo Tissue Rejuvenation",
    text: "Salk Institute scientists pioneered the concept of partial cellular reprogramming using cyclic expression of Yamanaka factors (OSKM) to rejuvenate aged tissues without inducing pluripotency or tumor formation. The platform uses AAV-delivered inducible OSKM cassettes with precisely calibrated dosing to restore youthful epigenetic signatures and tissue function in aged mice. Vision loss, muscle wasting, and neural function improvements demonstrated. Multiple tissue types under active study.",
    authors_or_owner: "Salk Institute Technology Transfer",
    institution_or_sponsor: "Salk Institute for Biological Studies",
    date: "2024-05-10",
    stage_hint: "preclinical",
    url: "https://www.salk.edu/about/technology-transfer",
    metadata: { licensing_status: "available", contact_office: "Salk Institute Technology Transfer", patent_status: "patented", owner_type: "research_institute" },
  },
  {
    source_type: "tech_transfer",
    title: "Mitochondrial Uncoupler for Obesity and Metabolic Disease",
    text: "Salk metabolic researchers have developed a liver-targeted mitochondrial uncoupler that safely increases metabolic rate by diverting electron transport chain energy to heat. Unlike historic uncouplers (DNP), the compound has a narrow proton conductance window and liver-selective pharmacokinetics that eliminate systemic toxicity. In DIO mouse models, treatment reduces fat mass by 30% in 4 weeks without affecting food intake or muscle mass. Diabetes reversal also demonstrated.",
    authors_or_owner: "Salk Institute Technology Transfer",
    institution_or_sponsor: "Salk Institute for Biological Studies",
    date: "2024-03-22",
    stage_hint: "preclinical",
    url: "https://www.salk.edu/about/technology-transfer",
    metadata: { licensing_status: "available", contact_office: "Salk Institute Technology Transfer", patent_status: "patent pending", owner_type: "research_institute" },
  },
  {
    source_type: "tech_transfer",
    title: "Retinal Progenitor Cell Therapy for Age-Related Macular Degeneration",
    text: "Salk ophthalmology researchers have established a protocol to generate retinal progenitor cells from human iPSCs that, when subretinally transplanted, integrate into the host retina and rescue photoreceptor function in AMD and Stargardt disease models. The cells produce neurotrophic factors and replace lost RPE cells. Non-human primate safety and tolerability studies completed. Surgical delivery device developed for targeted subretinal injection.",
    authors_or_owner: "Salk Institute Technology Transfer",
    institution_or_sponsor: "Salk Institute for Biological Studies",
    date: "2024-09-30",
    stage_hint: "preclinical",
    url: "https://www.salk.edu/about/technology-transfer",
    metadata: { licensing_status: "available", contact_office: "Salk Institute Technology Transfer", patent_status: "patent pending", owner_type: "research_institute" },
  },
  {
    source_type: "tech_transfer",
    title: "FoxO Transcription Factor Modulator for Healthy Aging Extension",
    text: "Salk researchers studying the genetics of exceptional longevity have identified small molecule FoxO3 activators that recapitulate the healthspan benefits of caloric restriction and FOXO3 genetic variants associated with human centenarians. The compounds improve stress resistance, reduce inflammation, and extend lifespan in multiple model organisms. Human aging pathway target engagement confirmed. Multiple FoxO isoform-selective compounds available for licensing.",
    authors_or_owner: "Salk Institute Technology Transfer",
    institution_or_sponsor: "Salk Institute for Biological Studies",
    date: "2023-11-05",
    stage_hint: "discovery",
    url: "https://www.salk.edu/about/technology-transfer",
    metadata: { licensing_status: "available", contact_office: "Salk Institute Technology Transfer", patent_status: "patent pending", owner_type: "research_institute" },
  },
  {
    source_type: "tech_transfer",
    title: "Non-Peptide GLP-1 Receptor Positive Allosteric Modulator",
    text: "Salk Institute metabolic scientists have developed the first non-peptide small molecule positive allosteric modulator (PAM) of the GLP-1 receptor that potentiates endogenous GLP-1 signaling without the burden of injectable peptide administration. The compound sensitizes the receptor to native GLP-1, producing glucose-dependent insulin secretion amplification and appetite suppression. Oral bioavailability confirmed. Differentiated from GLP-1 agonists by mechanism and route of administration.",
    authors_or_owner: "Salk Institute Technology Transfer",
    institution_or_sponsor: "Salk Institute for Biological Studies",
    date: "2024-07-08",
    stage_hint: "preclinical",
    url: "https://www.salk.edu/about/technology-transfer",
    metadata: { licensing_status: "available", contact_office: "Salk Institute Technology Transfer", patent_status: "patent pending", owner_type: "research_institute" },
  },
  {
    source_type: "tech_transfer",
    title: "CAR-T Cell Persistence Enhancer via Epigenetic Reprogramming",
    text: "Salk gene regulation researchers have identified an epigenetic reprogramming strategy that converts terminally exhausted CAR-T cells into a stem-cell-like memory phenotype with superior persistence and antitumor activity. The approach uses transient expression of TET2 and DNMT3A regulators during manufacturing to remodel the T cell epigenome. Treated CAR-T cells show 5-fold longer persistence and improved solid tumor infiltration in xenograft models.",
    authors_or_owner: "Salk Institute Technology Transfer",
    institution_or_sponsor: "Salk Institute for Biological Studies",
    date: "2024-11-20",
    stage_hint: "preclinical",
    url: "https://www.salk.edu/about/technology-transfer",
    metadata: { licensing_status: "available", contact_office: "Salk Institute Technology Transfer", patent_status: "patent pending", owner_type: "research_institute" },
  },
  {
    source_type: "tech_transfer",
    title: "Microglia Neuroinflammation Suppressor for CNS Disease",
    text: "Salk neuroscientists have developed a highly selective CSF1R/TREM2 bimodal modulator that suppresses pathological microglia activation in neuroinflammatory disease while preserving neuroprotective microglial functions. The compound normalizes the microglial transcriptome in Alzheimer's, multiple sclerosis, and traumatic brain injury models, reducing IL-1β, TNF, and complement-mediated synapse loss. Oral bioavailability and CNS penetration optimized in mouse and rat studies.",
    authors_or_owner: "Salk Institute Technology Transfer",
    institution_or_sponsor: "Salk Institute for Biological Studies",
    date: "2024-02-18",
    stage_hint: "preclinical",
    url: "https://www.salk.edu/about/technology-transfer",
    metadata: { licensing_status: "available", contact_office: "Salk Institute Technology Transfer", patent_status: "patent pending", owner_type: "research_institute" },
  },
];

export function getSalkListings(): RawSignal[] {
  return SALK_LISTINGS.map((listing) => ({
    ...listing,
    id: `salk-${Math.random().toString(36).slice(2, 9)}`,
  }));
}
