import type { RawSignal } from "../../types";

const SCRIPPS_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "Covalent Fragment Drug Platform for Undruggable Protein Targets",
    text: "Scripps Research has developed a covalent fragment screening platform enabling drug discovery against previously undruggable protein targets. The platform uses activity-based protein profiling (ABPP) to identify highly reactive, selective cysteine residues across the proteome and screens fragment libraries for covalent engagement. Active programs include transcription factors (MYC, RAS family), RNA-binding proteins, and adapter proteins without enzymatic activity. Multiple validated chemical probes available for licensing.",
    authors_or_owner: "Scripps Research Technology Development",
    institution_or_sponsor: "Scripps Research",
    date: "2024-10-18",
    stage_hint: "discovery",
    url: "https://www.scripps.edu/technology",
    metadata: { licensing_status: "available", contact_office: "Scripps Research Technology Development", patent_status: "patented", owner_type: "research_institute" },
  },
  {
    source_type: "tech_transfer",
    title: "Broadly Neutralizing Antibody Against Highly Mutable Viral Pathogens",
    text: "Scripps Research structural immunologists have solved the structure of broadly neutralizing epitopes on influenza, HIV, and coronavirus spike proteins and designed antibodies targeting conserved regions resistant to viral escape. The anti-influenza bnAb neutralizes all tested influenza A strains including H5N1, H3N2, and pandemic lineages. IP covers the antibody sequences, epitope-focused vaccine designs, and prophylactic formulations.",
    authors_or_owner: "Scripps Research Technology Development",
    institution_or_sponsor: "Scripps Research",
    date: "2024-07-14",
    stage_hint: "preclinical",
    url: "https://www.scripps.edu/technology",
    metadata: { licensing_status: "available", contact_office: "Scripps Research Technology Development", patent_status: "patented", owner_type: "research_institute" },
  },
  {
    source_type: "tech_transfer",
    title: "Cryptic Pocket Inhibitor Discovery via Enhanced Molecular Dynamics",
    text: "Scripps computational chemists have developed an enhanced molecular dynamics approach that reveals transient cryptic binding pockets in proteins not visible in static crystal structures. This has enabled drug discovery against Ras, Rac1, PCNA, and multiple other proteins previously considered undruggable. The platform generates a structural ensemble that guides high-throughput docking campaigns. First-in-class inhibitors for three cancer targets available for licensing.",
    authors_or_owner: "Scripps Research Technology Development",
    institution_or_sponsor: "Scripps Research",
    date: "2024-04-05",
    stage_hint: "discovery",
    url: "https://www.scripps.edu/technology",
    metadata: { licensing_status: "available", contact_office: "Scripps Research Technology Development", patent_status: "patent pending", owner_type: "research_institute" },
  },
  {
    source_type: "tech_transfer",
    title: "RNA-Targeted Small Molecule Library for Expansion of Druggable Space",
    text: "Scripps Research chemists have built a curated library of RNA-targeted small molecules specifically designed to bind structured RNA elements in disease-associated mRNAs and non-coding RNAs. The library covers 50+ validated RNA targets including oncogenic microRNA precursors, IRES elements, and repeat expansions in neurological diseases. Biophysical characterization and cellular target engagement data provided. Several lead series with sub-micromolar cellular activity available.",
    authors_or_owner: "Scripps Research Technology Development",
    institution_or_sponsor: "Scripps Research",
    date: "2023-12-20",
    stage_hint: "discovery",
    url: "https://www.scripps.edu/technology",
    metadata: { licensing_status: "available", contact_office: "Scripps Research Technology Development", patent_status: "patent pending", owner_type: "research_institute" },
  },
  {
    source_type: "tech_transfer",
    title: "Novel Kinase Scaffold with Non-ATP Competitive Binding Mode",
    text: "Scripps medicinal chemists have discovered a novel molecular scaffold that inhibits disease-relevant kinases through a non-ATP-competitive allosteric mechanism, enabling selectivity among structurally similar kinases that has eluded ATP-competitive inhibitors. Lead compounds target FAK, JAK2, and DYRK1A with >100-fold selectivity over kinase panels. The scaffold is differentiated from approved kinase inhibitors and resistant to common resistance mutations.",
    authors_or_owner: "Scripps Research Technology Development",
    institution_or_sponsor: "Scripps Research",
    date: "2024-02-12",
    stage_hint: "preclinical",
    url: "https://www.scripps.edu/technology",
    metadata: { licensing_status: "available", contact_office: "Scripps Research Technology Development", patent_status: "patent pending", owner_type: "research_institute" },
  },
  {
    source_type: "tech_transfer",
    title: "GPCR Structural Biology Platform for Orphan Receptor Drug Discovery",
    text: "Scripps Research has established a world-leading GPCR structural biology platform using cryo-EM and X-ray crystallography that has solved structures of 15 orphan GPCRs in complex with endogenous ligands and tool compounds. Several orphan receptors involved in pain, neuropsychiatric disease, and cancer have been deorphanized, enabling rational drug design. Structural data packages and screening-ready receptor preparations available for licensing.",
    authors_or_owner: "Scripps Research Technology Development",
    institution_or_sponsor: "Scripps Research",
    date: "2024-09-01",
    stage_hint: "discovery",
    url: "https://www.scripps.edu/technology",
    metadata: { licensing_status: "available", contact_office: "Scripps Research Technology Development", patent_status: "patent pending", owner_type: "research_institute" },
  },
  {
    source_type: "tech_transfer",
    title: "Click Chemistry Bioorthogonal Protein Degradation Tag",
    text: "Scripps Research—home of click chemistry—has developed a bioorthogonal protein degradation tag that enables conditional, tissue-selective protein degradation in vivo using systemically administered small molecule triggers. The tag uses a tetrazine-trans-cyclooctene ligation chemistry to recruit engineered E3 ligase adaptors only at the site of tag-trigger ligation. Applications include controllable PROTAC systems, inducible knockdown in specific organs, and temporal degradation studies.",
    authors_or_owner: "Scripps Research Technology Development",
    institution_or_sponsor: "Scripps Research",
    date: "2024-05-28",
    stage_hint: "discovery",
    url: "https://www.scripps.edu/technology",
    metadata: { licensing_status: "available", contact_office: "Scripps Research Technology Development", patent_status: "patent pending", owner_type: "research_institute" },
  },
  {
    source_type: "tech_transfer",
    title: "Pan-Coronavirus Antiviral Targeting Conserved Capsid Assembly",
    text: "Scripps Research virologists have identified a conserved structural site in the coronavirus nucleocapsid protein required for capsid assembly and developed first-in-class small molecule disruptors. The compounds block replication of SARS-CoV-2, MERS-CoV, and bat coronaviruses with high breadth, offering pandemic preparedness potential. High oral bioavailability, low toxicity, and no emergence of resistance in serial passage studies. Differentiated mechanism from protease inhibitors.",
    authors_or_owner: "Scripps Research Technology Development",
    institution_or_sponsor: "Scripps Research",
    date: "2024-01-30",
    stage_hint: "preclinical",
    url: "https://www.scripps.edu/technology",
    metadata: { licensing_status: "available", contact_office: "Scripps Research Technology Development", patent_status: "patent pending", owner_type: "research_institute" },
  },
];

export function getScrippsListings(): RawSignal[] {
  return SCRIPPS_LISTINGS.map((listing) => ({
    ...listing,
    id: `scripps-${Math.random().toString(36).slice(2, 9)}`,
  }));
}
