import type { RawSignal } from "../../types";

const STANFORD_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "LZTR1-Targeted Small Molecule for RASopathy and Cancer",
    text: "Stanford researchers have identified a first-in-class small molecule inhibitor targeting LZTR1, a CRL3 substrate adaptor that controls RAS protein ubiquitination. The compound demonstrates potent anti-proliferative activity in RAS-driven cancers and rare RASopathy syndromes such as Noonan syndrome. Preclinical models show tumor regression with favorable selectivity.",
    authors_or_owner: "Stanford Technology Licensing",
    institution_or_sponsor: "Stanford University",
    date: "2024-09-01",
    stage_hint: "preclinical",
    url: "https://techfinder.stanford.edu",
    metadata: {
      licensing_status: "available",
      contact_office: "Stanford Office of Technology Licensing",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Engineered Exosomes for CNS Drug Delivery",
    text: "A platform technology for engineering exosomes to cross the blood-brain barrier and deliver therapeutic cargo to the CNS. The system uses genetically modified surface proteins to achieve targeted delivery to neurons and astrocytes. Demonstrated efficacy in Parkinson's and Alzheimer's animal models. IP covers the engineering methodology and specific surface modifications.",
    authors_or_owner: "Stanford Technology Licensing",
    institution_or_sponsor: "Stanford University",
    date: "2024-06-15",
    stage_hint: "preclinical",
    url: "https://techfinder.stanford.edu",
    metadata: {
      licensing_status: "available",
      contact_office: "Stanford Office of Technology Licensing",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "CAR-Macrophage Platform for Solid Tumor Immunotherapy",
    text: "Stanford engineers have developed a chimeric antigen receptor macrophage (CAR-M) platform that overcomes key limitations of CAR-T therapy in solid tumors. The macrophages can penetrate the immunosuppressive tumor microenvironment and exhibit phagocytic and cytokine-mediated killing. Initial data in pancreatic and ovarian cancer models are promising.",
    authors_or_owner: "Stanford Technology Licensing",
    institution_or_sponsor: "Stanford University",
    date: "2024-11-20",
    stage_hint: "preclinical",
    url: "https://techfinder.stanford.edu",
    metadata: {
      licensing_status: "available",
      contact_office: "Stanford Office of Technology Licensing",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Next-Gen PROTAC Degrader Targeting STAT3 in Hematologic Malignancies",
    text: "A proteolysis-targeting chimera (PROTAC) that selectively degrades STAT3 protein with improved cellular permeability over existing degraders. STAT3 is a validated oncogenic driver in multiple myeloma, AML, and DLBCL. The compound shows sub-nanomolar degradation efficiency and excellent selectivity in proteomics profiling.",
    authors_or_owner: "Stanford Technology Licensing",
    institution_or_sponsor: "Stanford University",
    date: "2025-01-08",
    stage_hint: "discovery",
    url: "https://techfinder.stanford.edu",
    metadata: {
      licensing_status: "available",
      contact_office: "Stanford Office of Technology Licensing",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "mRNA Delivery Platform Using pH-Responsive Lipid Nanoparticles",
    text: "A novel lipid nanoparticle formulation with pH-sensitive endosomal escape that dramatically improves mRNA delivery efficiency compared to ionizable lipid benchmarks. The formulation shows superior liver-tropism control and can be tuned for extrahepatic tissue targeting. Suitable for mRNA therapeutics and vaccines.",
    authors_or_owner: "Stanford Technology Licensing",
    institution_or_sponsor: "Stanford University",
    date: "2024-03-22",
    stage_hint: "preclinical",
    url: "https://techfinder.stanford.edu",
    metadata: {
      licensing_status: "available",
      contact_office: "Stanford Office of Technology Licensing",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Bispecific Antibody Targeting HER2 and CD47 for Breast Cancer",
    text: "A bispecific antibody that simultaneously targets HER2 (a tumor antigen overexpressed in ~20% of breast cancers) and CD47 (the 'don't-eat-me' signal that suppresses macrophage phagocytosis). Combining these two mechanisms achieves synergistic tumor cell killing in HER2+ breast cancer preclinical models without the systemic toxicity of monotherapy anti-CD47.",
    authors_or_owner: "Stanford Technology Licensing",
    institution_or_sponsor: "Stanford University",
    date: "2024-08-30",
    stage_hint: "preclinical",
    url: "https://techfinder.stanford.edu",
    metadata: {
      licensing_status: "available",
      contact_office: "Stanford Office of Technology Licensing",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "CRISPR Base Editing Correction of PCSK9 for Hypercholesterolemia",
    text: "Stanford researchers have developed a base editing approach to permanently silence PCSK9 expression in hepatocytes following a single in vivo administration. The approach achieves >80% editing efficiency in non-human primates with LDL reduction equivalent to current PCSK9 monoclonal antibodies, but with the potential for lifetime effect from a single dose.",
    authors_or_owner: "Stanford Technology Licensing",
    institution_or_sponsor: "Stanford University",
    date: "2025-02-14",
    stage_hint: "preclinical",
    url: "https://techfinder.stanford.edu",
    metadata: {
      licensing_status: "available",
      contact_office: "Stanford Office of Technology Licensing",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Synthetic Biology Platform for On-Demand CAR-T Cell Activation",
    text: "A synthetic biology approach to creating CAR-T cells that can be externally activated by a small-molecule drug, enabling precise temporal and spatial control of CAR-T activity. The system uses a chemogenetic switch that is OFF in the absence of the activating drug, reducing tonic signaling and exhaustion. Demonstrated in GBM and melanoma models.",
    authors_or_owner: "Stanford Technology Licensing",
    institution_or_sponsor: "Stanford University",
    date: "2024-12-01",
    stage_hint: "preclinical",
    url: "https://techfinder.stanford.edu",
    metadata: {
      licensing_status: "available",
      contact_office: "Stanford Office of Technology Licensing",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
];

export function getStanfordListings(): RawSignal[] {
  return STANFORD_LISTINGS.map((l, i) => ({ ...l, id: `stanford-tt-${i}` }));
}
