import type { RawSignal } from "../../types";

const UC_BERKELEY_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "Base Editing Platform for Precise Genetic Correction",
    text: "UC Berkeley researchers have developed an advanced base editing system enabling single-nucleotide corrections without double-strand DNA breaks. The platform demonstrates superior precision over conventional CRISPR-Cas9 in primary hematopoietic cells and induced pluripotent stem cells. Demonstrated efficacy for sickle cell disease, beta-thalassemia, and hereditary blindness. IP covers novel base editor architectures and guide RNA designs with minimal off-target activity.",
    authors_or_owner: "UC Berkeley Office of Technology Licensing",
    institution_or_sponsor: "UC Berkeley",
    date: "2024-08-12",
    stage_hint: "preclinical",
    url: "https://otl.berkeley.edu",
    metadata: { licensing_status: "available", contact_office: "UC Berkeley Office of Technology Licensing", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Circular mRNA Platform for Enhanced Protein Expression",
    text: "A novel circular mRNA technology developed at UC Berkeley offers dramatically improved stability and translation efficiency compared to linear mRNA formats. The platform uses engineered internal ribosome entry sites and optimized ligation chemistry to produce stable circular constructs resistant to exonuclease degradation. Applications span therapeutic protein replacement, vaccines, and cell engineering. Demonstrated 10-fold longer expression duration in preclinical models.",
    authors_or_owner: "UC Berkeley Office of Technology Licensing",
    institution_or_sponsor: "UC Berkeley",
    date: "2024-05-20",
    stage_hint: "preclinical",
    url: "https://otl.berkeley.edu",
    metadata: { licensing_status: "available", contact_office: "UC Berkeley Office of Technology Licensing", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Synthetic Biology Cell Factory for Therapeutic Molecule Production",
    text: "Berkeley's leading synthetic biology group has engineered mammalian cell factories capable of producing complex therapeutic molecules at pharmaceutical scale. The platform uses a layered genetic circuit architecture for tunable expression, metabolic flux optimization, and product sensing feedback loops. Current validated outputs include terpenoid-based antivirals, polyketide antibiotics, and novel alkaloids with oncological activity. GMP-compatible processes have been developed.",
    authors_or_owner: "UC Berkeley Office of Technology Licensing",
    institution_or_sponsor: "UC Berkeley",
    date: "2023-11-08",
    stage_hint: "preclinical",
    url: "https://otl.berkeley.edu",
    metadata: { licensing_status: "available", contact_office: "UC Berkeley Office of Technology Licensing", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Computationally Designed Protein Switches for Targeted Therapy",
    text: "Using de novo protein design algorithms, UC Berkeley engineers have created conditionally active therapeutic proteins that switch from inactive to active conformations in response to specific disease biomarkers. Applications include tumor-selective cytokines, conditionally active antibody fragments, and logic-gated enzyme prodrugs. The platform generates proteins with no natural homologs, minimizing immunogenicity. Validated in solid tumor models with improved therapeutic windows.",
    authors_or_owner: "UC Berkeley Office of Technology Licensing",
    institution_or_sponsor: "UC Berkeley",
    date: "2024-02-14",
    stage_hint: "preclinical",
    url: "https://otl.berkeley.edu",
    metadata: { licensing_status: "available", contact_office: "UC Berkeley Office of Technology Licensing", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Microbiome-Derived Postbiotic for Metabolic Disease",
    text: "Berkeley researchers have characterized a novel class of postbiotic metabolites produced by specific gut bacteria that directly improve insulin sensitivity and reduce hepatic lipid accumulation. The compounds act through FXR and TGR5 nuclear receptors to modulate bile acid signaling. Preclinical NASH and type 2 diabetes models show robust metabolic improvements without dysbiotic side effects. The molecules are amenable to chemical synthesis for pharmaceutical development.",
    authors_or_owner: "UC Berkeley Office of Technology Licensing",
    institution_or_sponsor: "UC Berkeley",
    date: "2023-09-30",
    stage_hint: "preclinical",
    url: "https://otl.berkeley.edu",
    metadata: { licensing_status: "available", contact_office: "UC Berkeley Office of Technology Licensing", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Cancer Metabolomics Biomarker Panel for Early Detection",
    text: "A serum metabolomics panel developed at UC Berkeley enables non-invasive early detection of pancreatic and ovarian cancers with high sensitivity and specificity. The panel uses LC-MS/MS quantification of 12 metabolite signatures validated across multi-cohort clinical studies. Detection at stage I/II enables curative intervention in cancers typically diagnosed at late stages. Platform is compatible with standard clinical lab infrastructure.",
    authors_or_owner: "UC Berkeley Office of Technology Licensing",
    institution_or_sponsor: "UC Berkeley",
    date: "2024-01-22",
    stage_hint: "discovery",
    url: "https://otl.berkeley.edu",
    metadata: { licensing_status: "available", contact_office: "UC Berkeley Office of Technology Licensing", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Epigenetic Silencer Screen Platform for Oncogene Suppression",
    text: "UC Berkeley has developed a high-throughput CRISPR-based epigenetic silencer screening platform that identifies combinations of chromatin regulators capable of silencing oncogenes without permanent DNA editing. The approach uses dCas9 fused to histone methyltransferases and validated in multiple cancer types including glioblastoma and hepatocellular carcinoma. Silencing is durable across cell divisions and reversible, offering a novel therapeutic modality.",
    authors_or_owner: "UC Berkeley Office of Technology Licensing",
    institution_or_sponsor: "UC Berkeley",
    date: "2023-07-15",
    stage_hint: "discovery",
    url: "https://otl.berkeley.edu",
    metadata: { licensing_status: "available", contact_office: "UC Berkeley Office of Technology Licensing", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "CAR-NK Cell Therapy with Persistence-Enhancing Cytokine Armoring",
    text: "Berkeley immunologists have engineered CAR-NK cells with integrated IL-15 and IL-21 cytokine armoring to overcome the persistence limitations of conventional NK cell therapies. The cells demonstrate superior in vivo persistence, tumor infiltration, and cytotoxicity against hematologic malignancies and solid tumors. The manufacturing process uses iPSC-derived NK cells for off-the-shelf scalability. Initial clinical translation planning underway.",
    authors_or_owner: "UC Berkeley Office of Technology Licensing",
    institution_or_sponsor: "UC Berkeley",
    date: "2024-10-05",
    stage_hint: "preclinical",
    url: "https://otl.berkeley.edu",
    metadata: { licensing_status: "available", contact_office: "UC Berkeley Office of Technology Licensing", patent_status: "patent pending", owner_type: "university" },
  },
];

export function getUcBerkeleyListings(): RawSignal[] {
  return UC_BERKELEY_LISTINGS.map((listing) => ({
    ...listing,
    id: `ucberkeley-${Math.random().toString(36).slice(2, 9)}`,
  }));
}
