import type { RawSignal } from "../../types";

const UCHICAGO_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "Orthogonal IL-2 Receptor System for Tumor-Selective T Cell Expansion",
    text: "University of Chicago immunologists have engineered a fully orthogonal IL-2/IL-2 receptor pair where an engineered IL-2 variant activates only T cells expressing a co-engineered IL-2Rβ variant, enabling selective antitumor T cell expansion without systemic cytokine toxicity. Adoptively transferred T cells or CAR-T cells expressing the orthogonal receptor expand exclusively upon dosing of the engineered IL-2, providing controlled amplification in vivo. Validated in solid and hematologic tumor models.",
    authors_or_owner: "UChicago Polsky Center for Entrepreneurship",
    institution_or_sponsor: "University of Chicago",
    date: "2024-11-10",
    stage_hint: "preclinical",
    url: "https://polsky.uchicago.edu/programs-services/technology-commercialization",
    metadata: { licensing_status: "available", contact_office: "UChicago Polsky Center", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Covalent NLRP3 Inflammasome Inhibitor for Inflammatory Disease",
    text: "UChicago chemists have developed a covalent small molecule inhibitor of NLRP3 that engages Cys-991 in the NACHT domain, achieving complete, durable NLRP3 inhibition at low doses. The compound blocks IL-1β and IL-18 secretion in macrophages and validated in gout, atherosclerosis, NASH, and cardiovascular inflammation models. Superior to reversible NLRP3 inhibitors by providing sustained suppression with infrequent dosing. Oral bioavailability and safety profile established.",
    authors_or_owner: "UChicago Polsky Center for Entrepreneurship",
    institution_or_sponsor: "University of Chicago",
    date: "2024-08-28",
    stage_hint: "preclinical",
    url: "https://polsky.uchicago.edu/programs-services/technology-commercialization",
    metadata: { licensing_status: "available", contact_office: "UChicago Polsky Center", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "TIGIT Antagonist Peptide for Combination Checkpoint Immunotherapy",
    text: "UChicago researchers have identified and optimized a cyclic peptide antagonist of TIGIT that blocks the TIGIT-PVR interaction and restores CD8 T cell and NK cell function in the tumor microenvironment. The peptide is formatted as a long-acting PEGylated construct with biweekly dosing potential. Strong synergy with anti-PD-1 in multiple syngeneic tumor models including colorectal and melanoma. Differentiated from antibody-based TIGIT antagonists by cost of goods and tumor penetration.",
    authors_or_owner: "UChicago Polsky Center for Entrepreneurship",
    institution_or_sponsor: "University of Chicago",
    date: "2024-06-14",
    stage_hint: "preclinical",
    url: "https://polsky.uchicago.edu/programs-services/technology-commercialization",
    metadata: { licensing_status: "available", contact_office: "UChicago Polsky Center", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Trained Immunity Modulator for Cancer Immunoprevention",
    text: "UChicago cancer biologists have identified a beta-glucan derivative that induces trained immunity in bone marrow progenitor cells, epigenetically reprogramming innate immune cells for enhanced antitumor surveillance. In preclinical models of spontaneous and carcinogen-induced cancers, trained immunity induction reduces tumor incidence and progression. Oral formulation with favorable tolerability. Positioned as a novel cancer immunoprevention approach for high-risk populations.",
    authors_or_owner: "UChicago Polsky Center for Entrepreneurship",
    institution_or_sponsor: "University of Chicago",
    date: "2024-04-02",
    stage_hint: "preclinical",
    url: "https://polsky.uchicago.edu/programs-services/technology-commercialization",
    metadata: { licensing_status: "available", contact_office: "UChicago Polsky Center", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Gut-Brain Axis Metabolite for Depression and Anxiety",
    text: "UChicago neurogastroenterology researchers have identified a gut-derived indole metabolite produced by Lactobacillus reuteri that crosses the blood-brain barrier and activates aryl hydrocarbon receptor signaling in the hypothalamus to produce antidepressant and anxiolytic effects. The metabolite reduces inflammatory cytokine production in the brain, addressing the neuroimmune component of treatment-resistant depression. Oral synthetic version validated in chronic stress models with effects comparable to SSRIs.",
    authors_or_owner: "UChicago Polsky Center for Entrepreneurship",
    institution_or_sponsor: "University of Chicago",
    date: "2024-02-20",
    stage_hint: "preclinical",
    url: "https://polsky.uchicago.edu/programs-services/technology-commercialization",
    metadata: { licensing_status: "available", contact_office: "UChicago Polsky Center", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "cGAS-STING Inhibitor for Autoimmune and Sterile Inflammatory Disease",
    text: "UChicago immunologists have developed potent, selective cGAS inhibitors addressing the self-DNA sensing pathway that drives sterile inflammation in SLE, Sjögren's syndrome, STING-associated vasculopathy (SAVI), and inflammatory myopathies. The compounds achieve >99% cGAS enzyme inhibition at nanomolar concentrations and reduce type I interferon signatures in patient-derived cells. Oral bioavailability confirmed. Multiple chemical series available for licensing.",
    authors_or_owner: "UChicago Polsky Center for Entrepreneurship",
    institution_or_sponsor: "University of Chicago",
    date: "2023-11-15",
    stage_hint: "preclinical",
    url: "https://polsky.uchicago.edu/programs-services/technology-commercialization",
    metadata: { licensing_status: "available", contact_office: "UChicago Polsky Center", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Nanoparticle Allergen Desensitization Platform for Food Allergy",
    text: "UChicago immunologists have developed biodegradable PLGA nanoparticles encapsulating peanut, tree nut, or milk allergens that deliver antigen to tolerogenic liver-resident APCs via portal circulation, inducing robust antigen-specific tolerance without systemic allergen exposure. The platform avoids the anaphylaxis risk of conventional sublingual or oral immunotherapy. In murine food allergy models, a 3-dose series produces durable tolerance lasting over 6 months.",
    authors_or_owner: "UChicago Polsky Center for Entrepreneurship",
    institution_or_sponsor: "University of Chicago",
    date: "2024-09-08",
    stage_hint: "preclinical",
    url: "https://polsky.uchicago.edu/programs-services/technology-commercialization",
    metadata: { licensing_status: "available", contact_office: "UChicago Polsky Center", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Regulatory T Cell Expander for Autoimmune Disease and Transplant",
    text: "UChicago transplant immunologists have developed a low-dose IL-2 muteins conjugated to anti-CD25 antibody fragments that selectively expand regulatory T cells (Tregs) 20-fold without activating effector T cells or NK cells. The technology overcomes the fundamental limitation of clinical IL-2: equal stimulation of anti-regulatory cell populations. Validated for graft-versus-host disease prevention, type 1 diabetes, and rheumatoid arthritis. First-in-human studies in planning.",
    authors_or_owner: "UChicago Polsky Center for Entrepreneurship",
    institution_or_sponsor: "University of Chicago",
    date: "2024-07-04",
    stage_hint: "preclinical",
    url: "https://polsky.uchicago.edu/programs-services/technology-commercialization",
    metadata: { licensing_status: "available", contact_office: "UChicago Polsky Center", patent_status: "patent pending", owner_type: "university" },
  },
];

export function getUchicagoListings(): RawSignal[] {
  return UCHICAGO_LISTINGS.map((listing) => ({
    ...listing,
    id: `uchicago-${Math.random().toString(36).slice(2, 9)}`,
  }));
}
