import type { RawSignal } from "../../types";

const UCSD_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "AI-Designed Miniprotein Inhibitor of the SARS-CoV-2 Spike — Generalizable Platform for Viral Entry Inhibition",
    text: "UCSD computational biologists used deep learning-based protein design to generate hyperstable miniproteins that bind the ACE2-binding domain of SARS-CoV-2 spike with picomolar affinity. The approach, generalizable to any viral surface protein with a known structure, has been extended to influenza HA and RSV F proteins. The miniprotein scaffold is <7 kDa, thermostable to 95°C, and manufacturable by peptide synthesis or E. coli expression.",
    authors_or_owner: "UC San Diego Office of Innovation and Commercialization",
    institution_or_sponsor: "University of California, San Diego",
    date: "2024-10-05",
    stage_hint: "preclinical",
    url: "https://innovation.ucsd.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "UCSD OIC", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Brain-Penetrant Small Molecule CDK5 Inhibitor for Alzheimer's and Frontotemporal Dementia",
    text: "A selective CDK5/p25 inhibitor designed with a CNS-tuned pharmacophore that achieves >40% brain penetration and reduces hyperphosphorylated tau pathology in 3xTg-AD mice following oral dosing. CDK5 dysregulation by p25 (a truncated activator) is a primary driver of neurofibrillary tangle formation. Unlike prior CDK5 inhibitors, the compound spares CDK1/2/4 at therapeutic concentrations, avoiding cell-cycle toxicity in dividing tissues.",
    authors_or_owner: "UC San Diego Office of Innovation and Commercialization",
    institution_or_sponsor: "University of California, San Diego",
    date: "2025-01-22",
    stage_hint: "preclinical",
    url: "https://innovation.ucsd.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "UCSD OIC", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Retinal Organoid-Derived Photoreceptor Cell Therapy for Retinitis Pigmentosa",
    text: "A GMP-compatible protocol for differentiating human iPSCs into functional cone and rod photoreceptors via retinal organoid intermediate, optimized for sub-retinal transplantation in retinitis pigmentosa. The cells are delivered in a biodegradable fibrin scaffold that maintains photoreceptor orientation and facilitates synaptic integration with host bipolar cells. Partial visual function restoration demonstrated in rd1 mouse and RCS rat models.",
    authors_or_owner: "UC San Diego Office of Innovation and Commercialization",
    institution_or_sponsor: "University of California, San Diego",
    date: "2024-07-14",
    stage_hint: "preclinical",
    url: "https://innovation.ucsd.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "UCSD OIC", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Liquid Biopsy Platform for Multi-Cancer Early Detection via Methylated cfDNA",
    text: "A methylation-based cell-free DNA assay that simultaneously detects 10 cancer types from a single blood draw using a targeted panel of tissue-of-origin methylation signatures. Validated in 1,200-patient prospective biobank study: overall stage I–II sensitivity of 62% at 98% specificity, with sensitivity >80% for pancreatic, ovarian, and hepatic cancers — the highest-mortality cancers with fewest early detection options. Regulatory strategy: breakthrough device designation pathway.",
    authors_or_owner: "UC San Diego Office of Innovation and Commercialization",
    institution_or_sponsor: "University of California, San Diego",
    date: "2024-11-18",
    stage_hint: "preclinical",
    url: "https://innovation.ucsd.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "UCSD OIC", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Microfluidic Platform for High-Throughput Tumor Organoid Drug Sensitivity Testing",
    text: "A microfluidic platform that encapsulates patient-derived tumor organoids in nanoliter-volume droplets and tests them against 96 drug combinations in parallel within 72 hours of biopsy receipt. In a 45-patient prospective oncology study, organoid drug sensitivity results correctly predicted clinical response in 82% of cases, outperforming genomic biomarkers. Available for licensing as a companion diagnostic platform or as a stand-alone drug discovery tool.",
    authors_or_owner: "UC San Diego Office of Innovation and Commercialization",
    institution_or_sponsor: "University of California, San Diego",
    date: "2024-09-02",
    stage_hint: "preclinical",
    url: "https://innovation.ucsd.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "UCSD OIC", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Oral Microbiome-Derived Probiotic for Prevention of Clostridium Difficile Infection",
    text: "A defined three-strain consortium of commensal gut bacteria identified from C. diff-resistant microbiome profiles that colonizes stably and competitively excludes C. difficile via niche competition and antimicrobial peptide production. Oral capsule format. In hamster CDI models, a 3-day course reduces CDI recurrence by 85% versus vancomycin alone. Designed for antibiotic stewardship co-administration in hospitalized patients receiving broad-spectrum antibiotics.",
    authors_or_owner: "UC San Diego Office of Innovation and Commercialization",
    institution_or_sponsor: "University of California, San Diego",
    date: "2024-05-28",
    stage_hint: "preclinical",
    url: "https://innovation.ucsd.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "UCSD OIC", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Computationally Designed Allosteric SHP2 Inhibitor for RAS-MAPK Driven Cancers",
    text: "A cryptic allosteric pocket inhibitor of SHP2 phosphatase identified via molecular dynamics simulation of the closed (auto-inhibited) to open conformational transition, revealing a binding site not accessible in crystal structures. The compound locks SHP2 in the closed state with IC50 of 3 nM and achieves tumor regression in KRAS G12C, EGFR-mutant, and NF1-deficient tumor models as monotherapy and in combination with KRAS inhibitors. Fully synthetic, orally available.",
    authors_or_owner: "UC San Diego Office of Innovation and Commercialization",
    institution_or_sponsor: "University of California, San Diego",
    date: "2025-02-08",
    stage_hint: "preclinical",
    url: "https://innovation.ucsd.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "UCSD OIC", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Electroactive Hydrogel Neural Interface for Parkinson's Disease DBS",
    text: "A soft, conducting polymer hydrogel electrode coating for deep brain stimulation leads that reduces chronic foreign body response and maintains impedance stability for >5 years implantation (validated in rodent model). The coating is dip-coatable onto existing clinical DBS electrode geometries, enabling a simple upgrade to current-generation devices. Reduced electrode impedance allows equivalent therapeutic stimulation at 30% lower energy output, extending battery life.",
    authors_or_owner: "UC San Diego Office of Innovation and Commercialization",
    institution_or_sponsor: "University of California, San Diego",
    date: "2024-08-20",
    stage_hint: "preclinical",
    url: "https://innovation.ucsd.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "UCSD OIC", patent_status: "patented", owner_type: "university" },
  },
];

export function getUcsdListings(): RawSignal[] {
  return UCSD_LISTINGS.map((l, i) => ({ ...l, id: `ucsd-tt-${i}` }));
}
