import type { RawSignal } from "../../types";

const UCSF_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "KRAS G12D-Selective Covalent Inhibitor for Pancreatic Cancer",
    text: "UCSF researchers have developed a selective covalent small molecule inhibitor targeting the KRAS G12D mutation, the most prevalent KRAS variant in pancreatic ductal adenocarcinoma. The compound achieves sub-nanomolar potency against G12D while sparing wild-type KRAS, a major selectivity hurdle that prior programs failed to overcome. Efficacy demonstrated in patient-derived organoids and orthotopic mouse models.",
    authors_or_owner: "UCSF Innovation Ventures",
    institution_or_sponsor: "University of California, San Francisco",
    date: "2025-01-20",
    stage_hint: "preclinical",
    url: "https://innovation.ucsf.edu/available-technologies",
    metadata: {
      licensing_status: "available",
      contact_office: "UCSF Innovation Ventures",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Single-Cell Multiomics Platform for Tumor Microenvironment Profiling",
    text: "A UCSF-developed platform combining simultaneous single-cell RNA sequencing, ATAC-seq, and protein quantification to profile immune cell states within the tumor microenvironment. The technology generates a proprietary cell state atlas that predicts immunotherapy response with 89% accuracy across NSCLC and melanoma cohorts. Suitable for companion diagnostic licensing or as a discovery research tool.",
    authors_or_owner: "UCSF Innovation Ventures",
    institution_or_sponsor: "University of California, San Francisco",
    date: "2024-10-05",
    stage_hint: "discovery",
    url: "https://innovation.ucsf.edu/available-technologies",
    metadata: {
      licensing_status: "available",
      contact_office: "UCSF Innovation Ventures",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Anti-FcRn Antibody Fragment for Autoimmune IgG-Mediated Diseases",
    text: "A half-life-engineered Fc fragment (Fc-engineered decoy) that competes with pathogenic IgG autoantibodies for FcRn binding, accelerating IgG catabolism. The technology is designed for conditions including myasthenia gravis, pemphigus vulgaris, and anti-NMDAR encephalitis. Unlike full monoclonal antibodies targeting FcRn, the fragment format enables subcutaneous self-administration and lower manufacturing cost.",
    authors_or_owner: "UCSF Innovation Ventures",
    institution_or_sponsor: "University of California, San Francisco",
    date: "2024-07-12",
    stage_hint: "preclinical",
    url: "https://innovation.ucsf.edu/available-technologies",
    metadata: {
      licensing_status: "available",
      contact_office: "UCSF Innovation Ventures",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "In Vivo AAV-Based Base Editing for Spinal Muscular Atrophy",
    text: "UCSF has developed an AAV9-delivered adenine base editor that restores SMN2 exon 7 inclusion in motor neurons following a single intrathecal injection. The approach achieves >70% editing in spinal cord neurons in neonatal mouse models with near-complete reversal of the SMA phenotype. The editor construct is substantially smaller than full-length prime editors, enabling efficient AAV packaging.",
    authors_or_owner: "UCSF Innovation Ventures",
    institution_or_sponsor: "University of California, San Francisco",
    date: "2025-02-28",
    stage_hint: "preclinical",
    url: "https://innovation.ucsf.edu/available-technologies",
    metadata: {
      licensing_status: "available",
      contact_office: "UCSF Innovation Ventures",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Bispecific T Cell Engager Targeting GD2 and CD3 for Neuroblastoma",
    text: "A proprietary bispecific T cell engager (BiTE) with optimized GD2-binding domain that achieves potent T cell-mediated killing of neuroblastoma and GD2-positive osteosarcoma cells. The molecule incorporates a half-life extension domain to enable weekly dosing. Preclinical data demonstrate superior cytotoxicity compared to dinutuximab at lower effector-to-target ratios.",
    authors_or_owner: "UCSF Innovation Ventures",
    institution_or_sponsor: "University of California, San Francisco",
    date: "2024-05-15",
    stage_hint: "preclinical",
    url: "https://innovation.ucsf.edu/available-technologies",
    metadata: {
      licensing_status: "available",
      contact_office: "UCSF Innovation Ventures",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Oral GLP-1 Receptor Agonist Peptide with Enhanced Bioavailability",
    text: "A cyclized, proteolysis-resistant GLP-1 receptor agonist peptide that achieves >15% oral bioavailability in non-human primates — significantly exceeding current oral peptide benchmarks. The compound retains full receptor potency and duration of action with a once-daily oral dosing profile. IP covers both the peptide scaffold and the cyclization chemistry.",
    authors_or_owner: "UCSF Innovation Ventures",
    institution_or_sponsor: "University of California, San Francisco",
    date: "2025-03-01",
    stage_hint: "preclinical",
    url: "https://innovation.ucsf.edu/available-technologies",
    metadata: {
      licensing_status: "available",
      contact_office: "UCSF Innovation Ventures",
      patent_status: "patent pending",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "Engineered IL-2 Variant with Tumor-Selective Signaling",
    text: "A computationally designed IL-2 variant that preferentially signals through IL-2Rβγ (found on effector T and NK cells) while minimizing IL-2Rα binding (associated with regulatory T cell expansion and vascular leak syndrome). The variant shows a 50-fold improved therapeutic index compared to aldesleukin in syngeneic tumor models, with durable tumor regression at doses 10-fold below the MTD of wild-type IL-2.",
    authors_or_owner: "UCSF Innovation Ventures",
    institution_or_sponsor: "University of California, San Francisco",
    date: "2024-09-18",
    stage_hint: "preclinical",
    url: "https://innovation.ucsf.edu/available-technologies",
    metadata: {
      licensing_status: "available",
      contact_office: "UCSF Innovation Ventures",
      patent_status: "patented",
      owner_type: "university",
    },
  },
  {
    source_type: "tech_transfer",
    title: "CXCR4 Antagonist Peptide for Stem Cell Mobilization and HIV Therapy",
    text: "A novel cyclic peptide CXCR4 antagonist with superior pharmacokinetics compared to plerixafor, suitable for both hematopoietic stem cell mobilization and as an anti-HIV entry inhibitor. The compound shows synergistic activity with G-CSF in mobilization protocols and demonstrates potent inhibition of CXCR4-tropic HIV strains. Formulated for subcutaneous administration with twice-weekly dosing.",
    authors_or_owner: "UCSF Innovation Ventures",
    institution_or_sponsor: "University of California, San Francisco",
    date: "2024-04-22",
    stage_hint: "preclinical",
    url: "https://innovation.ucsf.edu/available-technologies",
    metadata: {
      licensing_status: "available",
      contact_office: "UCSF Innovation Ventures",
      patent_status: "patented",
      owner_type: "university",
    },
  },
];

export function getUcsfListings(): RawSignal[] {
  return UCSF_LISTINGS.map((l, i) => ({ ...l, id: `ucsf-tt-${i}` }));
}
