import type { RawSignal } from "../../types";

const UMICH_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "Next-Generation MDM2 Inhibitor with Improved Cancer Selectivity",
    text: "University of Michigan medicinal chemists—pioneers of the MDM2-p53 inhibitor field—have developed a new-generation MDM2 inhibitor series with dramatically improved tumor selectivity and resistance profile. The lead compound achieves potent p53 reactivation in MDM2-amplified cancers while displaying an 8-fold improvement in therapeutic index over early-generation compounds. Activity confirmed in liposarcoma, glioblastoma, and ALL models. IND-enabling studies ongoing.",
    authors_or_owner: "UM Technology Transfer",
    institution_or_sponsor: "University of Michigan",
    date: "2024-09-25",
    stage_hint: "preclinical",
    url: "https://techtransfer.umich.edu",
    metadata: { licensing_status: "available", contact_office: "UM Technology Transfer", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Ionizable Lipid Nanoparticle Library for Organ-Selective mRNA Delivery",
    text: "UM pharmaceutical scientists have developed a combinatorial library of ionizable lipid nanoparticles with tunable organ tropism for mRNA delivery. By adjusting lipid tail branching and head group chemistry, they have achieved selective delivery to liver, lung, spleen, and muscle without active targeting ligands. The platform enables tissue-specific expression for metabolic diseases, respiratory disorders, and cancer immunotherapy applications.",
    authors_or_owner: "UM Technology Transfer",
    institution_or_sponsor: "University of Michigan",
    date: "2024-06-10",
    stage_hint: "preclinical",
    url: "https://techtransfer.umich.edu",
    metadata: { licensing_status: "available", contact_office: "UM Technology Transfer", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Metabolically Engineered NK Cell Therapy for Solid Tumors",
    text: "UM cancer immunologists have engineered NK cells with enhanced metabolic fitness through PPARGC1A overexpression and mitochondrial biogenesis upregulation. The cells maintain effector function in the nutrient-depleted solid tumor microenvironment, overcoming a primary resistance mechanism. Combined with a novel CAR targeting B7-H3 (CD276), the cells show potent activity against glioblastoma, prostate, and ovarian cancers in xenograft models. Allogeneic manufacturing platform established.",
    authors_or_owner: "UM Technology Transfer",
    institution_or_sponsor: "University of Michigan",
    date: "2024-04-18",
    stage_hint: "preclinical",
    url: "https://techtransfer.umich.edu",
    metadata: { licensing_status: "available", contact_office: "UM Technology Transfer", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "mTOR-Independent Autophagy Inducer for Neurodegeneration",
    text: "UM neurologists have identified a small molecule that induces autophagy through an mTORC1-independent mechanism via TFEB nuclear translocation, avoiding the immunosuppressive and metabolic liabilities of rapamycin-based approaches. The compound reduces protein aggregates (tau, alpha-synuclein, TDP-43) in neuronal models and transgenic mouse models of Alzheimer's, Parkinson's, and ALS. Oral bioavailability and CNS penetration confirmed.",
    authors_or_owner: "UM Technology Transfer",
    institution_or_sponsor: "University of Michigan",
    date: "2023-12-01",
    stage_hint: "preclinical",
    url: "https://techtransfer.umich.edu",
    metadata: { licensing_status: "available", contact_office: "UM Technology Transfer", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Tumor-Localized STING Agonist for Systemic Immune Priming",
    text: "UM researchers have engineered a tumor-targeted STING agonist conjugate that concentrates innate immune activation at the tumor site, avoiding the systemic cytokine toxicity that has limited prior STING agonist development. The conjugate uses a tumor-reactive antibody fragment for targeting and a pH-sensitive linker for intratumoral STING agonist release. Strong abscopal effects demonstrated in bilateral syngeneic tumor models, indicating systemic immune priming.",
    authors_or_owner: "UM Technology Transfer",
    institution_or_sponsor: "University of Michigan",
    date: "2024-08-06",
    stage_hint: "preclinical",
    url: "https://techtransfer.umich.edu",
    metadata: { licensing_status: "available", contact_office: "UM Technology Transfer", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "BRD4 Heterobifunctional Degrader for MYC-Driven Cancers",
    text: "University of Michigan chemists have synthesized a highly selective BRD4 PROTAC degrader achieving >95% BRD4 protein elimination at nanomolar concentrations in MYC-driven cancers including TNBC, SCLC, and Burkitt lymphoma. The degrader shows superior efficacy to BRD4 inhibitors by eliminating scaffolding functions and demonstrates activity in BET inhibitor-resistant cell lines. Full ADMET optimization completed with favorable oral pharmacokinetics.",
    authors_or_owner: "UM Technology Transfer",
    institution_or_sponsor: "University of Michigan",
    date: "2024-03-22",
    stage_hint: "preclinical",
    url: "https://techtransfer.umich.edu",
    metadata: { licensing_status: "available", contact_office: "UM Technology Transfer", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Pancreatic Cancer Early Detection Protein Biomarker Panel",
    text: "UM pancreatic cancer researchers have identified and validated a 6-protein serum biomarker panel that detects pancreatic ductal adenocarcinoma at stage I/II with 91% sensitivity and 88% specificity. The panel includes three novel biomarkers first described by this group. Validated across three independent patient cohorts (n=1,200). Clinical-grade ELISA assay format developed. Companion diagnostic regulatory strategy complete.",
    authors_or_owner: "UM Technology Transfer",
    institution_or_sponsor: "University of Michigan",
    date: "2024-01-15",
    stage_hint: "discovery",
    url: "https://techtransfer.umich.edu",
    metadata: { licensing_status: "available", contact_office: "UM Technology Transfer", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Innate Immune Adjuvant System for Enhanced Vaccine Responses",
    text: "UM vaccinologists have developed a particulate adjuvant system combining TLR4 and STING co-stimulation in a single nanoparticle formulation to achieve markedly enhanced T cell and antibody responses. The system generates 10-fold higher CD8 T cell responses than alum-based adjuvants and activates Th1-biased immunity critical for cancer and intracellular pathogen vaccines. Compatible with protein, peptide, and mRNA antigen formats.",
    authors_or_owner: "UM Technology Transfer",
    institution_or_sponsor: "University of Michigan",
    date: "2023-10-08",
    stage_hint: "preclinical",
    url: "https://techtransfer.umich.edu",
    metadata: { licensing_status: "available", contact_office: "UM Technology Transfer", patent_status: "patent pending", owner_type: "university" },
  },
];

export function getUmichListings(): RawSignal[] {
  return UMICH_LISTINGS.map((listing) => ({
    ...listing,
    id: `umich-${Math.random().toString(36).slice(2, 9)}`,
  }));
}
