import type { RawSignal } from "../../types";

const UPITT_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "Decellularized Extracellular Matrix Bioscaffold for Tissue Regeneration",
    text: "University of Pittsburgh's McGowan Institute has pioneered the clinical application of decellularized extracellular matrix (ECM) bioscaffolds derived from porcine urinary bladder, small intestine, and skeletal muscle. The scaffolds provide a bioactive 3D template that promotes constructive remodeling and site-appropriate tissue regeneration rather than fibrotic repair. Clinical applications include abdominal wall repair, rotator cuff reconstruction, and esophageal reconstruction with commercial precedents. Multiple new ECM formulations in active development.",
    authors_or_owner: "University of Pittsburgh Innovation Institute",
    institution_or_sponsor: "University of Pittsburgh",
    date: "2024-08-05",
    stage_hint: "approved",
    url: "https://www.innovation.pitt.edu",
    metadata: { licensing_status: "available", contact_office: "Pitt Innovation Institute", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Mixed Chimerism Tolerance Protocol for Living Donor Transplants",
    text: "Pitt transplant immunologists have developed a combined hematopoietic stem cell and solid organ transplantation protocol that establishes mixed chimerism and operational tolerance, enabling withdrawal of immunosuppression in kidney transplant recipients. The protocol uses a reduced-intensity conditioning regimen and donor-derived regulatory T cell infusions. Phase I/II trial results show tolerance achievement in 40% of patients at 2 years without immunosuppression.",
    authors_or_owner: "University of Pittsburgh Innovation Institute",
    institution_or_sponsor: "University of Pittsburgh",
    date: "2024-05-18",
    stage_hint: "phase 2",
    url: "https://www.innovation.pitt.edu",
    metadata: { licensing_status: "available", contact_office: "Pitt Innovation Institute", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Patient-Derived Lung Organoid Platform for Personalized Medicine",
    text: "Pitt pulmonologists have developed a rapid lung organoid generation protocol from patient bronchoscopy specimens that produces pharmacologically responsive organoids within 14 days. The platform preserves patient-specific disease characteristics including COPD, IPF, and lung cancer microenvironments. Demonstrated concordance between organoid drug responses and clinical outcomes in NSCLC patients. Platform is being used for personalized treatment selection and drug discovery.",
    authors_or_owner: "University of Pittsburgh Innovation Institute",
    institution_or_sponsor: "University of Pittsburgh",
    date: "2024-03-28",
    stage_hint: "discovery",
    url: "https://www.innovation.pitt.edu",
    metadata: { licensing_status: "available", contact_office: "Pitt Innovation Institute", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Injectable Cardiac Decellularized Matrix Hydrogel",
    text: "Pitt bioengineers have developed an injectable cardiac ECM hydrogel derived from decellularized myocardium that can be delivered by catheter-based intramyocardial injection after acute MI. The hydrogel self-assembles at body temperature, provides a bioactive scaffold for cardiomyocyte survival, and recruits progenitor cells to the infarct zone. Phase I clinical trial safety completed. Ejection fraction improvement signal at 3 months supports Phase II advancement.",
    authors_or_owner: "University of Pittsburgh Innovation Institute",
    institution_or_sponsor: "University of Pittsburgh",
    date: "2024-10-10",
    stage_hint: "phase 1",
    url: "https://www.innovation.pitt.edu",
    metadata: { licensing_status: "available", contact_office: "Pitt Innovation Institute", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Bioelectric Signal Modulation for Limb Regeneration",
    text: "Pitt regenerative biologists have discovered that modulation of bioelectric signaling through ion channel targeting can reinitiate regenerative programs in mammalian limb tissues, enabling de novo digit tip and digit joint regeneration in adult mice. The approach uses a combination of HCN channel blockers and BMP pathway activators administered by hydrogel depot. Enables regeneration without exogenous cell transplantation. First demonstration of mammalian multi-tissue regenerative induction.",
    authors_or_owner: "University of Pittsburgh Innovation Institute",
    institution_or_sponsor: "University of Pittsburgh",
    date: "2024-07-21",
    stage_hint: "discovery",
    url: "https://www.innovation.pitt.edu",
    metadata: { licensing_status: "available", contact_office: "Pitt Innovation Institute", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Electrospun Nanofiber Membrane for Musculoskeletal Tissue Repair",
    text: "Pitt bioengineers have developed electrospun nanofiber membranes with anisotropic alignment and gradient mechanical properties that mimic the complex architecture of tendons, ligaments, and meniscal tissue. The membranes are seeded with autologous mesenchymal stem cells and functionalized with BMP-2 and TGF-β3 for zone-specific differentiation. In vivo studies in rotator cuff, ACL, and meniscal defect models show histologically confirmed native-like tissue regeneration.",
    authors_or_owner: "University of Pittsburgh Innovation Institute",
    institution_or_sponsor: "University of Pittsburgh",
    date: "2023-12-12",
    stage_hint: "preclinical",
    url: "https://www.innovation.pitt.edu",
    metadata: { licensing_status: "available", contact_office: "Pitt Innovation Institute", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Conformal Islet Encapsulation for Immune-Evasive Transplantation",
    text: "Pitt researchers have developed a conformal coating technology for pancreatic islets that applies an ultrathin, biocompatible hydrogel shell directly to individual islets, enabling long-term graft survival without systemic immunosuppression. The coating uses covalently crosslinked PEG chemistry with anti-inflammatory zwitterionic surface modifications. In non-human primate transplantation studies, coated islets survive >6 months with maintained insulin secretion and glycemic control.",
    authors_or_owner: "University of Pittsburgh Innovation Institute",
    institution_or_sponsor: "University of Pittsburgh",
    date: "2024-02-05",
    stage_hint: "preclinical",
    url: "https://www.innovation.pitt.edu",
    metadata: { licensing_status: "available", contact_office: "Pitt Innovation Institute", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Anisotropic Spinal Cord Bridging Scaffold for Complete SCI",
    text: "Pitt neuroscientists have developed an anisotropically aligned biomaterial scaffold incorporating BDNF and NT-3 gradients and Schwann cells that bridges complete spinal cord injuries and directs regenerating axon growth across the lesion. In T10 complete transection rat models, treated animals show histologically confirmed axon crossing and partial hindlimb functional recovery by 12 weeks. Scaffold is clinically scalable from FDA-approved materials.",
    authors_or_owner: "University of Pittsburgh Innovation Institute",
    institution_or_sponsor: "University of Pittsburgh",
    date: "2024-09-04",
    stage_hint: "preclinical",
    url: "https://www.innovation.pitt.edu",
    metadata: { licensing_status: "available", contact_office: "Pitt Innovation Institute", patent_status: "patent pending", owner_type: "university" },
  },
];

export function getUpittListings(): RawSignal[] {
  return UPITT_LISTINGS.map((listing) => ({
    ...listing,
    id: `upitt-${Math.random().toString(36).slice(2, 9)}`,
  }));
}
