import type { RawSignal } from "../../types";

const UTSW_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "First-in-Class cGAS-STING Inhibitor for Sterile Inflammatory Diseases",
    text: "UT Southwestern researchers pioneered cGAS biochemistry and have developed a highly selective small molecule cGAS inhibitor that suppresses innate immune activation in sterile inflammatory contexts. The compound shows potent efficacy in mouse models of lupus, type I interferonopathy (AGS), and radiation-induced tissue damage without impacting antibacterial immune responses at therapeutic doses. IP covers the compound series, the binding site, and in vitro/in vivo data package.",
    authors_or_owner: "UT Southwestern Medical Center Technology Development",
    institution_or_sponsor: "UT Southwestern Medical Center",
    date: "2024-11-15",
    stage_hint: "preclinical",
    url: "https://www.utsouthwestern.edu/research/techtransfer",
    metadata: { licensing_status: "available", contact_office: "UTSW Technology Development", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "PI3K-delta/gamma Dual Inhibitor for Inflammatory and Autoimmune Diseases",
    text: "A highly selective oral PI3K-delta/gamma dual inhibitor designed for inflammatory diseases where both isoforms drive pathological B cell activation and tissue macrophage polarization. Unlike pan-PI3K inhibitors, the compound spares PI3K-alpha and PI3K-beta, reducing metabolic and cardiac side effects. Demonstrates superior efficacy compared to selective PI3K-delta inhibitors (idelalisib class) in rheumatoid arthritis and SLE mouse models with cleaner tolerability.",
    authors_or_owner: "UT Southwestern Medical Center Technology Development",
    institution_or_sponsor: "UT Southwestern Medical Center",
    date: "2024-08-10",
    stage_hint: "preclinical",
    url: "https://www.utsouthwestern.edu/research/techtransfer",
    metadata: { licensing_status: "available", contact_office: "UTSW Technology Development", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "AAV-Delivered Gene Replacement for CDKL5 Deficiency Disorder",
    text: "An intrathecally-delivered AAV9 vector expressing a codon-optimized, full-length CDKL5 gene under a neuron-specific promoter for CDKL5 deficiency disorder (CDD) — a severe early-onset epileptic encephalopathy with no disease-modifying treatment. Single intrathecal injection in Cdkl5 KO mice achieves widespread cortical and hippocampal CDKL5 expression, reduces spontaneous seizure frequency by 80%, and normalizes synaptic density. Regulatory pre-IND meeting completed.",
    authors_or_owner: "UT Southwestern Medical Center Technology Development",
    institution_or_sponsor: "UT Southwestern Medical Center",
    date: "2025-01-20",
    stage_hint: "preclinical",
    url: "https://www.utsouthwestern.edu/research/techtransfer",
    metadata: { licensing_status: "available", contact_office: "UTSW Technology Development", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Metabolically-Targeted Antibody for LDL-Lowering via PCSK9 Internalization",
    text: "A bispecific antibody that binds PCSK9 and simultaneously recruits lysosomal targeting receptor LRPAP1, routing the PCSK9-antibody complex to lysosomal degradation rather than recycling. This mechanism achieves 90% sustained PCSK9 depletion from a single dose with a 12-week effect duration — 3x longer than existing anti-PCSK9 mAbs. Suitable for quarterly or twice-yearly dosing with direct cardiovascular risk reduction benefit in familial hypercholesterolemia.",
    authors_or_owner: "UT Southwestern Medical Center Technology Development",
    institution_or_sponsor: "UT Southwestern Medical Center",
    date: "2024-06-25",
    stage_hint: "preclinical",
    url: "https://www.utsouthwestern.edu/research/techtransfer",
    metadata: { licensing_status: "available", contact_office: "UTSW Technology Development", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Organoid-Based Drug Screening Platform for Cholangiocarcinoma",
    text: "A patient-derived biliary organoid biobank of 35 cholangiocarcinoma cases including rare IDH1/IDH2-mutant, FGFR2-fusion, and ARID1A-mutant subtypes. Each organoid line is paired with clinical outcome data. The platform enables drug sensitivity profiling, biomarker identification, and combination testing for this rare cancer with limited preclinical model options. Available under a research license or as a co-development partnership for cholangiocarcinoma drug programs.",
    authors_or_owner: "UT Southwestern Medical Center Technology Development",
    institution_or_sponsor: "UT Southwestern Medical Center",
    date: "2024-10-08",
    stage_hint: "discovery",
    url: "https://www.utsouthwestern.edu/research/techtransfer",
    metadata: { licensing_status: "available", contact_office: "UTSW Technology Development", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Ferroptosis Sensitizer for Therapy-Resistant Pancreatic Cancer",
    text: "A small molecule that depletes GPX4 activity in KRAS-mutant pancreatic ductal adenocarcinoma cells by targeting a novel upstream regulator of the GPX4 transcriptional program, sensitizing otherwise therapy-resistant cells to ferroptotic cell death. The compound synergizes with RSL3 and erastin at sub-toxic doses and achieves tumor regression in patient-derived PDAC xenografts where neither agent alone has activity. KRAS mutation status strongly correlates with compound sensitivity.",
    authors_or_owner: "UT Southwestern Medical Center Technology Development",
    institution_or_sponsor: "UT Southwestern Medical Center",
    date: "2025-02-10",
    stage_hint: "preclinical",
    url: "https://www.utsouthwestern.edu/research/techtransfer",
    metadata: { licensing_status: "available", contact_office: "UTSW Technology Development", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Mitochondrial Uncoupler for Treatment-Refractory NASH and Obesity",
    text: "A controlled-release oral mitochondrial uncoupler that safely increases hepatic proton leak to stimulate fat oxidation in the liver without the systemic toxicity that has limited prior uncoupling approaches (2,4-DNP). Liver-targeted formulation achieves 8-fold higher liver-to-plasma concentration ratio. In diet-induced NASH mice, 8-week treatment reduces hepatic triglycerides by 75%, resolves inflammatory infiltrate, and reduces liver fibrosis by 60% vs vehicle. No cardiac thermogenic effects at 5x therapeutic dose.",
    authors_or_owner: "UT Southwestern Medical Center Technology Development",
    institution_or_sponsor: "UT Southwestern Medical Center",
    date: "2024-09-18",
    stage_hint: "preclinical",
    url: "https://www.utsouthwestern.edu/research/techtransfer",
    metadata: { licensing_status: "available", contact_office: "UTSW Technology Development", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Endosomal Escape Peptide Platform for Cytosolic Delivery of Protein Therapeutics",
    text: "A pH-responsive amphipathic peptide that incorporates into endosomal membranes at acidic pH and mediates membrane disruption and cytosolic release of co-delivered protein cargo with >40% efficiency. The platform dramatically outperforms existing endosomal escape strategies (chloroquine, photosensitizers) and is compatible with antibody-drug conjugates, protein PROTACs, and GFP reporter proteins. Enables a new class of protein-based therapeutics that require cytosolic access.",
    authors_or_owner: "UT Southwestern Medical Center Technology Development",
    institution_or_sponsor: "UT Southwestern Medical Center",
    date: "2024-05-12",
    stage_hint: "preclinical",
    url: "https://www.utsouthwestern.edu/research/techtransfer",
    metadata: { licensing_status: "available", contact_office: "UTSW Technology Development", patent_status: "patent pending", owner_type: "university" },
  },
];

export function getUtSouthwesternListings(): RawSignal[] {
  return UTSW_LISTINGS.map((l, i) => ({ ...l, id: `utsw-tt-${i}` }));
}
