import type { RawSignal } from "../../types";

const UW_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "RoseTTAFold-Guided De Novo Protein Drug Design Platform",
    text: "The University of Washington Institute for Protein Design has developed a computational pipeline combining RoseTTAFold structure prediction with de novo design algorithms to create entirely novel therapeutic proteins. The platform generates miniproteins, binders, and enzymes with nanomolar affinity to validated drug targets. Multiple candidates targeting cancer, respiratory disease, and rare genetic disorders are in lead optimization. IP covers both the design methodology and specific protein scaffolds.",
    authors_or_owner: "UW CoMotion",
    institution_or_sponsor: "University of Washington",
    date: "2024-09-18",
    stage_hint: "discovery",
    url: "https://comotion.uw.edu",
    metadata: { licensing_status: "available", contact_office: "UW CoMotion Technology Transfer", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Chemically Modified mRNA with Enhanced Stability for Protein Replacement",
    text: "UW researchers have developed a suite of chemical modifications to mRNA that extend in vivo half-life from hours to weeks without triggering innate immune responses. The approach combines pseudouridine substitutions, 5' cap analogs, and 3' UTR engineering. Validated in mouse, rat, and non-human primate models for factor VIII replacement (hemophilia A), erythropoietin, and CFTR protein. Scalable synthesis process compatible with lipid nanoparticle delivery.",
    authors_or_owner: "UW CoMotion",
    institution_or_sponsor: "University of Washington",
    date: "2024-03-10",
    stage_hint: "preclinical",
    url: "https://comotion.uw.edu",
    metadata: { licensing_status: "available", contact_office: "UW CoMotion Technology Transfer", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Blood-Brain Barrier Shuttle Peptide for CNS Drug Delivery",
    text: "UW has identified a class of engineered peptide shuttles that exploit endogenous transcytosis pathways to ferry biologics across the blood-brain barrier with 40-fold higher efficiency than conventional approaches. The shuttles are conjugated to antibodies, enzymes, or nucleic acid therapeutics and demonstrated robust CNS delivery in Alzheimer's, Parkinson's, and ALS models. IP covers shuttle peptide sequences, conjugation chemistry, and therapeutic conjugates.",
    authors_or_owner: "UW CoMotion",
    institution_or_sponsor: "University of Washington",
    date: "2023-12-05",
    stage_hint: "preclinical",
    url: "https://comotion.uw.edu",
    metadata: { licensing_status: "available", contact_office: "UW CoMotion Technology Transfer", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "AAV-Delivered Retinal Neuroprotection Gene Therapy",
    text: "University of Washington ophthalmology researchers have developed an AAV9 gene therapy delivering a novel neuroprotective protein to retinal ganglion cells, preventing progressive vision loss in glaucoma and retinitis pigmentosa. A single subretinal injection provides durable neuroprotection in large animal models for over 18 months. Safety and tolerability studies completed. IND-enabling studies planned for 2025.",
    authors_or_owner: "UW CoMotion",
    institution_or_sponsor: "University of Washington",
    date: "2024-07-22",
    stage_hint: "preclinical",
    url: "https://comotion.uw.edu",
    metadata: { licensing_status: "available", contact_office: "UW CoMotion Technology Transfer", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Computational Antibody Design Platform for Rapid Epitope Targeting",
    text: "UW's computational antibody design platform generates high-affinity antibodies against any structural epitope within 6 weeks, bypassing conventional immunization campaigns. The platform uses Rosetta-based docking and deep learning-guided sequence optimization to design binders with sub-nanomolar affinity. Applications span oncology (neoantigens), infectious disease, and autoimmunity. Validated against 50+ targets with 85% success rate in experimental affinity validation.",
    authors_or_owner: "UW CoMotion",
    institution_or_sponsor: "University of Washington",
    date: "2024-04-30",
    stage_hint: "discovery",
    url: "https://comotion.uw.edu",
    metadata: { licensing_status: "available", contact_office: "UW CoMotion Technology Transfer", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Senolytic Navitoclax Analog with Improved Selectivity",
    text: "UW aging researchers have synthesized a series of navitoclax analogs with dramatically improved selectivity for senescent cells over normal tissue, addressing the primary dose-limiting toxicity (thrombocytopenia) of the parent compound. Lead candidate demonstrates 20-fold selectivity window in cellular assays and confirms senescent cell clearance in aged mouse models with improved healthspan measures. Drug-like properties fully optimized for oral bioavailability.",
    authors_or_owner: "UW CoMotion",
    institution_or_sponsor: "University of Washington",
    date: "2023-10-15",
    stage_hint: "preclinical",
    url: "https://comotion.uw.edu",
    metadata: { licensing_status: "available", contact_office: "UW CoMotion Technology Transfer", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Self-Assembling Vaccine Nanoparticle Platform for Respiratory Pathogens",
    text: "The UW Institute for Protein Design has developed self-assembling protein nanoparticle scaffolds displaying viral antigens in multivalent, geometry-optimized arrays that elicit superior immune responses. The platform has been applied to influenza hemagglutinin, RSV F protein, and coronavirus spike variants. Clinical trials for the RSV construct have demonstrated durable protection. The platform technology is broadly applicable to any surface antigen.",
    authors_or_owner: "UW CoMotion",
    institution_or_sponsor: "University of Washington",
    date: "2024-01-08",
    stage_hint: "phase 1",
    url: "https://comotion.uw.edu",
    metadata: { licensing_status: "available", contact_office: "UW CoMotion Technology Transfer", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Cryo-EM Guided Covalent Fragment Drug Discovery Platform",
    text: "UW structural biologists have developed a cryo-EM guided fragment screening platform that identifies covalent fragments binding to previously undruggable cryptic pockets revealed under cryogenic conditions. The approach dramatically expands the druggable proteome and has yielded lead compounds against RAS, KEAP1, and transcription factor targets. Fragment-to-lead optimization is integrated with the structural pipeline for rapid iteration.",
    authors_or_owner: "UW CoMotion",
    institution_or_sponsor: "University of Washington",
    date: "2024-06-17",
    stage_hint: "discovery",
    url: "https://comotion.uw.edu",
    metadata: { licensing_status: "available", contact_office: "UW CoMotion Technology Transfer", patent_status: "patent pending", owner_type: "university" },
  },
];

export function getUwListings(): RawSignal[] {
  return UW_LISTINGS.map((listing) => ({
    ...listing,
    id: `uw-${Math.random().toString(36).slice(2, 9)}`,
  }));
}
