import type { RawSignal } from "../../types";

const VANDERBILT_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "Broadly Neutralizing Antibody Cocktail for Pandemic-Ready Influenza Prophylaxis",
    text: "Vanderbilt's Vanderbilt Vaccine Center has isolated a pair of human monoclonal antibodies targeting the highly conserved stem and receptor-binding site of influenza HA that neutralizes all tested Group 1 and Group 2 influenza A strains, including H5N1 and H7N9 pandemic candidates. The combination achieves prophylactic protection in ferret models against lethal H5N1 challenge. IP covers the antibody sequences, the combination epitope strategy, and the manufacturing cell lines.",
    authors_or_owner: "Vanderbilt Center for Technology Transfer and Commercialization",
    institution_or_sponsor: "Vanderbilt University",
    date: "2025-01-15",
    stage_hint: "preclinical",
    url: "https://cttc.vanderbilt.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Vanderbilt CTTC", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Structure-Based mGluR5 Negative Allosteric Modulator for Fragile X Syndrome",
    text: "A novel series of mGluR5 negative allosteric modulators (NAMs) designed using cryo-EM structures of the receptor in its inactive state, achieving >1000-fold selectivity for mGluR5 over other mGluR subtypes. In Fmr1 KO mouse models of Fragile X syndrome, the lead compound reverses audiogenic seizure susceptibility, hyperactivity, and social interaction deficits at well-tolerated doses. Clean CNS PK profile (brain/plasma = 4.2, Kp,uu = 0.8).",
    authors_or_owner: "Vanderbilt Center for Technology Transfer and Commercialization",
    institution_or_sponsor: "Vanderbilt University",
    date: "2024-08-28",
    stage_hint: "preclinical",
    url: "https://cttc.vanderbilt.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Vanderbilt CTTC", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Pan-Coronavirus Vaccine Using Mosaic Spike Nanoparticles",
    text: "A pan-coronavirus vaccine displaying mosaic arrays of spike receptor-binding domains from 8 diverse coronavirus strains on a ferritin nanoparticle scaffold. Immunization elicits broadly cross-reactive antibodies against all tested sarbecoviruses (SARS-CoV-1, SARS-CoV-2 variants, bat coronaviruses WIV1 and SHC014) in mice and NHPs at titers protective against lethal challenge. Designed as a 'pan-sarbecovirus' preparedness vaccine.",
    authors_or_owner: "Vanderbilt Center for Technology Transfer and Commercialization",
    institution_or_sponsor: "Vanderbilt University",
    date: "2024-06-10",
    stage_hint: "preclinical",
    url: "https://cttc.vanderbilt.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Vanderbilt CTTC", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "CXCR2 Antagonist for Neutrophil-Driven ARDS and Sepsis",
    text: "A potent, selective CXCR2 small molecule antagonist that blocks neutrophil trafficking to inflamed lungs in ARDS, sepsis, and severe COVID-19-related acute lung injury. IV and oral formulations demonstrate equivalent efficacy in LPS-induced and cecal ligation puncture sepsis models, reducing lung neutrophil infiltration by >80% and improving survival. The compound is differentiated from prior CXCR2 programs by its exceptional selectivity (>1000-fold vs CXCR1) and clean hERG safety profile.",
    authors_or_owner: "Vanderbilt Center for Technology Transfer and Commercialization",
    institution_or_sponsor: "Vanderbilt University",
    date: "2024-11-20",
    stage_hint: "preclinical",
    url: "https://cttc.vanderbilt.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Vanderbilt CTTC", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Wnt Pathway Activator for Bone Regeneration and Osteoporosis",
    text: "A small molecule activator of the LRP5/6 co-receptor in the canonical Wnt signaling pathway that promotes bone formation without the anabolic/catabolic coupling limitations of bisphosphonates. The compound increases trabecular bone volume by >35% in ovariectomized mice after 8 weeks of oral dosing, with no ectopic calcification or hepatotoxicity signals at 10x therapeutic dose. Potential applications in osteoporosis and fracture healing.",
    authors_or_owner: "Vanderbilt Center for Technology Transfer and Commercialization",
    institution_or_sponsor: "Vanderbilt University",
    date: "2024-09-05",
    stage_hint: "preclinical",
    url: "https://cttc.vanderbilt.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Vanderbilt CTTC", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "M. tuberculosis-Targeting Bactericidal with Novel MOA for Drug-Resistant TB",
    text: "A novel bicyclic scaffold identified via whole-cell phenotypic screen against Mtb that kills both replicating and non-replicating (persistent) Mtb at nanomolar concentrations and retains full activity against MDR-TB and XDR-TB clinical isolates. Mechanism of action studies confirm inhibition of a previously untargeted metabolic pathway (mycobacterial CoA biosynthesis), ensuring no cross-resistance with current TB drugs. Oral bioavailability >60% in mouse pharmacokinetics.",
    authors_or_owner: "Vanderbilt Center for Technology Transfer and Commercialization",
    institution_or_sponsor: "Vanderbilt University",
    date: "2025-02-28",
    stage_hint: "preclinical",
    url: "https://cttc.vanderbilt.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Vanderbilt CTTC", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Platelet-Inspired Synthetic Hemostatic Nanoparticle for Trauma Hemorrhage",
    text: "A synthetic platelet nanoparticle that carries fibrin-binding peptides and von Willebrand factor-binding motifs that home to sites of vascular injury and co-localize with natural platelets to accelerate hemostasis. IV-injectable, room-temperature stable formulation achieves 3x faster hemorrhage control versus saline in a liver laceration trauma model. Designed for pre-hospital or battlefield use where platelet transfusion is not possible.",
    authors_or_owner: "Vanderbilt Center for Technology Transfer and Commercialization",
    institution_or_sponsor: "Vanderbilt University",
    date: "2024-07-22",
    stage_hint: "preclinical",
    url: "https://cttc.vanderbilt.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Vanderbilt CTTC", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Small Molecule Corrector of Mutant CFTR for Cystic Fibrosis Class II Mutations",
    text: "A novel corrector of CFTR protein folding defects for F508del and other Class II CFTR mutations, designed to complement the distinct mechanism of CFTR modulators (e.g. VX-770, VX-445). Structural studies confirm binding to a novel allosteric site on NBD1, distinct from existing correctors. Combination with tezacaftor in organoids from F508del homozygous patients achieves CFTR function restoration equivalent to elexacaftor-tezacaftor-ivacaftor at half the corrector doses, suggesting strong synergy.",
    authors_or_owner: "Vanderbilt Center for Technology Transfer and Commercialization",
    institution_or_sponsor: "Vanderbilt University",
    date: "2024-10-30",
    stage_hint: "discovery",
    url: "https://cttc.vanderbilt.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Vanderbilt CTTC", patent_status: "patent pending", owner_type: "university" },
  },
];

export function getVanderbiltListings(): RawSignal[] {
  return VANDERBILT_LISTINGS.map((l, i) => ({ ...l, id: `vanderbilt-tt-${i}` }));
}
