import type { RawSignal } from "../../types";

const WARF_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "First-in-Class NAMPT Inhibitor for Solid Tumors with Selective Tumor Targeting",
    text: "WARF chemists have developed a next-generation NAMPT inhibitor with a tumor-selective prodrug strategy that dramatically reduces the dose-limiting hematological toxicity that halted earlier NAMPT inhibitor programs. The compound is activated preferentially in the low-pH tumor microenvironment, achieving >20-fold tumor-to-plasma drug ratio. Demonstrated tumor regression in breast, colon, and lung cancer xenograft models at doses well below the bone marrow toxicity threshold.",
    authors_or_owner: "Wisconsin Alumni Research Foundation",
    institution_or_sponsor: "University of Wisconsin-Madison",
    date: "2025-01-10",
    stage_hint: "preclinical",
    url: "https://www.warf.org/technologies",
    metadata: { licensing_status: "available", contact_office: "WARF", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Oral Small Molecule Inhibitor of BRD4 for Castration-Resistant Prostate Cancer",
    text: "A novel BET bromodomain inhibitor with optimized selectivity for BRD4 over BRD2/BRD3, designed to suppress MYC and AR transcriptional programs in castration-resistant prostate cancer (CRPC). The compound achieves tumor stasis in enzalutamide-resistant CRPC xenografts with a favorable oral PK profile (F=67%, half-life 8 hours in rats). The selectivity profile avoids the dose-limiting thrombocytopenia seen with pan-BET inhibitors.",
    authors_or_owner: "Wisconsin Alumni Research Foundation",
    institution_or_sponsor: "University of Wisconsin-Madison",
    date: "2024-08-22",
    stage_hint: "preclinical",
    url: "https://www.warf.org/technologies",
    metadata: { licensing_status: "available", contact_office: "WARF", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "iPSC-Derived Beta Cell Replacement Therapy for Type 1 Diabetes",
    text: "A proprietary differentiation protocol that produces functional, glucose-responsive pancreatic beta cells from iPSCs with >85% purity and insulin secretion capacity matching primary human islets. The cells are encapsulated in a PEG-based hydrogel microcapsule that confers immunoprotection without systemic immunosuppression. Euglycemia achieved for 6+ months in STZ-diabetic mice following subcutaneous implantation.",
    authors_or_owner: "Wisconsin Alumni Research Foundation",
    institution_or_sponsor: "University of Wisconsin-Madison",
    date: "2024-11-05",
    stage_hint: "preclinical",
    url: "https://www.warf.org/technologies",
    metadata: { licensing_status: "available", contact_office: "WARF", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Antisense Oligonucleotide Targeting ATXN2 for ALS and SCA2",
    text: "An ASO targeting ATXN2 mRNA designed for intrathecal delivery to reduce ATXN2 protein levels in motor neurons. ATXN2 intermediate-length polyQ expansions are the most common genetic modifier of TDP-43 proteinopathy in ALS; ATXN2 reduction extends survival in ALS mouse models. The ASO shows >80% target knockdown in CSF-accessible spinal cord motor neurons after a single intrathecal injection in NHPs.",
    authors_or_owner: "Wisconsin Alumni Research Foundation",
    institution_or_sponsor: "University of Wisconsin-Madison",
    date: "2024-06-18",
    stage_hint: "preclinical",
    url: "https://www.warf.org/technologies",
    metadata: { licensing_status: "available", contact_office: "WARF", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Oncolytic Vesicular Stomatitis Virus Engineered for Glioblastoma",
    text: "A recombinant VSV strain engineered with a tumor-selective IFN-beta transgene and a deletion of the M protein that attenuates pathogenicity in normal brain tissue while maintaining selective oncolytic activity in GBM. Intracranial delivery in syngeneic GBM mouse models achieves 40% long-term survivors with evidence of systemic anti-tumor immunity (abscopal effect). GMP manufacturing process established.",
    authors_or_owner: "Wisconsin Alumni Research Foundation",
    institution_or_sponsor: "University of Wisconsin-Madison",
    date: "2025-02-20",
    stage_hint: "preclinical",
    url: "https://www.warf.org/technologies",
    metadata: { licensing_status: "available", contact_office: "WARF", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "microRNA-Based Therapeutic for Cardiac Regeneration Post-MI",
    text: "A synthetic miR-199a mimic delivered via cardiac-tropic AAV9 that promotes cardiomyocyte re-entry into the cell cycle, driving myocardial regeneration in post-ischemic hearts. Delivery within 7 days of MI in pig models achieves significant scar reduction and left ventricular ejection fraction recovery (+15% over untreated controls) at 90 days. The treatment window and biodistribution profile are suitable for a Phase 1 protocol.",
    authors_or_owner: "Wisconsin Alumni Research Foundation",
    institution_or_sponsor: "University of Wisconsin-Madison",
    date: "2024-09-30",
    stage_hint: "preclinical",
    url: "https://www.warf.org/technologies",
    metadata: { licensing_status: "available", contact_office: "WARF", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Oral Probiotic Engineered to Produce IL-10 for Crohn's Disease",
    text: "A genetically modified Lactococcus lactis strain that secretes human IL-10 directly into the gastrointestinal lumen, achieving local mucosal anti-inflammatory effects without systemic cytokine exposure. Oral administration in murine and porcine IBD models reduces colonic inflammatory scores and mucosal cytokines with no systemic IL-10 elevation. The strain is non-colonizing and cleared within 72 hours of dosing cessation.",
    authors_or_owner: "Wisconsin Alumni Research Foundation",
    institution_or_sponsor: "University of Wisconsin-Madison",
    date: "2024-04-14",
    stage_hint: "preclinical",
    url: "https://www.warf.org/technologies",
    metadata: { licensing_status: "available", contact_office: "WARF", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Nanoparticle siRNA Platform Targeting VEGFR2 and PD-L1 for Combination Anti-Cancer Therapy",
    text: "A lipid-polymer hybrid nanoparticle co-delivering siRNA against VEGFR2 (anti-angiogenesis) and PD-L1 (checkpoint blockade) in a single formulation. The dual-silencing approach circumvents resistance mechanisms seen with antibody monotherapy and achieves superior tumor growth inhibition in NSCLC and melanoma syngeneic models compared to either siRNA alone or combination antibody therapy. Formulation is manufacturable using standard microfluidic mixing.",
    authors_or_owner: "Wisconsin Alumni Research Foundation",
    institution_or_sponsor: "University of Wisconsin-Madison",
    date: "2024-12-08",
    stage_hint: "preclinical",
    url: "https://www.warf.org/technologies",
    metadata: { licensing_status: "available", contact_office: "WARF", patent_status: "patent pending", owner_type: "university" },
  },
];

export function getWarfListings(): RawSignal[] {
  return WARF_LISTINGS.map((l, i) => ({ ...l, id: `warf-tt-${i}` }));
}
