import type { RawSignal } from "../../types";

const WASHU_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "KRAS G12C/G12D Dual Proteolysis Targeting Chimera (PROTAC)",
    text: "Washington University researchers have developed a first-in-class PROTAC targeting both KRAS G12C and G12D mutations through a novel ternary complex with the CRBN E3 ligase. The degrader achieves complete KRAS elimination in PDAC, NSCLC, and colorectal cancer models with superior durability compared to covalent inhibitors. Resistance profiling shows delayed resistance emergence. IP covers the PROTAC chemical scaffold, synthesis, and combination regimens.",
    authors_or_owner: "WashU Office of Technology Management",
    institution_or_sponsor: "Washington University in St. Louis",
    date: "2024-10-01",
    stage_hint: "preclinical",
    url: "https://otm.wustl.edu",
    metadata: { licensing_status: "available", contact_office: "WashU Office of Technology Management", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Tau Protein Clearance Enhancer for Alzheimer's Disease",
    text: "WashU neuroscientists have identified a small molecule that enhances the brain's autophagy-lysosomal system to selectively clear pathological tau aggregates without affecting normal tau function. The compound acts through the TFEB transcription factor to upregulate lysosomal biogenesis. In transgenic tauopathy mouse models, 8-week treatment reduced tau burden by 60% and restored cognitive function. Blood-brain barrier penetration and oral bioavailability confirmed.",
    authors_or_owner: "WashU Office of Technology Management",
    institution_or_sponsor: "Washington University in St. Louis",
    date: "2024-07-14",
    stage_hint: "preclinical",
    url: "https://otm.wustl.edu",
    metadata: { licensing_status: "available", contact_office: "WashU Office of Technology Management", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "TGF-β/PDGFR Dual Inhibitor for Cardiac Fibrosis",
    text: "Cardiac fibrosis affects over 15 million patients with heart failure in the US. WashU cardiovascular researchers have developed a bivalent small molecule simultaneously inhibiting TGF-β type I receptor and PDGFR-β to block the two primary drivers of pathological fibroblast activation. The compound reverses established fibrosis in pressure overload and myocardial infarction models with no cardiotoxicity signal. Differentiated from monotherapy approaches by superior antifibrotic depth.",
    authors_or_owner: "WashU Office of Technology Management",
    institution_or_sponsor: "Washington University in St. Louis",
    date: "2023-11-20",
    stage_hint: "preclinical",
    url: "https://otm.wustl.edu",
    metadata: { licensing_status: "available", contact_office: "WashU Office of Technology Management", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "NASH Therapeutic Target: Hepatic ACLY Allosteric Inhibitor",
    text: "WashU metabolism researchers discovered that allosteric inhibition of ATP-citrate lyase (ACLY) in hepatocytes reduces de novo lipogenesis by 80% while preserving mitochondrial citrate metabolism, addressing a key limitation of active-site ACLY inhibitors. A lead series has been optimized for liver selectivity using targeted lipid nanoparticle delivery. In diet-induced NASH models, the compound reverses steatosis, inflammation, and early fibrosis.",
    authors_or_owner: "WashU Office of Technology Management",
    institution_or_sponsor: "Washington University in St. Louis",
    date: "2024-02-28",
    stage_hint: "preclinical",
    url: "https://otm.wustl.edu",
    metadata: { licensing_status: "available", contact_office: "WashU Office of Technology Management", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Synthetic Lethal Vulnerability in IDH-Mutant AML",
    text: "WashU leukemia researchers have identified a synthetic lethal interaction between IDH1/2 mutations and the DNA damage response kinase WEE1 in acute myeloid leukemia. Combined IDH inhibitor and WEE1 inhibitor treatment induces selective tumor cell death while sparing normal hematopoietic progenitors. The combination is effective in IDH-inhibitor resistant AML clones. Clinical trial design in collaboration with industry partner underway.",
    authors_or_owner: "WashU Office of Technology Management",
    institution_or_sponsor: "Washington University in St. Louis",
    date: "2024-05-15",
    stage_hint: "preclinical",
    url: "https://otm.wustl.edu",
    metadata: { licensing_status: "available", contact_office: "WashU Office of Technology Management", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Gut Microbiome Metabolite Panel for Immunotherapy Response Prediction",
    text: "A WashU oncology team has identified a panel of 8 fecal metabolites that predict response to PD-1/PD-L1 checkpoint immunotherapy with 78% accuracy before treatment initiation. The metabolites, produced by specific Clostridiales species, modulate dendritic cell maturation and CD8 T cell priming. The companion diagnostic panel uses standard metabolomics LC-MS from stool samples. Validated in melanoma, NSCLC, and urothelial cancer cohorts.",
    authors_or_owner: "WashU Office of Technology Management",
    institution_or_sponsor: "Washington University in St. Louis",
    date: "2023-09-10",
    stage_hint: "discovery",
    url: "https://otm.wustl.edu",
    metadata: { licensing_status: "available", contact_office: "WashU Office of Technology Management", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "iPSC-Derived Cardiomyocyte Sheet for Myocardial Infarction Repair",
    text: "Washington University has developed a scalable process for producing clinical-grade cardiomyocyte sheets from iPSCs that, when epicardially applied after MI, improve ejection fraction, reduce infarct size, and promote angiogenesis. The sheets incorporate a biodegradable fibrin scaffold for mechanical support during engraftment. Large animal porcine MI studies demonstrate 15% absolute improvement in ejection fraction at 6 months. GMP manufacturing process established.",
    authors_or_owner: "WashU Office of Technology Management",
    institution_or_sponsor: "Washington University in St. Louis",
    date: "2024-08-30",
    stage_hint: "preclinical",
    url: "https://otm.wustl.edu",
    metadata: { licensing_status: "available", contact_office: "WashU Office of Technology Management", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Myeloid Checkpoint Antibody Targeting SIRPα-CD47 Axis Enhancement",
    text: "WashU immunologists have developed a bispecific antibody that simultaneously blocks SIRPα on macrophages and enhances phagocytic signaling through a novel activating Fc domain engineering approach. This dual mechanism produces greater cancer cell phagocytosis than CD47 blockade alone and avoids the red blood cell toxicity seen with CD47 antibodies. Validated in xenograft and syngeneic tumor models with strong combination activity with anti-PD-1.",
    authors_or_owner: "WashU Office of Technology Management",
    institution_or_sponsor: "Washington University in St. Louis",
    date: "2024-11-12",
    stage_hint: "preclinical",
    url: "https://otm.wustl.edu",
    metadata: { licensing_status: "available", contact_office: "WashU Office of Technology Management", patent_status: "patent pending", owner_type: "university" },
  },
];

export function getWashuListings(): RawSignal[] {
  return WASHU_LISTINGS.map((listing) => ({
    ...listing,
    id: `washu-${Math.random().toString(36).slice(2, 9)}`,
  }));
}
