import type { RawSignal } from "../../types";

const WEILL_CORNELL_LISTINGS: Array<Omit<RawSignal, "id">> = [
  {
    source_type: "tech_transfer",
    title: "Prostate Cancer Liquid Biopsy Using Urine-Based AR Splice Variant Detection",
    text: "A urine-based assay that simultaneously quantifies AR-V7 and AR-V9 splice variants — the primary resistance mechanisms to enzalutamide and abiraterone — from a non-invasive first-catch urine sample. Validated in 280-patient prospective CRPC cohort: AR-V7 positive patients had zero PSA response to AR-targeted therapy (100% NPV for therapy failure), enabling immediate pivot to taxane-based regimens and reducing treatment futility. CE-IVD eligible assay design.",
    authors_or_owner: "Weill Cornell Medicine Innovation",
    institution_or_sponsor: "Weill Cornell Medicine",
    date: "2024-10-20",
    stage_hint: "discovery",
    url: "https://innovation.weill.cornell.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Weill Cornell Innovation", patent_status: "patented", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Targeted Alpha Therapy Construct for Fibroblast Activation Protein (FAP) in Stroma-Rich Tumors",
    text: "A small molecule FAP-targeting ligand conjugated to actinium-225 or bismuth-213 for targeted alpha particle delivery to the tumor stroma of FAP-high solid tumors, including pancreatic cancer, mesothelioma, and TNBC. FAP is expressed on >90% of cancer-associated fibroblasts across major solid tumor types, providing broad applicability. Biodistribution studies show excellent FAP-specific tumor accumulation with low kidney and salivary gland uptake. IP covers targeting ligand, chelator, and dosing protocol.",
    authors_or_owner: "Weill Cornell Medicine Innovation",
    institution_or_sponsor: "Weill Cornell Medicine",
    date: "2025-02-08",
    stage_hint: "preclinical",
    url: "https://innovation.weill.cornell.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Weill Cornell Innovation", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "EZH2 Inhibitor with Superior Activity in NSD1/NSD2-Mutant Lymphomas",
    text: "A next-generation EZH2 catalytic inhibitor with a distinct binding mode that retains activity against EZH2 mutations (Y641F/N/S/H, A677G) that confer resistance to tazemetostat. The compound additionally shows activity in NSD1-mutant and NSD2-mutant lymphomas — subtypes not responsive to existing EZH2 inhibitors — suggesting a distinct mechanism beyond EZH2 catalytic inhibition. Demonstrated in >40 lymphoma cell lines and 6 patient-derived xenograft models.",
    authors_or_owner: "Weill Cornell Medicine Innovation",
    institution_or_sponsor: "Weill Cornell Medicine",
    date: "2024-07-18",
    stage_hint: "preclinical",
    url: "https://innovation.weill.cornell.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Weill Cornell Innovation", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Engineered Bacteria for Tumor-Selective Cytokine Delivery",
    text: "A genetically attenuated Salmonella strain engineered to produce and release IL-15 superagonist and anti-CD47 nanobody specifically within the hypoxic tumor microenvironment. The strain is auxotrophic outside the tumor and self-amplifies only under low-oxygen, high-nutrient conditions of solid tumors. Intravenous injection leads to selective colonization and cytokine production at tumor sites, achieving local immune activation without systemic cytokine syndrome. Demonstrated in syngeneic colorectal and melanoma models.",
    authors_or_owner: "Weill Cornell Medicine Innovation",
    institution_or_sponsor: "Weill Cornell Medicine",
    date: "2024-05-08",
    stage_hint: "preclinical",
    url: "https://innovation.weill.cornell.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Weill Cornell Innovation", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "HDAC6 Selective Inhibitor for Multiple Myeloma and Peripheral Neuropathy",
    text: "A selective HDAC6 inhibitor with >500-fold selectivity over other HDAC isoforms, designed for dual application in multiple myeloma (where HDAC6 regulates the aggresome pathway and protein homeostasis) and chemotherapy-induced peripheral neuropathy (CIPN), where HDAC6 inhibition restores axonal transport. The compound is active in bortezomib-resistant myeloma lines and reduces cisplatin-induced neuropathy in murine and NHP models without reducing cisplatin antitumor efficacy.",
    authors_or_owner: "Weill Cornell Medicine Innovation",
    institution_or_sponsor: "Weill Cornell Medicine",
    date: "2024-12-05",
    stage_hint: "preclinical",
    url: "https://innovation.weill.cornell.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Weill Cornell Innovation", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Inhalable siRNA Lipid Nanoparticle for Idiopathic Pulmonary Fibrosis",
    text: "An inhalable dry powder lipid nanoparticle formulation delivering siRNA against TGF-β1 and CTGF, the two primary fibrogenic mediators in IPF, directly to lung alveolar macrophages and type II pneumocytes via nebulization. Achieves >80% gene silencing in lung tissue with minimal systemic exposure, avoiding the systemic toxicity of systemic anti-TGF-β approaches. In bleomycin mouse IPF models, twice-weekly inhalation prevents and partially reverses established pulmonary fibrosis.",
    authors_or_owner: "Weill Cornell Medicine Innovation",
    institution_or_sponsor: "Weill Cornell Medicine",
    date: "2025-01-10",
    stage_hint: "preclinical",
    url: "https://innovation.weill.cornell.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Weill Cornell Innovation", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Single-Cell Spatial Transcriptomics Biomarker for Immunotherapy Patient Selection",
    text: "A tissue-based spatial transcriptomics analysis pipeline that quantifies the spatial relationship between CD8+ T cells and immune exclusion markers (TGF-β signaling, Wnt/β-catenin activity, myofibroblast density) in the tumor microenvironment. In a 380-patient retrospective cohort across NSCLC, melanoma, and RCC, the spatial score predicted anti-PD-1 response with AUC=0.89, substantially outperforming standard PD-L1 IHC. Validation cohort prospective study ongoing.",
    authors_or_owner: "Weill Cornell Medicine Innovation",
    institution_or_sponsor: "Weill Cornell Medicine",
    date: "2024-09-25",
    stage_hint: "discovery",
    url: "https://innovation.weill.cornell.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Weill Cornell Innovation", patent_status: "patent pending", owner_type: "university" },
  },
  {
    source_type: "tech_transfer",
    title: "Bacteriophage-Antibiotic Synergy Platform for Drug-Resistant Gram-Negative Infections",
    text: "A phage-antibiotic combination strategy that uses a non-replicating phage cocktail to sensitize carbapenem-resistant Klebsiella pneumoniae and Acinetobacter baumannii to previously ineffective antibiotics via phage-mediated outer membrane disruption. The phage cocktail resensitizes >85% of tested XDR clinical isolates to meropenem or colistin. Available as a companion therapeutic to standard antibiotics for compassionate use IND or as a platform license for phage-antibiotic combination development.",
    authors_or_owner: "Weill Cornell Medicine Innovation",
    institution_or_sponsor: "Weill Cornell Medicine",
    date: "2024-11-12",
    stage_hint: "preclinical",
    url: "https://innovation.weill.cornell.edu/technologies",
    metadata: { licensing_status: "available", contact_office: "Weill Cornell Innovation", patent_status: "patent pending", owner_type: "university" },
  },
];

export function getWeillCornellListings(): RawSignal[] {
  return WEILL_CORNELL_LISTINGS.map((l, i) => ({ ...l, id: `weillcornell-tt-${i}` }));
}
